[클린코드 리액트 3기 엄지연] 페이먼츠 미션 Step1
next-step/react-payments pull request #108
Opened 2024-03-01 19:23 UTC by jjiyeon

안녕하세요 승찬님😃
저는 첫번째 미션부터 사용해 보지 않았던 스토리북으로 부담감을 안고 시작하느라 조금 늦게 올리게 된 점 양해부탁드립니다.
요구사항에 대한 범위와 설계를 고민하면서 아직 진행중인 기능까지 올리고 피드백 받으면서 방향을 잡아가려고 합니다(더 늦어질까봐..ㅠ)

고민거리
1. 정규표현식으로 최대한 간결하게 validation 체크를 하려고 했으나, 조금 아쉬운 함수가 되었습니다. 빈틈이 많을바에 우직하게 하나하나 체크하는 로직이 더 나을지 고민이예요.
2. 확장성 있는 구조로 설계하려고 해보았는데, 어디가 확장성있는지 모르겠어요..ㅎ
3. 사실 더 있는것 같은데, 피드백 수정하면서 공유드릴게요!

 
- [ ] 원시적인 형태의 Primitive UI 형태의 컴포넌트 작성
- [ ] Funnel 기반의 애플리케이션 설계
- [ ] Storybook 상호 작용 테스트
- [ ] Controlled & Uncontrolled Components를 명확하게 구분하거나 선택하여 구현

카드 추가

- [ ] <(뒤로가기) 버튼 클릭 시, 카드 목록 페이지로 이동한다.
- [ ] 카드 번호를 입력 받을 수 있다.
- [ ] 카드 번호는 숫자만 입력가능하다.
- [ ] 카드 번호 4자리마다 -가 삽입된다.
- [ ] 카드 번호는 실시간으로 카드 UI에 반영된다.
- [ ] 카드 번호는 앞 8자리만 숫자로 보여지고, 나머지 숫자는 *로 보여진다.
- [ ] 만료일을 입력 받을 수 있다.

- [ ] MM / YY 로 placeholder를 적용한다.
- [ ] 월, 년 사이에 자동으로 /가 삽입된다.
- [ ] 만료일은 실시간으로 카드 UI에 반영된다.
- [ ] 월은 1이상 12이하 숫자여야 한다.
- [ ] 보안코드를 입력 받을 수 있다.

- [ ] 보안코드는 *으로 보여진다.
- [ ] 보안코드는 숫자만 입력가능하다.
- [ ] 카드 비밀번호의 앞 2자리를 입력 받을 수 있다.

- [ ] 카드 비밀번호는 각 폼마다 한자리 숫자만 입력가능하다.
- [ ] 카드 번호 입력 시, *으로 보여진다.
- [ ] 카드 소유자 이름을 입력 받을 수 있다.

- [ ] 이름은 30자리까지 입력할 수 있다.
- [ ] 이름 입력 폼 위에, 현재 입력 자릿수와 최대 입력 자릿수를 실시간으로 보여준다.
- [ ] 카드 추가 완료시 카드 등록 완료 페이지로 이동한다.

2024-03-03 16:23 UTC, onschan requested changes
안녕하세요. 지연님! 리뷰를 담당하게된 온승찬입니다 😊

전혀 느리지 않고 빠르게 잘 올려주셨는데요?! 오히려 제가 늦게 리뷰를 달게 되어서 죄송합니다.. 🥲 

미션 진행하시느라 수고많으셨고 리뷰에 대해 질문 및 답변 남겨주시면 빠르게 찾아올게요!! 

### 질문 해주신 내용에 대한 답변

> 정규표현식으로 최대한 간결하게 validation 체크를 하려고 했으나, 조금 아쉬운 함수가 되었습니다. 빈틈이 많을바에 우직하게 하나하나 체크하는 로직이 더 나을지 고민이예요. 카드번호와 마스킹 처리는 어거지로 만든것 같은데, 날짜에서 왜 멘붕..😲
> 

아마 아쉬움이 유발된 포인트는 정규 표현식 사용 자체의 문제보다는 데이터 관리 영역과 UI 영역이 섞여서 관리되어서 복잡해지고 있는 것으로 보여요.

현재 useMasking 훅에서 `*` 이라는 값이 포함된 데이터가 상태로 저장되고 있는 상황이에요.

만약 Input을 통해 유저에게 정보를 입력 받아서 카드를 등록 API에 해당 데이터들을 보내야하는 상황이라면 `*` 으로 저장된 데이터가 유효한 데이터로 볼 수 있을까요?

지금처럼 하나의 input에서 모든 카드 번호을 관리하고 e.target.value에서도 마스킹된 값들을 바라보고있는 상황이라면 계속 고민에 빠질 것 같은데요.

이런 요구 사항이면 어떨까요?

- [ ]  카드 번호는 4자리의 숫자 input 4개로 관리된다.
- [ ]  마지막 두 개의 input은 마스킹된 값으로 노출된다. (input css 혹은 type을 수정하면 실제 value와 UI 노출되는 값이 다르게 보일거에요.)

카드 정보를 예시로 생각하면 [1111, 2222, 3333, 4444] 라는 값으로 저장되고 3333, 4444 값은 마스킹된 값으로만 렌더링한다는 요구 사항으로 생각하시면 좋을 것 같네요!

(CVC랑 비밀번호의 마스킹도 추가적으로 고민해주세요!)

(날짜에서 어떤 부분이 멘붕이셨을까요? 🧐)

> 확장성 있는 구조로 설계하려고 해보았는데, 어디가 확장성있는지 모르겠어요..ㅎ
> 

지연님께서 생각하시는 확장성 있는 구조가 어떤 걸까요? 확장 가능한 구조로 설계하기 위해 어떤 고민이 있으셨는지에 대해 공유해주시면 좀 더 좋은 방향으로 제 생각을 공유해드릴 수 있을 것 같아요!

현재 미션에 제공된 요구 사항을 개발하면서 고민할 수 있는 포인트 중, 확장성있는 구조를 위해 중요하다고 생각하는 부분을 체크리스트로 제공해드릴테니 셀프 체크를 한번 해보시고 다시 질문 주실 수 있을까요?

- [ ]  재사용 가능한 컴포넌트를 만들었고 분리되어있나요?
- [ ]  각 컴포넌트는 하나의 역할만 수행하고 있나요?
- [ ]  명확한 기준으로 상태를 관리하고 있나요?
- [ ]  디렉토리와 모듈이 일관되게 관리되고 있나요?
- [ ]  코드가 일관되게 작성되고 있나요?

> 원시적인 형태의 Primitive UI 형태의 컴포넌트 작성을..제가 잘 이해한걸까요?😅
> 

단순히 코드를 기반으로 말씀드리기에는 설명에 모호함이 있을 것 같아서 제 생각을 코멘트로 달았다가 이 부분은 지연님의 말씀을 듣고 더 말씀을 드리는 편이 좋을 것 같아서 지웠어요. 

지연님께서 Primitive UI 형태의 컴포넌트를 어떤 식으로 이해하시고 의도하셨는지 설명해주시면 좋을 것 같아요! 

Primitive UI 형태의 컴포넌트가 정확히 무엇이냐 보다는 해당 키워드가 필수 요구 사항인 이유가 무엇일까요?

이 부분에 지연님의 생각을 공유해주신다면 좋은 방향으로 이야기 해볼 수 있을 것 같아요!

---

### 리뷰 사항

1. 스토리북의 기본 example 파일들은 제거 후 PR을 다시 올려주시면 감사하겠습니다! example 요소들은 제외하고 파일 체인지를 보려고했는데 example 컴포넌트가 로직에도 사용되는 부분이 있는 것 같아요 😅
2. 스토리북은 컴포넌트를 문서화하고 테스트를 해볼 수 있는 툴일 뿐이지 프로젝트 구조와는 관련이 없어야합니다. stories 디렉토리 안에서 관리하는 컴포넌트들은 프로젝트 구조와 통일되게 옮겨주세요!
3. 스토리북은 만들어진 컴포넌트의 문서화 용도로 사용될 수도 있지만 지연님께서 질문해주신 확장성 있는 컴포넌트, 원시적인 형태의 컴포넌트를 만들때 도메인과 분리해서 테스트해보기 좋은 테스팅 툴로 사용할 수도 있습니다. 이번 미션을 통해 해당 경험을 해보셔도 좋을 것 같아요!
4. 전체적으로 잘 작성해주셨고 프로젝트 구조적인 부분에 대해서는 비합리적인 부분으로 보이는 부분은 없어서 현재 구조로 유지해주시면서 잘 진행해주시면 감사하겠습니다!
5. 리뷰에도 담겨있지만 반복되고 있는 로직이 있어서 한번 더 코멘트를 남기자면 상태 변경을 위한 useEffect가 로직 중 필요한 상황이 나온다면 꼭 필요한 부분이 맞는지 한번 더 의심해보시면 좋을 것 같아요!

2024-03-03 16:23 UTC, onschan commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/macos,windows,node,react
PR 올리시고 습관처럼 위처럼 eol 공백이 생략되어있지 않는지 한번씩 체크해주시면 좋을 것 같아요!

2024-03-03 16:23 UTC, onschan commented on .prettierrc
> +  }
프리티어의 eol 옵션도 넣어주셨는데 막상 해당 파일에는 생략되어있네여 😅

2024-03-03 16:23 UTC, onschan commented on src/AddCard.tsx
> +const AddCard = ({ onBack, onNext }: StepProps) => {
AddCard 컴포넌트에 StepProps라는 타입으로 prop들을 받으니 어떤 연관성이 있는거지? 라고 먼저 생각이 드는 것 같아요.

현재 상황에서는 StepProps보다는 AddCardProps가 나을 것 같아요.

2024-03-03 16:23 UTC, onschan commented on src/index.tsx
> +  | { step: 'list' }
```suggestion
type Step = 'add' | 'select' | 'list'

export type FunnelStep = { step: Step }
```

step의 종류만 별도로 관리해도 괜찮을 것 같아요! 😄

2024-03-03 16:23 UTC, onschan commented on src/stories/Input.tsx
> +  )
```
   <div className={ui['input-container']}>
      <span className={ui['input-title']}>Label</span>
      <div className={ui['input-box']}>
        <Input
        ...
        />
      </div>
    </div>
```
Card에서 사용되는 Input 관련 컴포넌트들에 해당 코드들이 중복적으로 발생하고 있는 부분이 있는데
Input 컴포넌트의 역할로 공통화 시켜볼까요?

2024-03-03 16:23 UTC, onschan commented on src/stories/Header.stories.ts
> +  title: 'Example/Header',
스토리북 설치시 함께 설치되는 예제 코드들은 제외시켜서 올려주시면 감사하겠습니다! 😊

2024-03-03 16:23 UTC, onschan commented on src/index.tsx
> +  )
현재 로직들을 기반으로 간단하게 Stepper라는 컴포넌트로 추상화해보실까요?

Stepper의 역할은 선언적으로 각 Step에 해당하는 컴포넌트를 렌더링해주는 역할 정도면 충분할 것 같아요.

해당 작업 중 궁금한 점이 있으시면 질문 남겨주시면 지속적으로 확인할게요!

추가적으로 현재 상태로 관리되고있는 step은 꼭 상태로 관리되어야만 할지? 다른 방법은 없을지? 장단점은 무엇일지? 에 대해서 고민해보시면 좋을 것 같아요!

2024-03-03 16:23 UTC, onschan commented on src/AddCard.tsx
> +      {isShowModal && <CardType setIsShowModal={() => setIsShowModal(false)} />}
```suggestion
      {isShowModal && <CardType closeModal={() => setIsShowModal(false)} />}
```

setIsShowModal(false)를 실행하려는 함수를 넘기는 prop의 이름이 setIsShowModal 그대로인 부분은 어색한 것 같아요!

2024-03-03 16:23 UTC, onschan commented on src/components/CardBox/index.tsx
> +export const CardBox = () => {
```suggestion
import { useContext } from 'react'
import { CardInfoContext } from '../../context/paymentContext'
import ui from '../../styles/index.module.css'

export const CardBox = () => {
```

import문과 모듈 내부 코드, 관심사 그루핑이 필요한 부분 등에 공백을 이용해서 코드들을 잘 분리하시면 읽는 사람 입장에서 더 읽기 수월해질거에요.

잘해주시고 있는 부분들이 많은데 코드 중간중간 통일되지 않은 부분들이 있어서 지연님께서는 평소 어떤식으로 하시고 계셨는지 스스로 고민해보시고 코드 작성시 의식적으로 공백에도 신경써주시면 좋을 것 같아요!

```
import Something from './someModule'
type SomeProp = { something: string; }
export const SomeComponent = () => {
    const [state, setState] = useState();
    const handleSomeEvent = () => {}
    useEffect(() => {},[])
    return (<div/>)
}
```

```
import Something from './someModule'

type SomeProp = { something: string; }

export const SomeComponent = () => {
    const [state, setState] = useState();

    const handleSomeEvent = () => {}

    useEffect(() => {},[])

    return (<div/>)
}
```
저는 위 코드보다는 아래코드가 더 보기에 좋다고 생각해요 🧐

2024-03-03 16:23 UTC, onschan commented on src/components/CardType/index.tsx
> +            <div className={ui['modal-item-container']} key={idx}>
추가, 삭제가 일어나지 않은 상황이더라도 의식적으로 index 자체 key값은 지양해주시는게 좋아요!

2024-03-03 16:23 UTC, onschan commented on src/components/CardType/index.tsx
> +    <div className={ui['modal-dimmed']} onClick={() => setIsShowModal()}>
위에도 언급드린 부분이긴한데, set 네이밍을 가진 setIsShowModal을 인수 없이 호출했을때 자연스럽게 어색하다고 느끼신다면 좋을 것 같아요!

```suggestion
    <div className={ui['modal-dimmed']} onClick={closeModal}>
```

2024-03-03 16:23 UTC, onschan commented on src/components/CardType/index.tsx
> +  }, [selectType])
updateCardInfo.cardType와 selectType이 동일한 상태로 보이는데 두개의 상태로 관리될 이유가 있을까요? 🤔

상태 동기화를 위한 useEffect는 최대한 지향해주시는게 좋아요. 유저 인터렉션을 위한 요구 사항이 추가되어서 selectType이 변경될 시점이 더 생긴다면 어디서 상태값이 변경되는지 추적하기 어렵게 될 가능성이 커요!

```ts
 <button
    className={ui['modal-item-name']}
    onClick={() => {
        setSelectType(value)
        setIsShowModal()
    }}
>
    {value} 카드
</button>
```

대신 아래처럼 사용해도 같은 의미가 아닐까요?
```ts
 <button
    className={ui['modal-item-name']}
    onClick={() => {
        updateCardInfo({ cardType: value })
        setIsShowModal()
    }}
>
    {value} 카드
</button>
```

2024-03-03 16:23 UTC, onschan commented on src/components/CardNumber/index.tsx
> +export const CardNumber = () => {
T는 type을 뜻하는 prefix인가요? 다른 부분에서는 볼 수 없었던 부분이기도 한데 어떤 의미일까요?
만약 모호하게 사용되는 부분이라면 타입 관련 prefix는 굳이 필요없을 것 같아요!

추가로 해당 컴포넌트에서 사용되는 부분이 아닌것 같은데 useMasking 관련 부분에 이동하는 편이 어떨까요?

2024-03-03 16:23 UTC, onschan commented on src/hooks/useMasking.ts
> +const useMasking = (props: Partial<TInputProps>) => {
Partial이 필요한 이유가 있을까요? 하단의 로직상 props.number 같은 부분은 옵셔널 보다는 기본값으로 필요한 부분으로 보여요.

필요에 의해 Partial로 전부 옵셔널로 바꾸셨다면 undefined에 대한 방어로직 혹은

```ts
const { number = 4, ...restProps} = props;
```
처럼 기본값 지정은 해주시는게 좋을 것 같아요

2024-03-03 16:23 UTC, onschan commented on src/hooks/useMasking.ts
> +const useMasking = (props: Partial<TInputProps>) => {
상태를 가지는 useMasking 훅이 필요할까? 라는 생각이 먼저 드네요. 

해당 훅에서 사용하는 masking이라는 상태와 카드 정보를 저장하는 상태의 싱크를 맞추기위해 useEffect가 수반되어야하는 케이스가 발생하기도하는데, 요구 사항에서는 카드 번호, 비밀 번호, CVC는 해당 컴포넌트에서 Input Change 이벤트에서 ConetxtAPI에서 관리하는 값을 수정하는 부분으로도 충분할 것 같아요.

마스킹 구현 방향의 개선에 대해서는 PR 코멘트에 따로 남기겠지만 해당 훅에 대한 코멘트만 남기자면 해당 훅의 역할은 유틸 함수로만 분리해도 충분할 것 같아요.

2024-03-03 16:23 UTC, onschan commented on src/stories/Button.tsx
> +      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
마치 class 이름들이 스토리북용 컴포넌트 같네요..?

2024-03-03 16:23 UTC, onschan commented on src/hooks/useDefaultInput.ts
> +  }, [])
이 부분은 어떤 부분이 힘드셨던걸까요??

2024-03-03 16:23 UTC, onschan commented on src/stories/Button.tsx
> +};
직접 만드신게아니고 스토리북 샘플 코드일까요?? 로직상에서는 사용하는 부분도 있는 것으로 보였는데

2024-03-09 18:07 UTC, jjiyeon commented
승찬님 수정이 늦어져 죄송합니다!!!
코멘트 너무 감사해요👍
최대한 코멘트에 대한 수정 반영을 해보았습니다만, 부족한 지점이 있다면 추가 피드백 부탁드려요👍

먼저 제가 이해한 primitive ui는 순수 스타일이 없는 컴포넌트라고 이해를 했습니다.
지금 구현한 Input 컴포넌트에 중복인 wrapper div를 추가로 스타일을 잡아줬는데, 이렇게 스타일을 추가해도 될까 싶더라구요.
primitive ui의 영역이 어디까지인지 궁금합니다.
그리고 추가로 필요한 props가 늘어난다면..? input 컴포넌트에서 props를 추가로 받아도 될까?가 의문이였습니다.

stepper 추상화!!
stepper의 상태는 context를 사용하거나, 토스에서는 스토리지를 useRef로 사용하는 구조로 작성된걸로 이해했는데, 어떤 방식이 더 나은 방식인지 궁금합니다

2024-03-10 09:11 UTC, onschan requested changes
리뷰 사항을 반영해주셨군요 지연님! 감사드립니다 😊

### 리뷰 사항
현재 동작과 UI가 좀 깨지는 부분이 있어요.
개인적으로는 Step2 들어가시기 전에 수정 해주시면 좋을 것 같지만 시간상 힘드시다면 Step2를 진행해주시면서 수정해주셔도 좋아요! 제가 다시 확인할거니깐요 🧐

<img width="472" alt="스크린샷 2024-03-10 17 25 11" src="https://github.com/next-step/react-payments/assets/62434898/d3c543bc-ba0a-4f4b-8d1b-e400f94f44dc">

- [ ] 뒤로가기 버튼은 서비스 화면 안에 들어오게 해주세요!
- [ ] Input 사이의 구분자들의 정렬을 맞춰주세요!
- [ ] CVC는 마스킹된 값(*)이 아닌 실제 데이터로 저장해주세요.
- [ ] 카드 종류를 선택하는 모달도 뷰포인트 기준 가운데 정렬을 해주시면 더 자연스러울 것 같습니다!


### 질문 사항에 대한 답변
> 먼저 제가 이해한 primitive ui는 순수 스타일이 없는 컴포넌트라고 이해를 했습니다.
지금 구현한 Input 컴포넌트에 중복인 wrapper div를 추가로 스타일을 잡아줬는데, 이렇게 스타일을 추가해도 될까 싶더라구요.
primitive ui의 영역이 어디까지인지 궁금합니다.
그리고 추가로 필요한 props가 늘어난다면..? input 컴포넌트에서 props를 추가로 받아도 될까?가 의문이였습니다.
> 

잘 고민해주시고 답변해주셔서 감사합니다!

제가 생각하는 미션에서 Primitive UI 형태의 컴포넌트를 필수 요구 사항으로 정한 이유는 도메인 로직들을 위한 코드가 배제된 최대한 작은 역할을 하는 컴포넌트를 먼저 개발해보고 그를 활용해서 점진적으로 도메인을 구성하는 컴포넌트들로 확장해가는 경험을 해보시길 바래서라고 생각합니다.

Primitive UI라는 키워드에 매몰될 필요는 없다고 말씀을 드리고싶은데요. 이미 작은 단위의 컴포넌트를 만들어보셨고, 그에 대해 공통적으로 발생하는 로직들을 발견을 했다면 필요에 의해 공통화를 하는 작업은 자연스러운 일이라고 생각해요. 제가 제안드린 Label과 Conatiner에 대한 공통화는 그런 부분에 대한 말이었구요! 

컴포넌트는 결국 UI를 이루는 부품일뿐이고 이미 만들어진 부품이 다시 필요한 상황이 발생한다면 더 큰 조각으로 만드는 작업은 자연스럽게 발생할 수 밖에 없지않을까요? 😊

어떤 스타일 요구 사항에도 유연하게 대처하기 위해 스타일링이 배제되고 기본적인 기능 동작만하도록 하는 컴포넌트들을 만드는 패턴들은 조금 더 고려가 많이 되어야하긴합니다. 

`Headless Component` 라는 키워드로 조금 더 찾아보면 좋을 것 같아요 🧐

더 궁금한 점이 있으시다면 언제든 편하게 질문해주셔도 괜찮아요!!

> stepper 추상화!!
stepper의 상태는 context를 사용하거나, 토스에서는 스토리지를 useRef로 사용하는 구조로 작성된걸로 이해했는데, 어떤 방식이 더 나은 방식인지 궁금합니다
> 

레퍼런스도 검색해주시고 아주 좋습니다 👍

상태로 관리하는 방법 외에도 쿼리 파라미터 혹은 스토리지 혹은 별도의 저장소에 현재 step 단계를 저장하는 방법들이 있을거에요. 결국 `현재 단계에 대한 데이터를 저장한다 → 어디에 저장하냐?` 이 고민에서 파생되는 베리에이션들이기 때문에 해당 저장 방법이 어떤 특성들을 가지는지에 대해서 요구 사항과 비교를 해보면 될 거에요!

이런 패턴에 대해서 한가지 방법에만 매몰될 수 있어서 좀 더 넓은 시야에서 바라봐주시길 바라는 마음에 질문드린 부분이에요. 현재 개발 환경에서는 좋은 방법이 다른 개발 환경에서는 안좋은 방법일 수도 있어서 더 나은 방법이라는 부분은 항상 대답이 애매할 수 있어요 🥲

브라우저 새로 고침시에도 현재 Step을 유지해야한다라는 요구 사항이 있다면 다른 저장 방식과 비교해서 상태로 저장하는건 더 나은 방식일까요? 어떤 방법을 도입할때 가지는 트레이드 오프에 대해서 잘 생각하면 좋을 것 같아요.

2024-03-10 09:11 UTC, onschan commented on src/index.tsx
> +  const updateFunnelStep = useContext(UpdateFunnelStepContext)
현재 Stepper 컴포넌트의 역할이 chilren만 반환해줄 뿐 역할이 없는 컴포넌트로 보여요!
이 부분의 상태를 더 상위에서 관리하지않고 Stepper 컴포넌트에서 관리해도 되지 않을까요?

2024-03-10 09:11 UTC, onschan commented on src/utils/check.ts
> +  if (!number) return
number에 대한 기본값을 제공해주는 부분이 더 좋을 것 같아요.

옵셔널 타입 의미는 해당 함수에 number가 들어오지 않아도 기대 동작을 수행해야되는데,
아무런 역할을 수행하지 못하게 되는 상황이네요!

2024-03-10 09:11 UTC, onschan commented on src/components/CardBox/index.tsx
> +          }`}</p>
UI 로직에 삼항연산자와 로직들이 너무 많이 들어있어서 어떤 UI가 그려질지 예측하기 힘들어보여요!
각각 필요한 부분을 변수에 할당해서 사용하거나 특정 함수를 만들어서 사용할 수 있을 것 같아요!

2024-03-10 09:11 UTC, onschan commented on src/components/CardType/index.tsx
>                    closeModal
`closeModal()` !

2024-03-10 09:11 UTC, onschan commented on src/components/CardPassword/index.tsx
> +      value={cardInfo.password ? checkAllMasking(cardInfo.password, cardInfo.password.length)?.join() : ''} //
대부분의 value 뒤에 `//` 이 주석 처리가 붙어있는데 의도적인 부분이신가요???

2024-03-10 09:11 UTC, onschan commented on src/components/CardNumber/index.tsx
> +        onChange={(e) => updateCardInfo({ ...cardInfo, cardNumber: { ...cardInfo.cardNumber, fourth: e.target.value } })}
onChange handler를 공통화 시킬 방법이 있을것 같아요!

2024-03-10 11:53 UTC, jjiyeon commented on src/components/CardPassword/index.tsx
> +      value={cardInfo.password ? checkAllMasking(cardInfo.password, cardInfo.password.length)?.join() : ''} //
정렬을 위해 사용한 // 처리였습니다! 한줄로 보는게 가독성이 떨어져 보여서..작업하다 남은 습관이었어요.

2024-03-10 13:03 UTC, jjiyeon commented
승찬님 코멘트 고맙습니다😊
최대한 수정 반영하면서, 사용처에서 사용하는 스타일을 추가하여 적용하였습니다.
기능에만 신경을 썼는데, 다음 미션부터는 스타일도 신경쓰도록 해야겠어요.

> 어떤 스타일 요구 사항에도 유연하게 대처하기 위해 스타일링이 배제되고 기본적인 기능 동작만하도록 하는 컴포넌트들을 만드는 패턴들은 조금 더 고려가 많이 되어야하긴합니다.

적용을 잘 해보려고 합니다👍🎉🎉

2024-03-10 15:07 UTC, onschan approved these changes
주말동안 미션 진행해주시느라 고생많으셨어요!

수정해주신 부분에 대해서 추가 리뷰를 더 남기긴했는데
다음 미션으로 진행하시기엔 충분할 것 같아서 반영 여부는 다음 미션 진행에 선택해주세요!

다음 미션에서 뵙겠습니다 🤩

2024-03-10 15:07 UTC, onschan commented on src/components/CardBox/index.tsx
> +  }
1. 함수의 네이밍은 보통 동사로 시작하는 부분이 일반적이에요! 
```ts
const getCardNumberValue = () => {
    const cardNumber = cardInfo.cardNumber
    return {
      first: cardNumber?.first || '',
      second: cardNumber?.second || '',
      third: cardNumber?.third ? checkAllMasking(cardNumber.third, cardNumber.third.length) : '',
      fourth: cardNumber?.fourth ? checkAllMasking(cardNumber.fourth, cardNumber.fourth.length) : '',
    }
  }
```
2. 다만 이 부분은 한번의 함수 실행만으로도 충분히 구현이 가능할 것 같은데 즉시 실행 함수(IIFE)도 한번 이용해볼까요?

```ts
const cardNumberValue = (() => {
    const cardNumber = cardInfo.cardNumber
    return {
      first: cardNumber?.first || '',
      second: cardNumber?.second || '',
      third: cardNumber?.third ? checkAllMasking(cardNumber.third, cardNumber.third.length) : '',
      fourth: cardNumber?.fourth ? checkAllMasking(cardNumber.fourth, cardNumber.fourth.length) : '',
    }
  })()
  ```

이러면 반환값으로 변수에 바로 저장되기때문에 리렌더링시 한번의 함수 실행만 될 것 같아요!


3. 당장은 필요한 부분은 아니라고 생각하지만 이런 즉시 실행 함수의 반환값에 대한 최적화로 useMemo를 사용해볼 수도 있어요!
조금 더 말씀드리면 결국 메모이제이션도 메모리를 사용하고 더 많은 연산이 필요하기 때문에 해당 함수가 무겁다면 적용하는 방향으로 고려해보면 좋을 것 같아요. (prop값을 동일시하게끔 만들어서 리렌더링 최적화에도 활용할 수 있기도 하구요!)

2024-03-10 15:07 UTC, onschan commented on src/utils/check.ts
> +export const checkAllMasking = (text: string, number: number) => {
인자에 대한 옵셔널을 제거해주시는 방향으로 선택하셨군요!
현재의 개선 방향도 충분히 합리적이라고 생각합니다!

다만 제가 말씀드린 의도는
```ts
const DEFAULT_NUMBER = 4;

export const checkAllMasking = (text: string, number: number = DEFAULT_NUMBER) => {
  let maskingVal = ''
  const regx = new RegExp(`[0-9\*]{1,${number}}`, 'g')
  if (!text.match(regx)) return

  const masking = [text].map((value, _) => {
    return (maskingVal = value.replace(value, '*'.repeat(value.length)))
  })
  return masking
}
``` 
이런 방향이긴 했어요! 수정하실 필요는 전혀 없어요!

2024-03-10 15:07 UTC, onschan commented on src/components/CardNumber/index.tsx
> +  }
👍 key의 타입이 string대신 좀 더 좁은 타입이면 더 좋긴할 것 같은데 이대로도 충분한 것 같습니다!

2024-03-10 15:08 UTC, merged