[클린코드 리액트 3기 이범진] 페이먼츠 미션 Step1
next-step/react-payments pull request #120
Opened 2024-03-04 03:23 UTC by euan-lee

고민사항:

.디자인 먼저 컴포넌트화 하여서 시간이 오래걸린듯 한데  리뷰어님은 공통 ui를 먼저 작업하시는 편인가요?

.small card컴포넌트를 더 잘게 쪼겠지만 page5에서 공통 컴포넌트를 재활용하지 못하였는데 어떻게하면 좀더 재활용가능한 smalㅣ card 컴포넌트를 만들수 있을까요?

.모든 컴포넌트는 기능을 감추려고 노력하였고 단일 책임을 원칙으로 작성하려 노력하였습니다. 부족한점.. 혹은 아쉬운점있다면 피드백주시면 감사하겠습니다!!

2024-03-07 00:18 UTC, devhyun637 requested changes
안녕하세요 범진님! 
미션을 수행하느라 고생많으셨습니다 👏👏

질문에 대한 답변을 먼저 드리면, 
> .디자인 먼저 컴포넌트화 하여서 시간이 오래걸린듯 한데 리뷰어님은 공통 ui를 먼저 작업하시는 편인가요?

저는 회사에서 디자인시스템을 활용해서 직접 공통 UI를 작업하는 경우는 적긴해요. 하지만 만약 디자인시스템이 없다면 혹은 디자인 시안에서 누가봐도 공통적인 부분이 보인다면 작업시간을 오히려 덜기 위해서 공통 컴포넌트를 먼저 제작할 것 같아요. 어떤 부분이 디자인을 컴포넌트화하는데 오래 걸린 포인트였을지 궁금하네요! 컴포넌트를 만드는 건 오래걸리지만 여러 페이지에 적용을 한다면 오히려 먼 미래를 보았을 때 재활용을 할 수 있으니 시간을 절약하는 방법이 아닐까 생각합니다 :)

> .small card컴포넌트를 더 잘게 쪼겠지만 page5에서 공통 컴포넌트를 재활용하지 못하였는데 어떻게하면 좀더 재활용가능한 smalㅣ card 컴포넌트를 만들수 있을까요?

제가 이 질문에 대한 이해를 하지 못해서, 코드 상에 구체적인 질문을 남겨주실 수 있으실까요? 
추가적으로 범진님의 코드를 보면서 컴포넌트들이 너무 작게 나눠진 것 같아서 오히려 이런 부분이 재활용이 어렵고 유연하지 못한게 아닐까? 라는 생각을 했어요. 그래서 저는 범진님이 생각하는 '컴포넌트'는 어떤 것인지도 궁금하고, 어떤 기준으로 컴포넌트를 나누려했는지도 궁금합니다. 

일단은 빠르게 코드만 보면서 소소한 코드리뷰를 남겼는데, 이후 한번 더 로컬에서 시행해보면서 기능적인 측면에서 리뷰를 드리려고 해요. 그동안 제 질문에 대한 답변도 주시면 좋을 것 같습니다 :)

2024-03-07 00:18 UTC, devhyun637 commented on README.md
작업하면서 README가 덮여씌여진 것 같은데, 이 부분은 범진님의 프로젝트에 맞게 수정해주세요 🙇‍♀️

2024-03-07 00:18 UTC, devhyun637 commented on src/main.tsx
> +  </RegisteredCardsProvider>
`StrictMode`가 `Provicder`들 안에 있는 이유는 무엇일까요?

2024-03-07 00:18 UTC, devhyun637 commented on src/Components/Layout/Flex.tsx
> +      <div className="flex-center">{children}</div>
`flex-center`만 가능한 `Flex` 컴포넌트는 유연함이 부족해보이는데 왜 `flex-center` 스타일만 가능하도록 만들었는지 알 수 있을까요?

2024-03-07 00:18 UTC, devhyun637 commented on src/Components/Layout/Layout45.tsx
> +const Layout45 = ({ children }: { children: ReactNode }) => {
45는 어떠한 의미일까요~?

2024-03-07 00:18 UTC, devhyun637 commented on src/Components/Button/NextButton.tsx
> +    </div>
`Button` 컴포넌트임에도 불구하고 `div`로 만들어져있는 이유는 무엇일까요? 좀 더 시멘틱한 태그를 사용하면 좋을 것 같아요!

2024-03-07 00:18 UTC, devhyun637 commented on src/Components/Cards/Body/Bottom/CardBottom.tsx
> +};
이정도면 컴포넌트로 따로 안빼도 될 것 같은데, 범진님이 생각하시는 컴포넌트의 기준은 어떤 것일까요?

2024-03-07 00:18 UTC, devhyun637 commented on src/Hooks/UseInput.tsx
이 파일만 대문자로 시작하네요!

2024-03-07 00:18 UTC, devhyun637 commented on src/Context/CardProvider.tsx
> +  });
console.log가 있어요!

2024-03-07 00:18 UTC, devhyun637 commented on src/Components/Cards/Card/BigCreditCard.tsx
> +const BigCreditCard = () => {
이런 부분은 prettier를 활용해봐도 좋을 것 같네요:)

```suggestion
import CardBody from "../Body/CardBody";

const BigCreditCard = () => {
```

2024-03-07 00:18 UTC, devhyun637 commented on src/Pages/Page2.tsx
> +        <H2Text className="page-title">2️⃣ 카드 추가</H2Text>
한 페이지에 h2 컴포넌트가 2개 있는데, 두개가 동일한 위상을 가지는 것이 맞을까요?

2024-03-07 00:18 UTC, devhyun637 commented on src/Pages/Page3.tsx
> +        <h2 className="page-title"> 카드 추가</h2>
여기서의 h2 컴포넌트는 `<H2Text>`를 활용하지 않았군요. 특별한 이유가 있을까요?

2024-03-07 00:18 UTC, devhyun637 commented on src/type/CardInfoType.ts
모두 null이 허용이 가능하다면, 제네릭을 활용하여 유틸 타입을 선언해서 사용하는건 어떨까요?

2024-03-10 08:20 UTC, euan-lee commented on README.md
넵 바로 수정하겠습니다!

2024-03-10 08:20 UTC, euan-lee commented on src/main.tsx
> +  </RegisteredCardsProvider>
삭제 하겠습니다

2024-03-10 08:21 UTC, euan-lee commented on src/Components/Layout/Flex.tsx
> +      <div className="flex-center">{children}</div>
아 이 부분도 클레스 이름을 prop으로 받으면 좋아보일듯 하네요 감사합니다!

2024-03-10 08:21 UTC, euan-lee commented on src/Components/Button/NextButton.tsx
> +    </div>
button이 좋아보이네요 감사합니다!

2024-03-10 08:21 UTC, euan-lee commented on src/Context/CardProvider.tsx
> +  });
넵 감사합니다!

2024-03-10 08:22 UTC, euan-lee commented on src/Pages/Page3.tsx
> +        <h2 className="page-title"> 카드 추가</h2>
파일이 너무 많아져서 누락했나봅니다. 감사합니다

2024-03-10 09:15 UTC, euan-lee commented on src/type/CardInfoType.ts
아! 제네릭 쓸걸 생각을 못했네요!! 감사합니다

2024-03-24 06:47 UTC, devhyun637 commented on README.md
제목이 있었다면 더 좋았을 것 같아요! :)
보통의 README에는 '이 프로젝트를 시행하는 방법', '프로젝트에 대한 간략한 소개', '사용한 기술' 등이 들어가는데 
나중에 포트폴리오처럼 쓰일수도 있으니 다른 프로젝트를 할때에는 다른 깃헙들을 참고하면서 작성해주시면 좋을 것 같아요 :)

https://github.com/microsoft/TypeScript
https://github.com/facebook/react

2024-03-24 06:47 UTC, devhyun637 commented on src/main.tsx
> +  </RegisteredCardsProvider>
앗 삭제를 의미한건 아니었고, 왜 가장 안쪽에 감싸져있는지 궁금해서 남긴 리뷰입니다!

2024-03-24 07:03 UTC, devhyun637 commented on src/Components/Layout/Flex.tsx
> +      <div className="flex-center">{children}</div>
className의 타입이 더 구체적이면 좋을 것 같아요! 
그리고 수정된 코드에서도 아직 이 컴포넌트가 Flex로 의미가 명확하지 않은 것 같아서 다른 디자인컴포넌트들을 참고해보면 좋을 것 같습니다 :)

e.g) https://chakra-ui.com/docs/components/flex

2024-03-24 07:07 UTC, devhyun637 commented on src/Components/Button/NextButton.tsx
> +    </div>
수정된 내용이 다음과 같이 되어있는데, button이 span을 감싸는 형태여도 좋을 것 같아요:)
또한, button 태그의 기본 속성들에 대해서도 한번 보고, [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type) 등 필요한 속성은 작성하는 것이 좋습니다

```tsx
<div className={`button-box ${className}`} onClick={handleNext}>
  <button className="button-text">다음</button>
</div>
```

2024-03-24 07:08 UTC, devhyun637 commented on src/Context/CardProvider.tsx
> +  });
페이지4에 아직 console.log가 남아있는 것 같아요~

2024-03-24 07:21 UTC, devhyun637 approved these changes
안녕하세요 범진님! 리뷰가 늦어져서 죄송합니다.
반영하신 내용들 위주로 살펴보았고, 적용이 된 부분에 대해서 제 의견 혹은 질문 남겨두었습니다 :)

로컬에서 시행해보려고 하는데 현재 프로젝트 'src/Components/Cards/Card/SmallCreditCard.tsx 파일에서 오류가 있는 것 같아요 확인해주시면 좋을 것 같습니다. 또 리뷰를 반영한 부분과 반영하지 않은 부분이 있다면 리뷰에 이모지나 코멘트로 남겨주시면 제가 좀 더 그 부분을 확인하는데 좋을 것 같아요:)

저는 평소에 리액트 컴포넌트, 훅, 폼 라이브러리 등을 보면서 많이 참고하는 편인데, 범진님도 이번에 컴포넌트를 작게 쪼개면서 고민이 많았던 것 같아서 시간이 될 때 참고하는걸 추천드립니다 :)

좋은 예시들이 많겠지만, 
https://chakra-ui.com/
https://mui.com/
https://usehooks.com/

미션하느라 고생많으셨습니다! 
남은 기간이 별로 남지않았지만 마무리 잘하셔서 유종의 미를 거두시길 바랍니다~ 💪

2024-03-24 07:21 UTC, merged