[클린코드 리액트 3기 장동현] 페이먼츠 미션 Step1
next-step/react-payments pull request #124
Opened 2024-03-04 17:19 UTC by ww8007

안녕하세요 리뷰어님!
늦게 PR을 올려서 죄송합니다 😂 최근 회사에 입사해서 적응 기간을 거치느라 PR 올리는 시간이 늦어지게 되었네요...
늦었지만 잘 부탁 드리겠습니다!

## 고민 사항

### 1. card의 validation 체크 

카드의 각 상태마다
`카드 번호 : 4자리씩 입력`
`만료일 : MM / YY`
`CVC : 3자리 숫자`
와 같은 `validation` 체크 로직이 필요한 상황인데 모든 체크를 `onChangeCardInput`
에서 처리할까 아니면 `AddCard` 컴포넌트 내부에서 추가 변환이 필요한 상태를 관리하고 `onChangeCardInput`에서는 변환된 상태만을 업데이트를 하는게 좋을지 고민이 됩니다.

현재 구현 방식은 `AddCard` 컴포넌트 내부에서 상태를 관리하고 `onChangeCardInput`에서 변환된 상태만을 업데이트 하는 방식으로 구현을 했습니다.
이렇게 구현한 이유는 `validation`의 수정이나 오류가 발생했을 때 `AddCard` 컴포넌트 내부에서만 수정을 하면 되기 때문에 관리가 편리하다고 생각했습니다.
하지만 한 편으로는 동일한 데이터를 관리하는 불필요한 상태를 두는게 아닌가 하는 생각이 들기도 합니다.

혹시 이런 상황이라면 이는 합리적인 선택인지 아니면 불필요한 상태를 두는 것인지 리뷰어님의 생각이 궁금합니다.

### 2. 비지니스 로직의 CustomHook 추상화

현재 `AddCard` 컴포넌트의 경우 뿐만 아닌 모든 컴포넌트들에 대해 UI 로직과 비즈니스 로직이 섞여있는 상태입니다. 따로 분리를 진행하지 않은 이유는 `customHook`을 통해 관리를 한다 하더라도 단순하게 코드의 위치만 옮겨놓는 것이라 생각이 들어 분리를 하지 않았습니다.
코드를 유지보수 하는 다른 개발자 입장에서 바라볼 때는 `validation`이 어떻게 진행 되는지에 대한 정보가 중요한 정보라는 생각이 들어 `customHook` 내부로 숨겨놓는 것이 성급한 추상화로 보일 수 있을 것 같은데 이런 상황이라면 어떻게 하는게 좋을까요?
그리고 `customHook`으로 비지니스 로직을 분리할 때 리뷰어님은 어떤 기준으로 분리를 진행하시는지 궁금합니다.

### 3. 스토리북의 활용

이번에 스토리북을 이용해 보면서 객체 형태의 데이터를 다루는 것은 비개발자에게는 이해하기 어려울 수 있을 것 같다는 생각이 들었습니다.
검색을 좀 해보니 라이브러리를 설치 하거나 nested된 객체를 풀어주면서 기존 Storybook의 기능을 확장하는 방법이 있었는데 객체 형태의 데이터는 어떻게 다루는 것이 좋을지 궁금합니다.

<img width=400 src="https://github.com/ww8007/react-payments/assets/54137044/5cb80117-5c44-404a-97b7-2e689a2bfbc3" />

특히 합성 컴포넌트의 경우 많은 props를 가지게 되는데 이 모든 데이터를 핸들링 할 수 있게 사용자에게 권한을 주는 것이 좋을지 아니면 이는 UI만 보여주는 것이 좋을지 궁금합니다.
현재는 아래와 같이 `useArgs`와 `args`를 이용해서 사용자에게 권한을 주고 있습니다.

<img width=400 src="https://github.com/ww8007/react-payments/assets/54137044/339c6640-7a3f-486b-9e85-130dbd361494" />

2024-03-06 16:53 UTC, GwangYeol-Im requested changes
안녕하세요 동현님~ 파일 diff를 보면서 꽤 고생 많이 했겠다는 생각이 드네요. 세부 코멘트 확인 부탁드리고 질문에 대한 답변 남기고 마무리 짓도록 할게요!

> card의 validation 체크

현재의 질문에서는 어떤 부분이 고민인 건지 잘 그려지지 않아 생각하시는 각각의 케이스를 A, B로 나눈다면 A와 B에 해당하는 짧은 예시를 의사 코드로 작성해주시면 답변 드릴 수 있을 것 같습니다.

> 비지니스 로직의 CustomHook 추상화

개인적으로 로직을 별도의 hook으로 분리할 때는 크게 두가지 상황을 고려해보는 것 같습니다.

1. 해당 로직이 다른 곳에서 재사용 될 수 있을 것 같을 때
2. 현재 컴포넌트와 직접적으로 연관된 관심사가 아닐 때

저 또한 단순히 로직과 view를 분리하기 위해 커스텀 훅을 작성하는 경우는 잘 없는 듯 하네요!

> 스토리북의 활용

스토리북을 같이 보며 협업할 대상이 누군지, 팀 내 컨벤션 등 여러 상황에 따라 달라질 수 있는 부분이라고 생각합니다. 따라서 어떤 방식도 그 반대 방향에 비해 더 낫다고 쉽게 말씀 드리기 어렵다고 느껴지네요. 스토리북을 사용하는 팀의 아티클 등을 검색해서 실제 사용례를 찾아보시면 어떨까 싶습니다.

2024-03-06 16:53 UTC, igy95 commented on .gitignore
> +.vscode/*
이거는 왜 `.gitignore`에 포함되었는지 알 수 있을까요?

2024-03-06 16:53 UTC, igy95 commented on src/App.tsx
indet를 꽤 깊게 들여쓰시는 군요 😅 리뷰할 부분은 아닌 듯 하지만, 서로 간의 가독성 측면에서 들여쓰기는 `space: 2`는 어떨까 싶긴 하네요!

2024-03-06 16:53 UTC, igy95 commented on src/common/utils/style.ts
> +export const textAlignVariable = ["left", "center", "right"] as const;
widthVariable, textAlignVariable에 해당하는 value에 시맨틱한 이름을 부여하기 위해 배열보다는 객체 형식으로 관리하는 게 어떨까요? 예를 들면 다음과 같이 선언할 수 있을 것 같아요 (키 값이 정확한 의미를 가지지 않는 듯 하지만 예시 차원으로만 봐주세요)

```ts
const widthVariable = {
  XL: 100,
  L: 75,
  M: 50,
  S: 25,
  XS: 15,
} as const
```

2024-03-06 16:53 UTC, igy95 commented on src/main.tsx
> +		<IconLoader />
`IconLoader`의 역할이 무엇인지는 잘 모르겠지만, 막상 코드만 보면 쓰임새와 이름이 잘 매칭되지 않는 것 같아요!

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/utils/update.ts
> +export const updateNestedState = <T extends Record<string, any>>(
1. `lastKey`가 있을 경우 인자로 들어온 객체에 직접 변형을 가하는데, 불변성을 지켜주지 않으면 새로운 상태로 변형되는 위치를 추적하기 힘들고 `setState` 시에도 문제가 발생할 수 있지 않을까요?
2. `path`가 정확하게 입력되지 않을 경우에 명시적으로 에러를 반환하는 게 아니라 이전 상태를 반환하는데 개발자가 path를 잘못 넣어도 런타임에서 테스트 하기 전까지 문제를 알 길이 없지 않을까 싶습니다.

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/utils/object.ts
> +export const maskObjectValuesAfterIndex = (
객체의 값이 아닌 문자열을 마스킹 처리해주는 util을 만들고 사용처에서 객체의 값을 문자열로 변환하여 해당 유틸 함수를 호출하는 것이 재사용성을 높일 수 있지 않을까요?

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/ui/FlexibleInput/FlexibleInput.tsx
> +	children: ReactNode;
`PropsWithChildren` 유틸 타입을 사용해볼 수 있을 것 같습니다.

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/ui/FlexibleInput/FlexibleInput.tsx
> +	width?: Width;
`Width`라는 타입이 모든 컴포넌트에 범용적으로 사용될 수 있진 않아보여 사용처를 한정하여 타입 이름을 부여하는 게 어떨까 싶네요

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/hooks/funnel/models.ts
이 파일의 이름이 왜 `models`인지 알 수 있을까요?

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/hooks/funnel/models.ts
> +const isNonEmptyArray = <T>(array: readonly T[]): array is NonEmptyArray<T> => {
boolean 변수나 boolean을 반환하든 함수의 이름은 되도록 긍정형으로 짓는 것을 권장드립니다. 부정형으로 지어진 이름을 다시 한번 부정하게 되면 이중 부정이 되어 가독성을 더 떨어트리기 때문입니다.

```ts
!isValid // 유효하지 않은
!isNotValid // 유효하지 않지 않은
```

이와 별개로 이 유틸은 단순히 배열의 길이가 0 초과인지를 봐주는 거 같은데 따로 함수 선언까지 필요할까 의문이 들긴 하네요!

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/Card/ui/Card/provider/useCardContext.ts
> +const useCardContext = () => {
`useContext`로부터 받아온 value의 타입을 좁히기 위한 이 훅도 공통화를 할 수 있지 않을까요?

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/Card/ui/Card/core/Number.tsx
폴더 범위에 기대어 보더라도 `Number`라는 이름은 꽤 포괄적인 것 같은데, 이름을 좀 더 구체화시켜주면 좋을 듯 합니다.

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/Card/ui/Card/Card.tsx
> +	const expirationDateComponent = findComponentFromChildren(
이렇게 해주는 거보다는 `Card` 자체에서 각 요소에 대한 props를 받게 해주는 것이 낫지 않을까요? 그렇게 생각한 이유로는 다음과 같습니다.

1. 매번 받는 쪽에서 `findComponentFromChildren`을 호출해줘야 함
2. 사용처에서 선언할 `children`의 순서와 내부에서 그리는 순서가 다를 수 있어 사용 경험에 대한 명시성이 떨어짐

하위 컴포넌트를 외부로 노출한다는 것은, 어찌보면 사용자로 하여금 레이아웃의 자유도를 열어준다는 의미로 볼 수 있을 듯 한데 현재의 구조에서는 그렇지 않으니 조금 모순된다는 느낌이 드네요.

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/Card/constants/card.ts
> +export const TEMP_CARD_LENGTH = 2;
임시 값에 대한 상수가 PR에 올라와야 하는 이유가 있을까요?

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/ui/FlexibleInput/core/InputBox.tsx
> +	}
이렇게 던진 에러는 어디서 핸들링 해주나요?

2024-03-06 16:53 UTC, GwangYeol-Im commented on src/common/hooks/useUniqueId.tsx
> +export const useUniqueId = () => {
리렌더링 시에도 id를 보존하기 위해 `useRef`를 사용해주신 듯 한데, id를 반환하는 동작이 분리되어야 하지 않을까 싶습니다. 대개 id를 사용하는 경우가 list item 내에 key로 사용해주는 걸 감안해보았을 때 이 훅은 key를 선언한 때 사용하기 힘들 것 같아요.

2024-03-07 14:11 UTC, ww8007 commented on .gitignore
> +.vscode/*
vite 기본 템플릿 설정에 포함이 되어있어서 그대로 올린거 같네요 😅
혹시 문제가 되는 부분이 있을까요?

2024-03-07 14:13 UTC, ww8007 commented on src/App.tsx
앗 이게 기본 설정은 `space: 2`로 설정이 되어 있었는데 Github setting의 `tabWidth`가 12로 설정이 되어있었네요 😂
현재는 2로 수정했습니다!

2024-03-07 14:16 UTC, ww8007 commented on src/common/utils/style.ts
> +export const textAlignVariable = ["left", "center", "right"] as const;
앗 이부분에 대해서는 XL이 100의 크기를 가진다는 사실을 
`ts-doc`이나 파일 내부까지 들어가서 확인을 해야 되는 부분이 종종 생겨서
다음과 같이 구현을 하였습니다! width라는 값에 대해서는 숫자 값이 들어가는 것이 좀 더 명시적이라고 생각을 했는데
이 부분에 대해서는 어떻게 생각 하시나요?

2024-03-07 14:24 UTC, ww8007 commented on src/main.tsx
> +		<IconLoader />
앗 생각해보니 내부는 svg의 모음인데 무언가 로드한다는 의미로 해석될 수 있겠네요
`IconSprites`로 변경해 보도록 하겠습니다!

2024-03-07 14:57 UTC, ww8007 commented on src/common/utils/update.ts
> +export const updateNestedState = <T extends Record<string, any>>(
다시보니 너무 특정 상황에 대한 고려만 진행하고 코드를 작성했네요 😂
말씀 해주신대로 불변성에 대한 부분과 명시적으로 에러를 보여줄 수 있도록 수정해 보겠습니다!

2024-03-07 14:57 UTC, ww8007 commented on src/common/utils/update.ts
> +export const updateNestedState = <T extends Record<string, any>>(
- https://github.com/next-step/react-payments/pull/124/commits/86a9c50f989892b4e831cdc0efc7317fe08895fe

2024-03-07 15:01 UTC, ww8007 commented on src/common/ui/FlexibleInput/FlexibleInput.tsx
> +	children: ReactNode;
혹시 제가 알기로 PropsWithChildren의 경우 구현체가

```ts
type PropsWithChildren<P = unknown> = P & { children?: ReactNode | undefined };
```
와 같이 되어 있어서 children 값이 없더라도 오류가 나지 않는거로 알고 있는데
따로 유틸 타입을 만들어서 사용하는게 좋을까요?

2024-03-07 16:05 UTC, ww8007 commented on src/common/utils/object.ts
> +export const maskObjectValuesAfterIndex = (
네 재사용성 있게 사용할 수 있도록
객체를 문자열로 변환하는 유틸 함수 - https://github.com/next-step/react-payments/pull/124/commits/95512b3e62d5476d6f09c0d8068ec1f1d26dbb0e
문자열 기반으로 마스킹 하는 유틸 함수 - https://github.com/next-step/react-payments/pull/124/commits/916056867e878c967db54fd9f09aed2d86e65edd
로 수정 하였습니다!

2024-03-07 16:13 UTC, ww8007 commented on src/Card/ui/Card/core/Number.tsx
네! CardNumber로 수정했습니다 - https://github.com/next-step/react-payments/pull/124/commits/b3570e4d9c3ebc7a8910c458ef9377912a602c00

2024-03-07 16:18 UTC, ww8007 commented on src/common/ui/FlexibleInput/core/InputBox.tsx
> +	}
따로 핸들링 해주지 않고 최상위 까지 전파 되도록 하였습니다.
이렇게 진행한 이유는 개발 단계에서 컴포넌트의 목적성에 맞게 사용됨을 보장하고 싶기 때문에
개발단계에서 목적에 맞도록 사용하여 바로 오류를 확인하게 하고 싶었습니다.

2024-03-07 16:41 UTC, ww8007 commented on src/common/ui/FlexibleInput/FlexibleInput.tsx
> +	width?: Width;
현재 검색시 Input 에서만 사용되고 있어서 InputWidth로 변경 진행해 보겠습니다! - https://github.com/next-step/react-payments/pull/124/commits/8c4cdaaf7e55fd658c415cfdfc5d50a96f1e39ce

2024-03-09 07:18 UTC, ww8007 commented on src/common/hooks/funnel/models.ts
데이터를 나타내는 인터페이스의 모음을 나타내기 위해서 `models` 라는 네이밍을 사용하였습니다.
funnel 내붸서 type 들의 기반이 `비어있지 않은 Array`로 부터 시작이 되기 때문에(ValidArray)

다음의 타입을 가지고 있습니다!
```ts
export type ValidArray<T> = readonly [T, ...T[]];
```

다만 이전에 models 내부에 포함 되어있던
`extractNonEmptyArrayKeys`의 경우 유틸 함수 쪽에 좀 더 어울리는거 같아 `utils` 폴더로 이동하였습니다.
https://github.com/next-step/react-payments/pull/124/commits/fdb37b995b4f3fbaab19d56784ecbd0908ea932e

2024-03-09 07:21 UTC, ww8007 commented on src/common/hooks/funnel/models.ts
> +const isNonEmptyArray = <T>(array: readonly T[]): array is NonEmptyArray<T> => {
네 부정형을 담게 되면 두 번 생각해야 의미를 파악할 수 있을거 같아서
`ValidArray` 라는 네이밍으로 수정하고
내부에서 길이를 판단하는 것도 유틸 함수에서 `length === 0` 으로 체크 하도록 하였습니다.
https://github.com/next-step/react-payments/pull/124/commits/8e2cb42f4f9431e3e54109d6a76ccabe57bf6fbb

2024-03-09 13:05 UTC, ww8007 commented on src/Card/ui/Card/provider/useCardContext.ts
> +const useCardContext = () => {
네 공통화 하는 편이 좋을거 같아서
customHook을 통해 공통화 진행 하였습니다!
https://github.com/next-step/react-payments/pull/124/commits/db4c4af593ce304c0f127830b36979f951b8ad9d

2024-03-09 13:26 UTC, ww8007 commented on src/Card/constants/card.ts
> +export const TEMP_CARD_LENGTH = 2;
기본 UI에서 기본적인 카드가 존재하는 경우로 가정하고
`MSW`나 `Mock API`를 사용하지 않는다는 가정하에 임시 데이터를 두려고 했었는데
현재의 구조는 추후에 실제 API 연동시 TEMP에 대한 정보가 파편화 되어있어

1. `동적 id` 기반으로 새로운 카드 생성 - https://github.com/next-step/react-payments/pull/124/commits/86bc85c6009af3a89db21a2d9057d97d92c779f5
2. `constants` 파일에서 임시 정보 제거 - https://github.com/next-step/react-payments/pull/124/commits/ff1dfa41e2f23cb5d0a5b41e4efdf5e60c00ca97

하도록 수정 했습니다!

2024-03-09 15:31 UTC, ww8007 commented on src/Card/ui/Card/Card.tsx
> +	const expirationDateComponent = findComponentFromChildren(
일단 말씀해주신대로 합성 컴포넌트를 사용한거에 비해 UI 자유도가 떨어진거 같아서
`Top`, `Middle`, `Bottom` 정보를 추가하여서 자유도를 열어 주도록 하였습니다.

현재 `Card` 컴포넌트의 경우
1. props를 바깥으로 꺼내서 필수 정보를 나타낼 수 있다는 점
2. 페이지 마다 달라질 수 있는 Card UI에 대한 자율성을 가져갈 수 있다는 점에서

현재 구조를 유지하고 만약 Card를 이렇게 작성하는게 누군가가 피곤하다고 느껴진다면
`PropsBaseCardComponent`를 따로 만들어서 props로 내려보낼 수 있는 컴포넌트를 추가해 보도록 하겠습니다!

일단 말씀해주신대로 합성 컴포넌트를 사용한거에 비해 UI 자유도가 떨어진거 같아서
`Top`, `Middle`, `Bottom` 정보를 추가하여서 자유도를 열어 주도록 하였습니다.

현재 `Card` 컴포넌트의 경우
1. props를 바깥으로 꺼내서 필수 정보를 나타낼 수 있다는 점
2. 페이지 마다 달라질 수 있는 Card UI에 대한 자율성을 가져갈 수 있다는 점에서

현재 구조를 유지하고 만약 Card를 이렇게 작성하는게 누군가가 피곤하다고 느껴진다면
`PropsBaseCardComponent`를 따로 만들어서 props로 내려보낼 수 있는 컴포넌트를 추가해 보도록 하겠습니다!

https://github.com/next-step/react-payments/pull/124/commits/06462ad4490f82fd3c099f57382abb7c6424d91e

2024-03-09 16:09 UTC, ww8007 commented on src/common/hooks/useUniqueId.tsx
> +export const useUniqueId = () => {
네 key가 중복될 수 있는 점을 고려하여서 context 방식의 구현으로 변경해 보았습니다!
https://github.com/next-step/react-payments/pull/124/commits/47f73af6c3db56c39607190e56ac2985737598f4

2024-03-09 16:27 UTC, ww8007 commented
리뷰 상세하게 남겨주셔서 정말 감사드립니다! 😃

1번 질문의 대한 현재 코드를 바탕으로 예시를 들어드리도록 하겠습니다.

### A 상황

- Funnel 컴포넌트 내부에서 모든 validation에 대한 처리를 담당

[CardFunnel.tsx]
```tsx
const [newCard, setNewCard] = useState<CardInfo>(
  makeNewCard(cardList.length)
);

const onChangeCardInput = (e: ChangeEvent<HTMLInputElement>) => {
  const { name, value } = e.target;

  // 카드 번호 입력 validation

  // 카드 만료일 입력 validation

  // 카드 소유자 이름 입력 validation

  setNewCard((prev) => updateNestedState(prev, name, value));
};
```

### B 상황

- Funnel 컴포넌트 내부에서 기본적인 input update만 반영하고
`validation`이 필요한 상태의 경우 AddCard 컴포넌트 내부에서 상태를 따로 두고 관리
- 상태를 페이지 전환 전 업데이트

[CardFunnel.tsx]
```tsx
const [newCard, setNewCard] = useState<CardInfo>(
  makeNewCard(cardList.length)
);

const onChangeCardInput = (e: ChangeEvent<HTMLInputElement>) => {
  const { name, value } = e.target;
  setNewCard((prev) => updateNestedState(prev, name, value));
};
```

[AddCard.tsx]
```tsx
const [expirationDate, onChangeExpirationDate, onKeyDownExpirationDate] =
  useInputState(
    "",
    formatExpiryDate,
    removeTrailingCharacterOnKeyDown("Backspace", "/")
  );
const [securityCode, onChangeSecurityCode] = useInputState("", onlyNumber);

const onClickNext = () => {
  setCard((prev) => ({
    ...prev,
    expirationDate: { month, year },
    securityCode
  }));
  onNext();
};
```

2024-03-10 09:04 UTC, GwangYeol-Im commented on .gitignore
> +.vscode/*
문제가 되기보다는, 협업할 수 있는 환경을 고려하여 프로젝트 내의 세팅은 되도록 github에 올려두고 일관성을 유지하는 게 좋아보여 질문드렸습니다~

2024-03-10 09:19 UTC, GwangYeol-Im commented on src/common/utils/style.ts
> +export const textAlignVariable = ["left", "center", "right"] as const;
어떠한 데이터에 접근할 때, 인덱스와 키로 접근하는 방식 중 어느 방향이 더 명시적일지 고려해보면 저는 후자가 아닐까 생각합니다.

```ts
// array
widthVariable[0]

// object
widthVariable.XL
```

구조 분해 할당을 사용한다면, 배열도 어차피 변수에 할당하여 사용해야 하기 때문에 말씀 주신 부분이 크게 차이나진 않을 것 같아요.

```ts
// array
const [a] = widthVariable

console.log(a) // 100
```

오히려 배열은 구조 분해 할당을 시도할 때도 어떤 순서에 어떤 값이 있는지 확인해가며 꺼내써야 하기 때문에 객체보다 불편할 거라고 생각합니다.

```
// array
const [, , , a] = widthVariable

console.log(a) // 25

// object
const { XL, S } = widthVariable
```

2024-03-10 09:36 UTC, GwangYeol-Im commented on src/common/ui/FlexibleInput/FlexibleInput.tsx
> +	children: ReactNode;
아하 `children`을 required하게 받는 것이 의도였군요~ 그렇다면 현재와 같은 방식을 사용해도 괜찮을 듯 합니다! 다만 `ReactNode` 타입이 `undefined`를 내포하고 있기 때문에 이거까지 잡아주려면 따로 유틸 타입을 만들어 사용해볼 수도 있을 것 같아요~

2024-03-10 09:39 UTC, GwangYeol-Im commented on src/common/ui/FlexibleInput/core/InputBox.tsx
> +	}
아하 넵넵, 이 부분은 에러 핸들링에 대한 이해를 하고 계시고 해당 미션의 요구사항은 아니라서 스킵한 걸로 이해하겠습니다~

2024-03-10 09:47 UTC, ww8007 commented on .gitignore
> +.vscode/*
아하 현재는 따로 `.vscode` 폴더 자체에 다른 세팅이 설정된게 없어서 
추후에 다른 설정이 생긴다면 제거해 두도록 하겠습니다!

2024-03-10 09:49 UTC, GwangYeol-Im approved these changes
> 1번 질문의 대한 현재 코드를 바탕으로 예시를 들어드리도록 하겠습니다.

저는 두 방식 모두 합리적인 코드 작성 방식이라는 생각이 들고 단지 폼 작성 UX를 어떻게 처리하느냐에 따라 달라지는 부분이라고 느껴지네요! 입력한 시점마다 바로 폼 데이터에 반영을 시킬지, 모든 값이 유효하다고 판단되는 경우에 일괄적으로 폼 데이터에 반영을 시킬지에 대한 차이라 취사 선택하면 될 것 같습니다.

다만 A 상황 같은 경우 `onChangeCardInput`에 모든 유효성 검사를 넣기보다는, 각 인풋 핸들링 목적으로 wrapping한 메서드에 input에 맞는 유효성 검사를 실행해주는 게 좋을 듯 합니다.

```ts
const onChangeCardNumber = () => {
  // 여기서는 카드 번호 입력 validation만 수행

  onChangeCardInput()
}
```

2024-03-10 09:50 UTC, merged