[클린코드 리액트 3기 이진호] 페이먼츠 미션 Step2
next-step/react-payments pull request #130
Opened 2024-03-08 04:56 UTC by Gn0lee

안녕하세요 원석님! Step2 리뷰 요청 드립니다.

## 고민했던 점

### 상태 전역으로 관리

step1 pr에서 context api를 사용하여 전역으로 관리하는 것을 제안해 주셨습니다. 그래서 xstate를 적용하며 context api를 적용하였고 코드 가독성이 많이 개선되었다 생각합니다.😄 그런데 스토리북이나 테스트 코드 작성할때는 생각보다 어려운 점이 많았습니다. 예를 들면 카드 번호 입력 input을 테스트 하기 위해서는 form step으로 미리 이동을 시켜주거나 항상 Provider Wrapper가 필요했습니다. 내부 기능을 하는 코드의 가독성은 개선되었는데 스토리북과 테스트 코드는 오히려 복잡해진것 같아 미션을 잘 진행하고 있는 것인지 고민이 들었습니다. 전역상태를 사용하는 컴포넌트를 테스트하거나 스토리북을 적용할때의 노하우가 있으실지 궁금합니다.

### 테스트 방식

step1에서는 유저 이벤트를 기반으로 테스트 코드를 작성하였습니다. 앱은 유저 이벤트를 바탕으로 동작하여 유저 이벤트 바탕으로 테스트 하는 것이 더 적절하다고 생각했기 때문입니다. 하지만 step2 에서 xstate를 전역으로 관리하면서 특정 테스트에서 유저 이벤트를 사용하여 테스트하기가 어려워 졌습니다. 상태를 hook으로 조회하다보니 renderHook을 사용하는데 컴포넌트에서 유저이벤트가 발생해도 act 함수를 실행시킬 수가 없기 때문이었습니다. 그래서 이후 테스트는 state machine을 테스트하였습니다. 원석님께서는 state machine을 테스트하는 것으로 충분하다 생각하시는지 아니면 유저 이벤트나 E2E테스트등의 실제 동작을 테스트가 꼭 필요하다 생각하시는지 궁금합니다.

xstate를 처음 사용해보는데 정말 신선하고 재미있는 경험이었습니다.ㅎㅎ 그럼 이번 PR도 잘 부탁드립니다!

2024-03-09 18:16 UTC, wonsss requested changes
진호님 안녕하세요. XState를 사용하여 페이먼츠 미션 step2도 아주 잘 해주셨네요 👍 
이전보다 코드가 훨씬 가독성이 좋아지고 깔끔해진 것 같아요!
스토리북과 테스트코드도 잘 변경하여 적용해주셔서 코드 이해하는 데 도움이 되었습니다.
리뷰 남겨드렸으며, 질문 2가지에 대해서도 코멘트 내에 제 의견을 남겼습니다.

Xstate 시각화 다이어그램을 배포하여 링크로 주시거나 캡처한 이미지를 PR에 올려주셨어도 좋을 것 같아요.

그리고 XState의 `guards` 기능도 있던데, 이 부분도 참고해보셔도 좋을 것 같아요.
event가 동작할 수 있는지 유효성 검사하는 기능입니다.
현재 진호님 구현 프로젝트에서는 카드양식입력 단계에서 '다음' 버튼 및 인풋 필드 각각에 대한 유효성검사가 없는데, 이런 경우 state transition의 event에 대한 guard를 적용해볼 수 있을 것 같습니다.
v4 gurad: https://xstate.js.org/docs/guides/guards.html#guards-condition-functions
v5 guard: https://stately.ai/docs/guards

그리고 XState 구현 예시 중에 multi-step-form이 있길래 참고하실 수 있도록 공유드립니다.
https://xstate-catalogue.com/machines/multi-step-form
https://xstate-catalogue.com/machines/multi-step-form-with-validation

2024-03-09 18:16 UTC, wonsss commented on package.json
> +		"xstate": "4.38.3"
오. xstate 4버전을 사용하셨네요. 현재 xstate 버전이 latest가 5.9.1로서, 메이저버전이 4에서 5로 업데이트되면서 여러 개선이 된 것으로 알고 있습니다. @xstate/react 도 4.1.0이 나와 있구요.

xstate 이전 버전을 사용하신 이유가 궁금합니다. 🤔 

xstate v5의 공식 문서입니다.
https://stately.ai/blog/2023-12-01-xstate-v5

2024-03-09 18:16 UTC, wonsss commented on src/components/AddCardStepper.tsx
모든 components 들이 components 폴더에 함께 들어있네요.
components 폴더 안의 컴포넌트들의 이름만 봤을 때, 각각 어느 정도 범위의 역할을 하는 컴포넌트인지 바로 알기는 어려운 것 같아요. 
그래서 실제 사용처들을 일일이 가봐야 서로 의존 관계를 알 수 있게 되는 것 같습니다.
colocation 하게, "파일을 그들이 사용되는 곳 가까이에 위치시키는 식"으로 폴더 구조를 수정해보는 것은 어떨까요? 

AddCardStepper는 Page 단위의 컴포넌트이고,
CardList, AddCardForm, AddCardFinish는 Stepper에서 각각의 Step을 렌더링하는 컴포넌트이므로, components 폴더에서 분리되어 별도의 폴더로 관리되면 좋겠습니다.

```
add-card-stepper
      AddCardStepperPage.tsx
      machines
           addCardMachine.ts
      steps
            CardListStep.tsx
            AddCardFormStep.tsx
            AddCardFinishStep.tsx
      components
            card-list
                  CardList.tsx
                  CardList.hooks.ts
                  CardList.test.tsx
                  CardList.stories.tsx
    ...
```
    
그런데 수정하는 데 많이 번거로울 것 같아, 제안에 대해 참고만 해주셔도 됩니다.
폴더 구조에는 맞고 틀린 것은 없고, 의도와 상황에 따라 매번 달라질 수 있는 것 같아요. 😄

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +		predictableActionArguments: true,
참고로 v5에서는 depreacted 됐더군요

https://stately.ai/docs/migration#actions-ordered-by-default-predictableactionarguments-no-longer-needed

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +			select: {
저는 XState로 간단히 구현하면서 고민했던 점 중 하나가, XState의 createMachine 내 객체 속성들을 읽으면서 좀 읽기가 어렵다는 거였어요. 
타입스크립트가 지원되서 잘못 입력할 우려는 없지만, 문자열로 되어 있는 객체를 쭉 읽다보면 states, events, actions, context 들이 서로 조금씩 헷갈리더라구요. 
그래서 이 부분에 대한 컨벤션이 있으면 가독성이 더 올라갈 수 있겠다는 생각을 했습니다.

개인적으로 생각한 부분이라 참고만 해주셔도 됩니다.

우선 state는 어떤 것을 묘사하는 서술적인 용어면 좋겠습니다.
예를 들어, Pending, Closed, Open, On, Off 처럼요. 또는 이처럼 Stepper Page 상태에 대한 묘사라면, 파일명을 그대로 써도 될 것 같기도 합니다.
그리고 가독성을 위해서라면, 한글이름으로 써도 효과가 더 좋을 것 같아요.

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +			select: {
XState 관련된 유튜브 영상을 보다보니 댓글에 비슷한 고민을 하신 분이 있네요. ㅎㅎ

<img width="1352" alt="image" src="https://github.com/next-step/react-payments/assets/59413128/5d95a0b7-feb2-453b-8b88-11f958679502">

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +			}),
삼항조건연산자를 사용해서 리팩터링할 수도 있을 것 같아요. 😄 
```tsx
			deleteCard: assign({
				cardList: (context, event) =>
					event.type === 'DELETE_CARD' ? context.cardList.filter(card => card.id !== event.value) : context.cardList,
			}),
```

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +			}),
changeField 액션을 각 인풋필드에서 공용으로 사용할 수 있도록 잘 작성해주셨네요. 👍 
각 인풋마다 event에서 field를 달리 전달하여, 액션에서는 전달받은 필드명과 값을 key, value 로 추가하도록 했네요.

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +			}),
그리고 여기도 삼항조건 연산자로 리팩터링해도 좋을 것 같습니다. 😄 
```tsx
			changeField: assign({
				cardInfo: (context, event) =>
					event.type === 'CHANGE_FIELD' ? { ...context.cardInfo, [event.field]: event.value } : context.cardInfo,
			}),
````

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +				const newCardInfo = { ...context.cardInfo, id: Date.now().toString() };
id로 Date.now()를 사용하셨군요. 현재 타임스탬프를 반환하니, 이처럼 간단한 로컬 프로젝트에서는 유효한 방법이라고 생각됩니다.
다만 여러 사용자가 이용하는 서비스에서 중복된 id 생성 가능성이 있습니다. 

프로덕션에서는 고유한 키 값을 생성하는 UUID 라이브러리나 NANO ID 라이브러리를 사용하는 것이 좋을 것 같아요.

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +				},
form state 내에 Compound states로서 selectCardCompany와 enterCardInfo를 만드셨군요. form state 안에서 `selectCardCompany` 모달의 열고 닫는 처리를 이와 같이 잘해주셔서, 객체와 도식만 보고도 이해가 잘 되었습니다.

이러한 `Compound states`는 `statecharts`가 복잡한 상태를 상태머신에서 처리하는 데 유용한 방법이라고 생각합니다! \

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +};
이렇게 중첩된 객체로 CardInfo 객체를 정의할 수도 있을 것 같아요. 수정에 번거롭다면, 참고만 해주셔도 좋아요.
```tsx
  number: { first: string; second: string; third: string; fourth: string }
  expiration: { month: string; year: string }
  ownerName: string
  cvc: string
  password: { first: string; second: string }
  nickname: string
```

2024-03-09 18:16 UTC, wonsss commented on src/components/SelectToFormLayer.tsx
SelectToFormLayer 컴포넌트는 테스트와 스토리북에서 initialState를 변경하기 위해 사용되는 컴포넌트군요!
initialState가 select다 보니까, 다른 state의 스텝 컴포넌트에서는 해당 state로 변경시켜야 하니까 이러한 컴포넌트가 필요할 것 같습니다. 👍 

그런데 사용자에게 노출될 프로덕션 코드에서는 해당 컴포넌트를 사용하지 않을 것이니까, 스토리북과 테스트를 위한 유틸 성격의 별도의 폴더에 두는 것도 좋을 것 같습니다.

2024-03-09 18:16 UTC, wonsss commented on src/components/SelectToFormLayer.tsx
> +	}, [actorRef]);
useEffect의 dependency array에 actorRef를 넣으셨군요.
actorRef는 매번 동일하게 호출하고 있어, 변경되진 않고 있는 것 같아요. 
actorRef의 변화 여부에 의존하여 useEffect 내부 콜백이 호출되도록 기대한다면 다음과 같이 actorRef가 falsy일 때를 방어하는 early return 을 추가해두어야 했을 것 같습니다.
```tsx
	useEffect(() => {
                if(!actorRef) {
                      return
                }
		actorRef.send({ type: 'GO_TO_FORM' });
	}, [actorRef]);
```

하지만 actorRef가 변경되진 않으므로, useEffect에 이처럼 actorRef를 두는 것보다 제거하고 eslint rule을 무시하는 주석을 추가하는 것이 개발자의 의도를 알 수 있는 더 명시적인 코드가 될 것 같아요.

```tsx
	useEffect(() => {
		actorRef.send({ type: 'GO_TO_FORM' });
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);
```

nextjs discussion 중에 이와 비슷한 논의가 있어서 공유드립니다. 😄 
[Should router be in the dependency array of useEffect? #29403
](https://github.com/vercel/next.js/discussions/29403)

2024-03-09 18:16 UTC, wonsss commented on src/constants/card.ts
> +export const MOCK_CARD_INFO_LIST: CardInfoWithId[] = [
mock data를 constants 파일에 다른 정책적인 상수와 함께 두기보다 분리하는 것이 좋을 것 같습니다.
mock 데이터를 두는 폴더는 주로 __mocks__ 또는 mocks와 같은 이름으로 지정됩니다.

2024-03-09 18:16 UTC, wonsss commented on src/stories/card/CardExpirationDateInput.stories.tsx
> +	decorators: [AddCardMachineDecorator],
👍

2024-03-09 18:16 UTC, wonsss commented on src/constants/card.ts
> +};
위와 같은 유틸함수는 비슷해보이는데, 아래와 같이 하나로 만드는 것은 어떨까요?
```ts
export const getCardCompanyByCode = (code: string) => CARD_COMPANY_LIST.find(card => card.code === code)
```

```ts
getCardCompanyByCode(code).className
getCardCompanyByCode(code).name
```

2024-03-09 18:16 UTC, wonsss commented on src/constants/card.ts
> +];
getCardCompanyClassNameByCode와 getCardCompanyNameByCode 함수 모두 code를 갖고 객체의 요소에 접근하는 함수네요.
그렇다면, code를 key로 갖는 객체로 리팩터링하는 것은 어떨까요?

```ts
export const CARD_COMPANY_MAP: Record<string, { name: string; className: string }> = {
	poco: { name: '포코카드', className: 'card-poco' },
	jun: { name: '준 카드', className: 'card-jun' },
	seok: { name: '현석카드', className: 'card-seok' },
	yoon: { name: '윤호카드', className: 'card-yoon' },
	hwan: { name: '환오카드', className: 'card-hwan' },
	taen: { name: '태은카드', className: 'card-taen' },
	joonil: { name: '준일카드', className: 'card-joonil' },
	eunkyu: { name: '은규카드', className: 'card-eunkyu' },
};
```

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +	| { type: 'DELETE_CARD'; value: string };
EVENT 명을 잘 정의해주셔서 이해하기 쉬웠습니다 👍

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +	useSelector: useAddCardMachineSelector,
코드 상에 useAddCardMachineSelector를 사용한 곳이 없네요. 
불필요한 rerender 방지를 하려고 한다면, useSelector를 사용하는 것도 좋을 것 같습니다.

> [#](https://xstate.js.org/docs/packages/xstate-react/#useselector-actor-selector-compare-getsnapshot)useSelector(actor, selector, compare?, getSnapshot?)
A React hook that returns the selected value from the snapshot of an actor, such as a service. This hook will only cause a rerender if the selected value changes, as determined by the optional compare function.

```tsx
	const cardOwnerName = useAddCardMachineSelector(state => state.context.cardInfo.cardOwnerName);
```

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +	useActorRef: useAddCardMachineActorRef,
useActor와 useActorRef를 구분하여 둘 다 사용하셨네요.
그런데 여기서는 사실 useActor만 사용해도 구현이 될 것 같습니다. useActorRef를 사용한 곳에서는 어떤 이유로 useActor 대신 사용하셨는지 궁금합니다. 🤔 

> useActor() - a React hook that returns a tuple of [state, send] from the React Context
> useActorRef() - a React hook that returns the actor ref of the interpreted machine
https://xstate.js.org/docs/packages/xstate-react/#api

2024-03-09 18:16 UTC, wonsss commented on src/__tests__/CardExpirationDateInput.test.tsx
>  }
TestContainer 컴포넌트가 각 테스트 파일 내에서 각각 작성되어 있네요.
그런데 이들의 공통점은 AddCardMachineProviderd와 SelectToFormLayer 컴포넌트들로 테스트하려는 컴포넌트를 Wrapping하고 있다는 것입니다.
따라서 이를 공용의 컴포넌트로 추상화할 수 있을 것 같아요.
`renderWithProviders` 라는 테스트용 유틸함수를 만드실 것을 제안드립니다.
```tsx
import { render, RenderResult } from '@testing-library/react';

export function renderWithProviders(
  children: ReactElement,
) {
  return render(
    <AddCardMachineProvider>
        <SelectToFormLayer>
            {children}
       </SelectToFormLayer>
    </AddCardMachineProvider>,
  );
}
```

```tsx
// 각 테스트 코드 내에서 describe 내에 아래와 같이 추가하여, 각 테스트 시작 전 테스트하려는 컴포넌트를 Provider wrapping하여 렌더
  beforeEach(() => {
    renderWithProviders(<CardExpirationDateInput />);
  });

2024-03-09 18:16 UTC, wonsss commented on src/__tests__/CardNumberInput.test.tsx
코드 체인지에는 안 잡혀 있는데, 테스트 코드 내에 아래와 같이 컴포넌트 렌더를 utils로 반환할 필요는 없지 않을까 싶어요.
그냥 `render(<TestContainer />);`만 해도 충분할 것 같은데 어떻게 생각하시나요?
```
const utils = render(<TestContainer />);
return {
           ...utils
};
```

2024-03-09 18:16 UTC, wonsss commented on src/state/addCardMachine.ts
> +} = createActorContext(addCardMachine);
## 질문에 대한 의견
> 상태 전역으로 관리
step1 pr에서 context api를 사용하여 전역으로 관리하는 것을 제안해 주셨습니다. 그래서 xstate를 적용하며 context api를 적용하였고 코드 가독성이 많이 개선되었다 생각합니다.😄 그런데 스토리북이나 테스트 코드 작성할때는 생각보다 어려운 점이 많았습니다. 예를 들면 카드 번호 입력 input을 테스트 하기 위해서는 form step으로 미리 이동을 시켜주거나 항상 Provider Wrapper가 필요했습니다. 내부 기능을 하는 코드의 가독성은 개선되었는데 스토리북과 테스트 코드는 오히려 복잡해진것 같아 미션을 잘 진행하고 있는 것인지 고민이 들었습니다. 전역상태를 사용하는 컴포넌트를 테스트하거나 스토리북을 적용할때의 노하우가 있으실지 궁금합니다.

진호님께서 이번 step2에서 XState 전환 및 XState에서 제공하는 react context api 적용까지 아주 잘 해주셨다고 생각합니다.
그리고 storybook과 테스트도 이러한 변화에 맞춰 잘 수정해주셨구요.
상태를 주입한 context를 사용하였으므로 해당되는 컴포넌트에 대한 스토리북과 테스트코드에 해당 Context Provider로 감싸주는 것은 당연한 것 같아요. 

> 전역상태를 사용하는 컴포넌트를 테스트하거나 스토리북을 적용할때의 노하우가 있으실지 궁금합니다.

테스트 시 매번 proivders들로 감싸는 번거로움 때문에 그렇다면, renderWithProviders 와 같은 테스트용 유틸함수를 만들어 사용하시는 것도 방법일 것 같습니다. 
다른 코멘트에서 이 내용 관련하여 내용 남겼습니다.

2024-03-09 18:16 UTC, wonsss commented on src/__tests__/CardList.test.tsx
> +		expect(result.current[0].context.cardList.some(el => el.id === MOCK_CARD_INFO_LIST[0].id)).toBeFalsy();
## 질문에 대한 의견
> 테스트 방식
step1에서는 유저 이벤트를 기반으로 테스트 코드를 작성하였습니다. 앱은 유저 이벤트를 바탕으로 동작하여 유저 이벤트 바탕으로 테스트 하는 것이 더 적절하다고 생각했기 때문입니다. 하지만 step2 에서 xstate를 전역으로 관리하면서 특정 테스트에서 유저 이벤트를 사용하여 테스트하기가 어려워 졌습니다. 상태를 hook으로 조회하다보니 renderHook을 사용하는데 컴포넌트에서 유저이벤트가 발생해도 act 함수를 실행시킬 수가 없기 때문이었습니다. 그래서 이후 테스트는 state machine을 테스트하였습니다. 원석님께서는 state machine을 테스트하는 것으로 충분하다 생각하시는지 아니면 유저 이벤트나 E2E테스트등의 실제 동작을 테스트가 꼭 필요하다 생각하시는지 궁금합니다.

1. 컴포넌트 렌더하여 userEvent를 통해 사용자처럼 UI와 상호작용하여 UI의 변화를 테스트하는 방법
2. 훅을 렌더하여 act를 통해 훅의 동작을 실행하고 훅의 상태를 테스트하는 방법(주로 xstate의 context)

이러한 두 가지 방법을 사용하신 것 같아요.
step1에서 1번과 같은 방법을 주로 사용하셨고, step2에서는 2번과 같은 방법을 주로 사용하신 것 같습니다.
둘 다 유효한 방법이라 생각합니다. 

보통 각 테스트는 다음과 같은 특징이 있습니다.
- E2E 테스트: slower, expensive
- Unit 테스트: faster, cheaper

E2E 테스트는 실제 앱의 동작을 그대로 테스트할 수 있지만, 작성 비용도 크고 실행 속도도 상대적으로 느리다보니, 가장 서비스에서 중요한 사용 플로우(ex, 결제시스템)에 제한적으로 사용하는 편입니다.

테스트 코드도 ‘코드’로서, 유지보수의 대상이며, 작성하는 비용 대비 효용을 생각할 필요도 있다고 생각합니다. 그래서 불필요한 곳에서는 테스트하지 않고 핵심적인 곳에만 테스트를 유지해도 좋을 것 같습니다.

2024-03-09 18:16 UTC, wonsss commented on src/__tests__/CardList.test.tsx
> +		expect(result.current[0].context.cardList.some(el => el.id === MOCK_CARD_INFO_LIST[0].id)).toBeFalsy();
이외에 @xstate/react 패키지에서 제공하는 createModel 을 사용하여 xstate를 [model-based로 테스트](https://en.wikipedia.org/wiki/Model-based_testing)하는 방법도 있습니다. 유한상태머신이기에 model-based-test가 가능합니다. 
https://stately.ai/docs/xstate-test#createmodelmachine-options

찾아보니까 xstate model-based-test에 대한 설명과 테스트 데모 코드가 있더라구요. 몇년 전 것이지만, 참고해보셔도 좋을 것 같습니다.
https://slides.com/davidkhourshid/mbt
https://github.com/davidkpiano/xstate-test-demo

2024-03-10 13:14 UTC, Gn0lee commented on package.json
> +		"xstate": "4.38.3"
저는 아래 페이지의 내용을 보면서 구현하였는데 v4기반으로 작성되어있어서 버전을 내려서 구현하였습니다.

https://xstate.js.org/docs/

아직 v5가 준비가 안되었나 보다 했는데 공식문서가 다른곳에 있었군요😅

2024-03-10 13:15 UTC, Gn0lee commented on src/components/AddCardStepper.tsx
처음에는 큰 불편함이 없었는데 기능이 추가되니 불편한점이 있던것 같습니다.

그래서 컴포넌트를 기능 단위로 나누고 test와 storybook을 모아두었습니다.

2024-03-10 13:16 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +		predictableActionArguments: true,
v5로 업데이트 하면 같이 수정하였습니다!

2024-03-10 13:20 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +			select: {
state명이 너무 간단한것 같아서 고민을 하다가 컴포넌트 명으로 수정하였습니다.

AddCardFinish의 경우 nickname 수정에 대한 내용이 없어서 조금 고민하였지만 너무 자세하게 하면 상태명이 너무 길어질 것 같아서 컴포넌트 명으로 결정하였습니다

2024-03-10 13:21 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +			}),
v5로 업데이트하며 각 event에서 action을 바로 지정하여 조건문 자체가 필요없게 되었습니다.

2024-03-10 13:24 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +				const newCardInfo = { ...context.cardInfo, id: Date.now().toString() };
처음 구현당시에는 nanoid로 구현하였는데 jest 환경에서 nanoid 라이브러리가 실행되지 않아서 우선 Date 값으로 구현하였습니다.

jest 환경에서 nanoid가 동작하게끔 이런저런 시도를 하였는데 결국 nanoid를 mocking하는 것으로 마무리 하였습니다🥲

https://github.com/ai/nanoid/issues/363

2024-03-10 13:27 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +				},
사실 Compound state가 뭔지 모르고 구현하다보니 이런 구조로 구현하였네요ㅎㅎ

모달의 visible을 useState로 지정할까 하다가 xstate에 포함시킬수 있을 것 같아 방법을 찾아봤습니다.

Compound state관련 내용을 한번 찾아봐야겠네요😀

2024-03-10 13:30 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +};
저도 제시해주신 방식대로 객체를 정의하고 싶었는데 CHANGE_FIELD에서 공통으로 사용하려면 depth가 동일해야해서 우선 현재와 같은 방식으로 구현하였습니다.

event.field의 string을 "."으로 구현하면 될 것 같기는 한데 구현하는 비용이 엄청날 것 같다는 생각이 들었습니다.
원석님 의견은 어떠신지 궁금합니다!

2024-03-10 13:34 UTC, Gn0lee commented on src/components/SelectToFormLayer.tsx
해당 컴포넌트는 /components/utils로 이동시켰습니다

2024-03-10 13:44 UTC, Gn0lee commented on src/components/SelectToFormLayer.tsx
> +	}, [actorRef]);
저는 기존에 dependancy array에 useEffect 내부에서 사용하는 변수들을 대부분 포함시키려고 했습니다. 작성자가 변수에 대한 확인을 끝냈다 라고 생각했기 때문입니다. 그래서 custom hook을 만들때 dependency 배열에 추가될 함수라면 useCallback등으로 처리해서 사용했습니다. 위에서 알려주신 router나 react-router-dom의 useNavigate등을 사용할 때는 주석처리를 합니다.

그런데 코멘트를 읽고나니 원래 useEffect의 의도를 생각하면 변화를 감지할 변수만 포함시키는게 맞겠다라는 생각이 들어 dependancy array에 주석처리를 하였습니다.

2024-03-10 13:45 UTC, Gn0lee commented on src/constants/card.ts
> +export const MOCK_CARD_INFO_LIST: CardInfoWithId[] = [
mocks로 이동시키며 해당 mock data를 사용하는 machine을 정의하여 다른 테스트 파일에서 같이 사용할 수 있도록 수정하였습니다.

2024-03-10 13:46 UTC, Gn0lee commented on src/constants/card.ts
> +];
리스트의 값을 객체로 만들어서 재사용하는 방식으로 수정하였습니다.

기존 get 함수를 사용하면 매번 순회하여 성능에도 좋지 못할 것 같네요

2024-03-10 13:47 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +	useActorRef: useAddCardMachineActorRef,
처음에는 send만 하는 컴포넌트에서는 useActorRef를 사용하고 state와 send를 동시에 하는 컴포넌트에서는 useActor를 사용하였습니다.

v5로 업데이트 하며 useActor가 없어져서 전체적으로 수정하였습니다~

2024-03-10 13:48 UTC, Gn0lee commented on src/__tests__/CardExpirationDateInput.test.tsx
>  }
AddCardMachineProvider를 사용하는 render, renderHook 함수를 만들어 재사용하도록 수정하였습니다!

2024-03-10 13:49 UTC, Gn0lee commented on src/__tests__/CardNumberInput.test.tsx
예전 코드를 참고하며 작성하다보니 비슷하게 작성하였네요ㅜㅜ

setup에서 render 하던 것을 beforeAll로 이동시켰습니다

2024-03-10 14:03 UTC, Gn0lee commented on src/__tests__/CardList.test.tsx
> +		expect(result.current[0].context.cardList.some(el => el.id === MOCK_CARD_INFO_LIST[0].id)).toBeFalsy();
좋은 자료 감사합니다!

2024-03-10 14:16 UTC, Gn0lee commented
제가 웹스톰을 사용하고 있는데 intellij에는 xstate 플러그인이 없어서 vscode 새로 설치해서 이미지 첨부합니다.

![image](https://github.com/next-step/react-payments/assets/93526602/5d5bb4ef-61c5-4188-890a-283517ceeb50)

유효성 검사같은 경우는 step3의 요구조건인 것 같아 우선 추가하지 않았습니다.

도움이 되는 자료들 많이 공유해주셔서 큰 도움이 되었습니다ㅎㅎ 감사합니다!!🙇‍♂️

2024-03-11 14:09 UTC, wonsss commented on package.json
> +		"xstate": "4.38.3"
그러게요 ㅎㅎ 공식문서가 도메인도 다르게 해서 만들어서 좀 헷갈리더라구요.

2024-03-11 14:20 UTC, wonsss commented on src/components/AddCardStepper.tsx
우와 수고 많으셨습니다. 수정할 부분 많으셨을텐데, 역시 진호님 👍 꼼꼼하고 빠르게 잘 수정해주셨네요.
폴더구조 지금도 넘 충분합니다. ㅎㅎ 추가적으로 이런 의견도 더 제안드립니다.
아래 스크린샷처럼 steps 폴더 내에 각 스텝 폴더를 만들고, 해당 스텝에서만 사용되는 컴포넌트들을 components 폴더 내에 모아두는 것은 어떨까요? 지금은 어떤 스텝과 관련된 컴포넌트를 루트에 있는 components 폴더로 찾아가며 왔다갔다 하고 있어서, 이런 부분도 이렇게 수정하면 조금 더 나아질 수 있을 것 같아요. 😄 
<img width="329" alt="image" src="https://github.com/next-step/react-payments/assets/59413128/c19d44ae-5ac5-4448-9967-ffd1bcaccd18">

2024-03-11 14:21 UTC, wonsss commented on src/state/addCardMachine.ts
> +		predictableActionArguments: true,
v5로 업데이트까지..! 대단하십니다 👍

2024-03-11 14:22 UTC, wonsss commented on src/state/addCardMachine.ts
> +			select: {
step을 의미하는 컴포넌트 명을 state로 하는 것도 1:1 매칭이 되니 적절한 것 같네요 👍

2024-03-11 14:28 UTC, wonsss commented on src/state/addCardMachine.ts
> +			}),
오 맞습니다. v5가 그게 좋더라구요.
지금 action inline으로 다 정의하셨는데, action objects로 하면 가독성이 더 높아질 것 같습니다.
XState에서도 action objects를 권장하더라구요. 
https://stately.ai/docs/actions#action-objects
<img width="797" alt="image" src="https://github.com/next-step/react-payments/assets/59413128/d44a6679-5df8-43f7-9e56-d2f57a3a912b">

2024-03-11 14:29 UTC, wonsss commented on src/state/addCardMachine.ts
> +				const newCardInfo = { ...context.cardInfo, id: Date.now().toString() };
네. mocking 적절하게 잘 해주셨네요. 멋집니다 👍

2024-03-11 14:35 UTC, wonsss commented on src/state/addCardMachine.ts
> +				},
compound states는 parent states라고 말하기도 하더라구요. https://stately.ai/docs/state-machines-and-statecharts#parent-states
그리고 parallel states도 가능하던데 참고해보세요. ㅎㅎ 
https://stately.ai/docs/state-machines-and-statecharts#parallel-states

2024-03-11 14:35 UTC, wonsss commented on src/state/addCardMachine.ts
> +};
비용이 많이 든다면 현재 방식도 유효할 것 같아요!

2024-03-11 14:38 UTC, wonsss commented on src/constants/card.ts
> +];
reduce 사용해서 멋진 방식으로 리팩터링 해주셨네요 👍

2024-03-11 14:40 UTC, wonsss commented on src/state/addCardMachine.ts
> +	useActorRef: useAddCardMachineActorRef,
코드가 더 명료해졌네요!

2024-03-11 15:05 UTC, wonsss commented on src/state/addCardMachine.ts
> +	useSelector: useAddCardMachineSelector,
댓글을 달진 않으셨지만, useSelector사용하여 코드상에 리팩터링하신 부분 확인하였습니다! 👍 
그런데 이로 인해 불필요한 리렌더링 방지 이득을 얻으려면, AddCardForm 스텝 컴포넌트에서 CardImage 에 props를 넘기지 말고, CardImage 내에서 직접 selector로 상태를 가져오는 게 좋을 것 같아요. 성능적 향상이 별로 크진 않지만, 어느 정도 불필요한 리렌더링이 조금은 줄어들 수 있고, 어차피 context 사용하는 거 코드도 더 깔끔해질 것 같아요.ㅎㅎ
<img width="1393" alt="image" src="https://github.com/next-step/react-payments/assets/59413128/c783ddb7-199a-4fbb-b289-0c18a120e4ed">
코드 수정 후 리렌더링
https://github.com/next-step/react-payments/assets/59413128/74cddc39-5527-4e10-9e1e-3818bf367152

2024-03-11 15:09 UTC, wonsss commented on src/__tests__/CardNumberInput.test.tsx
리팩터링한 코드 보았습니다. 좋네요 👍 
그리고 setup()이라는 함수명도 좋은데, 해당 함수의 역할이 dom에서 요소를 가져오는 거니까 `getTargetElement()` 라는 이름도 고려해볼만 할 것 같아요.

2024-03-11 15:14 UTC, wonsss approved these changes
진호님. 빠르고 꼼꼼하게 피드백 반영해주셔서 감사합니다. 👏 
진짜 잘 해주고 계셔서, 저도 덕분에 많이 배우면서 하고 있네요 👍 
댓글을 몇 가지 조금 더 남겼는데, 엄청 중요한 부분은 아니지만, 조금 더 참고하실 시간이 아직 있는 것 같아서 바로 merge는 하지 않고 화요일 자정 이후에 다시 확인 후 merge할게요.

2024-03-12 10:51 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +			}),
action object로 변경하고 나니 테스트를 위한 MOCK_CARD_LIST 주입하는 것이 제대로 동작을 안하더라구요.

이전에는 ...addCardMachine.config를 createMachine에 주입해도 문제가 없었는데 action object로 수정하니 문제가 계속 생겨서 machine의 설정을 그대로 가져와 사용하였습니다.

2024-03-12 10:53 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +	useSelector: useAddCardMachineSelector,
해당 컴포넌트가 AddCardFinish에서도 공통으로 사용하여 props로 설정해두었습니다.

그래서 select 함수(ex. state => state.cardInfo)를 인자로 내릴지 아니면 컴포넌트를 한 단계를 더 만들지 고민이 됩니다.

원석님의 의견이 궁금합니다!

2024-03-12 13:59 UTC, Gn0lee commented on src/state/addCardMachine.ts
> +	useSelector: useAddCardMachineSelector,
CardImage를 AddCardFinish나 CardListItem에서도 재활용 하기 때문에 useSelector를 CardImage안으로 이동시키지는 못했습니다. 하지만 CardImage를 사용하는 데이터를 담는 컨테이너 컴포넌트를 만들고 해당 컴포넌트에서 CardImage를 사용하게 하였습니다.

그리고 shallowEqual을 사용하여 불필요한 렌더링을 줄이도록 처리하였습니다

2024-03-12 14:02 UTC, wonsss commented on src/state/addCardMachine.ts
> +			}),
아하.. xstate v5에서 action object 가 기대만큼 잘 동작하는 게 아닌 것 같군요..?ㅠ

2024-03-12 14:02 UTC, wonsss commented on src/state/addCardMachine.ts
> +	useSelector: useAddCardMachineSelector,
수고하셨습니다. 피드백 반영 감사합니다.

2024-03-12 14:04 UTC, wonsss approved these changes

2024-03-12 14:04 UTC, wonsss commented on src/machines/addCardMachine.ts
> +					actions: [{ type: 'selectCard' }],
👍

2024-03-12 14:05 UTC, wonsss approved these changes
진호님! 항상 빠르고 완벽한 피드백 반영 감사합니다. 👍 
2단계 미션은 여기서 마무리해도 괜찮을 것 같습니다.
다음 미션도 화이팅입니다! 💪

2024-03-12 14:05 UTC, merged