[클린코드 리액트 3기 정수현] 페이먼츠 미션 Step2
next-step/react-payments pull request #132
Opened 2024-03-09 18:04 UTC by sasha1107

2024-03-10 18:11 UTC, ronci requested changes
안녕하세요 수현님! step2 미션도 수고하셨습니다! 👍 
이번 미션의 중심이었던 xState 사용을 중점적으로 확인해보았습니다!
코드리뷰에도 달아놓았지만 v5를 사용하시는 만큼 v5 문법으로 변경해보는 건 어떨까해요.
v4 버전의 문서는 더 이상 유지보수 안된다고 문서에 작성되어있더라구요.
XState Visualizer을 활용한 부분도 좀 더 보여주시면 좋을 것 같아요!

----

> 1. dependencies 와 devDependencies 구분하여 설치하기
> devDependencies로 설치해도 빌드 시 문제 없을지 파악할 수 있는 방법이 있을까요?
> 평소에는 공식 문서에 따라 예시로 주어지는 install 코드에 -D 옵션이 있을 경우 devDependencies로 설치하고, 그렇지 않은 경우 dependencies로 설치하고 있습니다. 가급적이면 devDependencies로 설치하여 빌드에 포함시키고 싶지 않은데, 이를 어떻게 구분할 수 있을지 궁금합니다. xstate, xstate-react의 경우에도 문서에서 제공하는 코드로 설치하여 dependencies에 추가되었습니다.

로컬에서 build 후 start했을 때 알 수 있어요!
devDependency에 설치되는 라이브러리들은 개발할 때 사용되고 배포에서는 사용하지 않는 라이브러리들을 설치하는 방법으로 구분할 수 있는데, devDependency로 의심되는 라이브러리는 한 번 설치해보고 안되면 dependency에 넣어도 괜찮겠네요!

> 2. 프론트엔드에서 id 값을 만든다고 할 때 어떤 방법을 사용하는게 좋다고 생각하시나요?
> 데이터의 unique한 id(예. cardlist에서 card를 구분할 수 있는 값)값은 백엔드에서 생성되는게 일반적이지만, 다음 과제와 같이 백엔드에 의존하지 않는 상황에서 어떤 방법으로 id를 생성하는게 best practice라고 생각하시는지 궁금합니다.

대부분은 백엔드에서 만들어주는 방법이 일반적이겠지만,
해당 프로젝트의 경우에는 uuid를 사용하는 방법이 있을 것 같아요!
다만 uuid 중복관련된 이슈도 있으니 알고만 계시면 좋을 것 같아요.
물론 일어날 확률은 극악입니다!

2024-03-10 18:11 UTC, ronci commented on src/pages/new/steps/CardInfo.tsx
> +  next: (data: Map<Partial<FormItemKeys>, FormItemValues<FormItems>>) => void;
next의 경우 위에서 props로 내리지 않고 해당 컴포넌트에서 가져와서 쓸 수 있을 것으로 보여요!
최대한 종속성이 없도록 바꿔보는 건 어떨까요?

2024-03-10 18:11 UTC, ronci commented on src/pages/new/steps/CardName.tsx
> +  );
useMachine을 사용해보는 건 어떨까요?

2024-03-10 18:11 UTC, ronci commented on src/pages/new/steps/CardName.tsx
> +  const cardBrand = useMemo(() => {
useMemo를 쓰신 이유가 있을까요?

2024-03-10 18:11 UTC, ronci commented on src/pages/new/steps/Stepper.tsx
> +  );
현재 설치되어있는 XState는 v5이지만 v4문법을 많이 쓰시는 것 같아요!
v5에서는 어떻게 쓰는 지 확인해보고 수정하면 좋을 듯 합니다!

2024-03-10 18:11 UTC, ronci commented on src/pages/new/context.ts
> +  },
상태 머신의 states들을 수정하는 값들을 기준으로 잡은 것 같아요!
type: 'final'의 경우는 마지막 상태, 종료를 의미하는 상태인만큼 카드 입력 상태가 아닌,
카드의 정보들을 모두 입력하고 확인을 했을 때 마지막 상태로 전환되면서 끝내는 것은 어떨까합니다!

2024-03-10 18:11 UTC, ronci commented on src/pages/new/context.ts
상태 머신의 경우는 pages 폴더의 목적과는 맞지 않는 것 같아서 다른 곳으로 분리하는 것이 좋을 것 같아요!

2024-03-10 18:11 UTC, ronci commented on src/pages/new/context.ts
> +      on: {
카드 이름 입력에서 카드 정보 입력으로 돌아가는 케이스는 없는 걸까요?

2024-03-10 18:11 UTC, ronci commented on src/pages/new/context.ts
> +  },
추가적으로 수정하는 상태들만 상태관리에 쓰는 것이 아니라 카드 정보들이 가지는 상태들에 대한 상태머신을 만들어보는 것은 어떨까하네요!

2024-03-10 18:11 UTC, ronci commented on src/components/card/index.tsx
> +          // marginTop: 'auto',
불필요한 스타일링 제거 부탁드려용!

2024-03-10 18:11 UTC, ronci commented on src/components/input/index.tsx
> +  const classNames = cn([styles.inputElement, className]);
여기도 다른 컴포넌트에서 사용한 것 처럼 통일화하면 좋을 것 같아요!
``` tsx
const Input = ({
    className,
    htmpType = 'text',
    type = 'default',
    block = false,
    ...rest
  }: InputProps) => {
```

2024-03-10 18:11 UTC, ronci commented on src/utils/mapToObj.ts
한 파일에 하나의 함수만 매칭되면 후에 너무 많은 util 파일들이 생기는 문제가 발생할 것 같아요.
mapToObj와 objToMap은 하나의 파일에 넣어놔도 될 것 같아요!

2024-03-10 18:11 UTC, ronci commented on src/pages/new/steps/Stepper.tsx
> +        />
컴포넌트 렌더링 부분에서 너무 많은 로직이 있는 것 같아요! 함수로 한 번 분리해보는 건 어떨까요?

2024-03-11 13:10 UTC, sasha1107 commented on src/pages/new/steps/CardName.tsx
> +  const cardBrand = useMemo(() => {
첫 렌더링 이후 리렌더링 될 때 딱히 변경되지 않는 값이라 불필요한 로직이어서 삭제하였습니다. 꼼꼼한 피드백 감사합니다 ☺️

2024-03-11 13:21 UTC, sasha1107 commented on src/pages/new/steps/Stepper.tsx
> +  );
앗 [@xstate/react](https://stately.ai/docs/xstate-react) 섹션의 코드를 최대한 따라해보았는데 상단에 v5라 적혀 있어서 사용했습니다😅 이전 버전에 해당하는건가요?? 😭

2024-03-11 13:24 UTC, sasha1107 commented on src/pages/new/context.ts
감사합니다! 
`pages/` 폴더에서 분리하여 `src/machine/`이란 폴더로 분리했는데 공식 문서의 예제에는 폴더명에 대한 컨벤션은 따로 없는것 같네요,,
혹시 xstate를 사용하신다면 사용하시는 폴더명 컨벤션이 있을까요? 😮😮

2024-03-11 13:56 UTC, sasha1107 commented on src/pages/new/steps/CardName.tsx
> +  );
https://github.com/sasha1107/react-payments/blob/0e144f51d8d8dde6b4711efbe44baabc25843d6f/src/pages/new/index.tsx#L5-L13

2024-03-11 14:01 UTC, sasha1107 commented on src/pages/new/context.ts
> +      on: {
ui에서 카드 입력 폼으로 돌아가도록 되어 있지 않아서 미처 생각하지 못했네요!
뒤로 돌아가는 경우도 고려하여 action 추가하였습니다.
감사합니다 :)

2024-03-11 14:36 UTC, sasha1107 commented
연지님 step2도 꼼꼼한 리뷰 감사드립니다👍🤩
리뷰 반영하여 수정했습니다.
devDependency는 직접 빌드하여 확인해 봐야겠네요. 좋은 정보 감사합니다. ☺️
그리고 기존에 카드 번호 16자리로 id값을 관리하고 있어서 중복된 카드 번호를 입력할 경우 기존 작성한 내용이 오버라이드 될 수 있는 문제가 있었는데 말씀 주신 uuid로 id값을 관리하도록 수정하였습니다.
그리고 기존에 form(+비제어 컴포넌트) 단위로 Stepper를 관리하고 있어서 이를 기준으로 XState 머신을 만들다 보니 [큰 단위](https://github.com/next-step/react-payments/pull/132/#discussion_r1518907931)로 관리하게 되었는데요,,다음 step에서 auto focusing에 대한 요구사항이 있어서 카드 정보들이 가지는 상태들에 대한 머신으로 리팩토링하며 구현해보고 싶습니다...🫠
구현한 머신을 [XState Visualizer](https://stately.ai/viz/f18b60c0-3f82-463c-888e-a18ea8a3db5d)에 넣어보았습니다!
감사합니다🙏

2024-03-12 13:49 UTC, ronci commented on src/pages/new/steps/CardName.tsx
> +  );
createActorContext가 v4문서에는 존재하지만 v5에는 사라진 것 같더라구요! 😢 
그것에 따라서 호환하는 API가 달라서 접근이 안되는 것 같아요..

2024-03-12 13:51 UTC, ronci commented on src/pages/new/steps/Stepper.tsx
> +  );
https://xstate.js.org/docs/packages/xstate-react/
v4에서 지원하는 것 같아요 😢

2024-03-12 13:52 UTC, ronci commented on src/pages/new/context.ts
따로 컨벤션은 없지만 저였어도 수현님처럼 machine으로 분리해놓을 것 같네용!
해당 레벨로도 충분한 것 같습니다! 👍

2024-03-13 13:07 UTC, ronci reviewed
.

2024-03-13 13:08 UTC, ronci requested changes
수현님 코드리뷰 반영하시느라 수고하셨어요!
댓글로만 작성하면 알람이 따로 안가더라구요..! 😢 
수현님이 주신 질문에 대해 답변 달아놓았는데 확인 한 번 해주세요! 👍

2024-03-14 00:35 UTC, sasha1107 commented on src/pages/new/steps/CardName.tsx
> +  );
https://stately.ai/docs/xstate-react#createactorcontextlogic

이 부분 확인되는 것으로 보입니다.

2024-03-14 00:42 UTC, sasha1107 commented
https://stately.ai/docs/migration

해당 문서에서 deprecated된다는 api를 사용하지 않아서..어떤 부분을 개선할 수 있을 지 잘 와닿지 않습니다😅

2024-03-16 05:48 UTC, ronci commented on src/pages/new/steps/CardName.tsx
> +  );
확인해보니 context 내부에서 사용하려면 수현님께서 구현하신 방법으로 밖에 접근이 안되는 것 같네요.. 😢 
죄송합니다.

2024-03-16 05:48 UTC, ronci approved these changes
확인해보니 context 내부에서 사용하려면 수현님께서 구현하신 방법으로 밖에 접근이 안되는 것 같네요.. 😢 
approve 후 머지하겠습니다!
수고하셨어요!

2024-03-16 05:48 UTC, merged