[클린코드 리액트 3기 박재영] 페이먼츠 미션 Step2
next-step/react-payments pull request #146
Opened 2024-03-15 15:07 UTC by SaeWooKKang

안녕하세요 윤호님! 작업이 조금 지연되는것 같아서 작업된 부분 우선 pr 리뷰 부탁드리겠습니다! 

## 작업 설명

이번 작업은 xState 사용을 중점적으로 했습니다. 내용이 어렵네요 😅
- step 관리를 기존 useFunnel 훅에서 xState로 완전히 변경했습니다.
- Form.tsx의 validate props를 옮기지 못했습니다. 왜냐하면 해당 공통 컴포넌트는 input의 입력된 상태를 가지고 있다가 submit시 값을 확인할 수 있기 때문입니다. 이 부분도 xState로 옮길 수 있으면 좋을것 같긴 한데.. 고민입니다. 😅
``` ts
 <Form
   initialValues={paymentsMachine.context.registration}
   onSubmit={(values) => paymentActorRef.send({ type: 'SUBMIT', value: values })} // 🚧 submit시 해당 값 받을 수 있음
   validate={Step1Validate}
   >
    <Step1 />
 </Form>
```
- xState 관련 참고한 아티클
  - https://fe-developers.kakaoent.com/2022/220922-make-cart-with-xstate/
  - https://blog.hwahae.co.kr/all/tech/6707

- card 컴포넌트 컴파운드 패턴으로 작성
  -  카드의 UI가 조금씩 다를 수 있다고 생각했습니다. (ex 카드번호의 위치가 제일 상단으로 가능 경우 등등)
-  폴더 구조를 변경
```
// 특정 도메인 components 폴더링
📦src/features/payments
 ┣ 📂Card
 ┣ 📂Layout
 ┣ 📂Step1
 ┃ ┣ 📂Components
 ┗ 📂Step2

// 특정 비지니스 로직 폴더링
📦service
 ┗ 📂payments
 ┃ ┣ 📜index.ts
 ┃ ┣ 📜payments.const.ts
 ┃ ┣ 📜payments.machine.ts
 ┃ ┣ 📜payments.type.ts
 ┃ ┗ 📜validations.ts
```
기존에는 react-router-dom 라이브러리를 사용하고, url 기반으로 폴더링하여 필요한 컴포넌트들을 해당 페이지 하위 components 하위에 관리 했었는데 xState를 사용하면서 하나의 컴포넌트에서 flow를 관리하고 싶어서(?) 폴더를 분리 했습니다. 이렇게 되면 문제점이 step이 상태이기에 새로고침시 해당 step을 유지하지 못하는 단점이 있는데 브라우저의 history와 어떻게 연결할지는 고민해봐야 할 것 같습니다. (query를 사용하는것도 좋겠네요) 

매 프로젝트마다 '폴더 구조를 어떻게 가져가야 할까?'가 정말 고민되는것 같습니다. 고민해도 뭔가 '정답이다!' 싶은것도 없는것 같구요 ㅜ 윤호님이 생각하시는 진짜 '베스트 프랙티스'다 싶은 구조가 있을까요?

## 배포
- 📕 [storybook](https://65f44fcf318b8b151c8bea58-mfhmcghvki.chromatic.com/?path=/docs/components-input--docs)
- 🎰 [xState](https://stately.ai/registry/editor/4ff5a20f-15f7-483e-b604-f25101e810c7?machineId=12860f4d-a28d-4b41-b6ff-cca39e52d965&mode=Design)

## 요구사항

### 필수 요구사항
- [x] 원시적인 형태의 Primitive UI 형태의 컴포넌트 작성
- [x] Storybook 상호 작용 테스트
- [x] Controlled & Uncontrolled Components를 명확하게 구분하거나 선택하여 구현
- [x] 설계한 Stepper을 [XState Visualizer](https://stately.ai/viz)를 활용하여 구현

### 카드 추가 확인
- [x] 이전 폼에서 입력된 카드를 보여준다.
- [x] 카드 별칭을 입력할 수 있다.
- [x] placeholder는 카드 별칭 (선택)이다.
- [x] 빈 입력값인 경우, 카드사 이름이 별칭으로 저장된다.
- [x] 최대 길이는 10자리이다.
- [x] 확인 버튼을 누르면, 카드 목록 페이지로 이동한다.

### 카드 목록(🔨 TODO)
- [ ] 카드 목록을 조회할 수 있다.
- [ ] 카드 목록은 최신순(내림차순)으로 정렬된다.
- [ ] 목록 최상단에 +을 누르면 카드 추가 페이지로 이동한다.
- [ ] 카드를 클릭하면, 카드 별칭 수정(카드 추가 완료 페이지)로 이동한다.
- [ ] 카드를 삭제할 수 있다.

2024-03-18 17:45 UTC, yujo11 requested changes
안녕하세요 재영님 먼저 리뷰가 늦어져서 정말 죄송합니다 🥲🥲🥲

다음 번 리뷰는 꼭 빠르게 드릴 수 있도록 하겠습니다

---

>이번 작업은 xState 사용을 중점적으로 했습니다. 내용이 어렵네요 😅

xState를 처음 봤을 때 xState의 철학과 visualizer를 통해 상태의 흐름을 파악할 수 있다는 점이 굉장히 좋다고 느껴졌는데 실제 프로덕트에 적용하는 건 쉽지 않더라구요. 주변에 프로덕트에 적용했다는 팀이 있어 물어봤는데 유지가 어렵고(다른 상태관리 라이브러리와 비교해서 러닝커브 존재) 복잡한 상태관리가 필요하지 않아 걷어내고 있다는 얘기를 듣기도 헀네요 😅 그래도 한번쯤 사용해보면 좋을 라이브러리라고 생각합니다

>Form.tsx의 validate props를 옮기지 못했습니다. 왜냐하면 해당 공통 컴포넌트는 input의 입력된 상태를 가지고 있다가 submit시 값을 확인할 수 있기 때문입니다. 이 부분도 xState로 옮길 수 있으면 좋을것 같긴 한데.. 고민입니다. 😅

xState에서 submit 시, validate을 직접 호출하거나 vlidate의 결과를 xState의 상태로 저장하면 가능할거 같다는 생각이 드는데 xState 사용이 능숙하지 않아 확신은 안 드네요 🥲 이 부분은 저도 같이 좀 더 고민해보겠습니다.

> 폴더 구조

이 부분은 정답이 없고 항상 어려운 부분이지만 코드베이스가 큰 프로덕트를 여러번 구현하면서 저는 사용하는 곳과 선언되는 곳이 물리적으로(파일트리 상으로) 가까운 것을 선호하게 되었습니다. 아래는 제가 개인적으로 생각하는 Bad Case, Good Case입니다.

- BAD
```
.
└── src
    ├── api
    │   └── v1
    │       └── warehouse
    │           ├── warehouse-list.ts
    │           └── warehouse.ts
    ├── components
    │   └── vendor
    │       └── warehouse-list
    │           └── SearchPanel
    │               ├── SearchPanel.tsx
    │               ├── index.ts
    │               └── style.tsx
    ├── containers
    │   └── vendor
    │       └── VendorListContainer
    │           ├── VendorListContainer.tsx
    │           └── index.ts
    └── types
        └── dtos
            └── warehouse
                └── warehouse-list.ts
```
- GOOD
```
.
└── src
    └── domain
        └── vendor
            └── warehouse-list
                ├── api
                │   └── warehouse-list.api.ts
                ├── components
                │   └── SearchPanel
                │       ├── SearchPanel.tsx
                │       ├── SearchPanle.styled.tsx
                │       └── index.ts
                ├── page
                │   └── WarehouseListPage
                │       ├── WarehouseListPage.tsx  // init 지점이 되는 페이지
                │       └── index.ts
                └── types
                    └── warehouse-list.type.ts
```

프로덕트 규모가 점점 커지고 파일 수가 수백개가 되면서 이런 식으로 가까이 있지 않으면 파일트리 상에서 파일을 찾는 것도 꽤 시간이 걸리더라구요 ㅎㅎ

최근에 새로 만들거나 한 프로덕트는 대부분 위의 GOOD Case 구조를 따라가고 있는거 같습니다.

---

이번에 새로 구현 된 코드가 많지 않고 코드를 깔끔하게 작성해주셔서 리뷰 남길 내용이 많지 않았는데요. 구현 못 하신 부분들 추가로 구현해서 리뷰 요청 주시면 좋을거 같습니다!

고생 많으셨습니다 재영님!! 👍 👍 👍

2024-03-18 17:45 UTC, yujo11 commented on package.json
> +    "xstate": "^5.9.1"
👍 👍 👍

2024-03-18 17:45 UTC, yujo11 commented on src/features/payments/Card/Card.tsx
> +}
`Card`와 관련된 부분을 같이 구현하신게 좋네용 ㅎㅎ 👍 👍 👍

2024-03-18 17:45 UTC, yujo11 commented on src/features/payments/Card/Card.tsx
> +Card.CardCompany = (props: CardCompanyProps) => {
props를 구조분해할당으로 받은 곳도 있고 여기처럼 그냥 받은 곳도 있는데 어떤 기준으로 나누셨는지 궁금하네용

2024-03-18 17:45 UTC, yujo11 commented on src/features/payments/Card/Card.tsx
> +  const cardNumber = creditCardNumber.split(' ').join('')
공백을 제거하기 위해 이 로직이 필요한걸까용

2024-03-18 17:45 UTC, yujo11 commented on src/service/payments/payments.machine.ts
> +              registration: Object.assign(context.registration, event.value),
객체를 병합하기 위해 `Object.assign`을 사용하신거라면 spread 연산자를 사용하면이 가독성이 더 좋아질거 같다는 생각이 드네요
```suggestion
              registration: {...context.registration, event.value},
```

2024-03-19 13:43 UTC, SaeWooKKang commented on src/features/payments/Card/Card.tsx
> +Card.CardCompany = (props: CardCompanyProps) => {
예를들어서 atom 정도 단위의 컴포넌트를 만든다고 한다면, 컴포넌트의 기본 속성들을 정의한채 사용자의 props를 합칠 때 사용하는 편입니다. ( ex) 컴포넌트의 기본 스타일링을 적용한 채, props로 클라이언트의 스타일을 추가하는 경우 )

```ts
export const Card = ({ children, backgroundColor, style, ...rest }: CardProps) => {
  return (
    <section className="big-card card-box" style={{ backgroundColor, ...style }} {...rest}>
      {children}
    </section>
  )
}
```

좀 더 큰 단위의 컴포넌트를 만들땐 props가 추가되는 경우가 종종 있는데 props가 추가됨에 따른 변경을 최소화하기 위해서 되도록 구조분해할당을 하지 않으려 합니다. 또한 props로 내려온 값을 명확하게 알 수 있어서 컴포넌트 내부 변수와 구분되는 점에서 가독성도 더 좋은것 같구요 😁


``` ts
// prev
interface Props {
  a,
  b,
}

// after
interface Props {
  a,
  b,
  c,
  ...
  z,
}

❌
const Organism = ({a, b, c, ..., z}: Props) => {...}

✅
const Organism = (props: Props) => {
  const blabal = props.a + props.z

  return <>blabla..</>
}
```

2024-03-24 04:30 UTC, SaeWooKKang commented
안녕하세요 윤호님! 나머지 요구사항 모두 완료하여 리뷰 요청 드립니다. 남겨주신 리뷰또한 잘 읽어보았습니다 😁

> 이 부분은 정답이 없고 항상 어려운 부분이지만 코드베이스가 큰 프로덕트를 여러번 구현하면서 저는 사용하는 곳과 선언되는 곳이 물리적으로(파일트리 상으로) 가까운 것을 선호하게 되었습니다. 아래는 제가 개인적으로 생각하는 Bad Case, Good Case입니다.

저도 말씀해주신바와 같이 코로케이션하게 모아두는것이 관리 측면에서 좋다고 생각합니다. 예시로 들어주신 폴더 구조관련해서 추가로 궁금한 점이 있습니다.

경로가 `/domain/vendor/varehouse-list` 하위에 각각의 폴더로 `api`, `components`, `page`, `types`를 만드셨는데 그렇다면 `/domain/vendor/varehouse-list` 해당 주소가 **url**을 따라가는 주소인지 궁금합니다. 만약 url을 따라가는 구조라면 상세 주소의 경우 `/domain/vendor/varehouse-list/[id]`와 같은 형식일 수 있다고 생각하는데 해당 폴더 하위에 똑같이 `api`, `components`, `page`, `types`구조를 만들게 되는것인지 궁금합니다. 추가로 배럴파일로 만드신 이유도 알고 싶습니다!

수정, 삭제를 xState로 관리하려니 꽤나 어렵더라구요 ㅎㅎ 카드 등록, 닉네임 설정을 하고 상태 머신을 종료하려고 type을 final로 만들었었는데 final 상태에서는 상태의 전이가 안되더라구요; 상태를 종료하고, 재실행? 하고 싶었는데 방법을 못찾아서 상태 종료는 못시켰습니다. 

이번 구현을 하면서 중점을 둔 부분은 좀 더 타입으로 연결(?) 할 수 있도록 작업을 진행했습니다. 
예를 들어서 이전에는 form 노출 조건을 아래와 같이 문자열 비교로 작성했었는데 xState의 상태명을 변경했을 때 해당 조건에 걸리지 않아서 빈화면이 노출되더라구요. 그래서 상태도 상수화해서 관리하면 상태 변경시 타입에러로 좀 더 빠른 디버깅이 가능할 것 같아서 변경했습니다. 

``` ts

// prev: 문자열이 변경되어도 타입 에러 x
if (['card-registration-complete', 'card-nickname-submitting'].includes(paymentsMachine.value)) {
  return <></>
}

// after: 변경시 PAYMENT_STATE를 직접 참조 해야함
const step2ConditionList: ReadonlyArray<(typeof PAYMENT_STATE)[keyof typeof PAYMENT_STATE]> = [PAYMENT_STATE.CARD_NICKNAME_REGISTRATION, PAYMENT_STATE.CARD_NICKNAME_SUBMITTING,]

if (step2ConditionList.includes(paymentsMachine.value)) {
  return <></>
}
```

카드리스트 페이지에 대한 동작은 훅으로 캡슐화 했습니다. (usePaymentCardList.ts) 제가 작성한 editCard 보면 머신에 요청을 보내고 성공 여부와 상관없이 페이지를 이동시키고 있는데 사이드 이펙트를 어떻게 처리하면 좋을지 xState가 익숙치 않아서 좋은 방법을 모르겠네요 😅 
send가 완료 됐을때 처리 결과로 navigate 동작을 처리하고 싶은데 send가 반환값이 없어서 그렇게 할 수도 없고 useEffect로 처리할 땐 현재 상태로 비교하여 navigate할 수 있을것 같은데 해당 상태만 되면 페이지를 전환시켜 버려서 원하는대로 동작이 안되더라구요 ㅎㅎ;
```ts
const editCard = (item: CardItem) => {
  paymentActorRef.send({ type: 'EDIT_CARD', value: item })
  navigate('/payments/cards/new')
}
```

xState vscode가 상태를 정의한 변수를 머신이 정의된 파일 밖으로 뺄 경우 비쥬얼라이제이션이 정상 동작 안하더라구요 ㅋㅋ; 당황했습니다. 😵‍💫
``` ts
// payments.machine.ts
export enum PAYMENT_STATE {}
export const paymentsMachine = setup({}).createMachine({})  ✅
```

``` ts
// payments.const.ts
export enum PAYMENT_STATE {}

// payments.machine.ts
import {PAYMENT_STATE} from './payments.const.ts'
export const paymentsMachine = setup({}).createMachine({})  ❌
```

2024-03-24 17:10 UTC, yujo11 commented on src/features/payments/Card/Card.tsx
> +Card.CardCompany = (props: CardCompanyProps) => {
>좀 더 큰 단위의 컴포넌트를 만들땐 props가 추가되는 경우가 종종 있는데 props가 추가됨에 따른 변경을 최소화하기 위해서 되도록 구조분해할당을 하지 않으려 합니다. 또한 props로 내려온 값을 명확하게 알 수 있어서 컴포넌트 내부 변수와 구분되는 점에서 가독성도 더 좋은것 같구요 😁

오 이런 관점으로는 생각해보지 못 했는데 이런 부분에서는 확실히 장점이 있겠네요 하나 배워갑니다 👍 👍 👍 

ps. 저는 구조분해할당을 하면 lint를 통해 사용하지 않는 변수에 대한 힌트를 받을 수 있어서 구조분해할당을 선호하는 편입니다 ㅎㅎ

2024-03-24 17:47 UTC, yujo11 approved these changes
안녕하세요 재영님~

이전 리뷰 때도 느꼈지만 코드를 깔끔하게 잘 작성하시네요 👍 👍 👍 

작업하시면서 어떤 부분에 중점을 두고 진행하셨는지 정리해주신 덕분에 코드의 의도를 파악하기도 훨씬 좋았고, 작업 내용이 커밋 단위로 잘 나뉘어있어 이전 리뷰 이후 어떤 부분들이 변경되었는지도 커밋을 따라가며 보기 좋았습니다 👍 👍 


>경로가 /domain/vendor/varehouse-list 하위에 각각의 폴더로 api, components, page, types를 만드셨는데 그렇다면 /domain/vendor/varehouse-list 해당 주소가 url을 따라가는 주소인지 궁금합니다. 만약 url을 따라가는 구조라면 상세 주소의 경우 /domain/vendor/varehouse-list/[id]와 같은 형식일 수 있다고 생각하는데 해당 폴더 하위에 똑같이 api, components, page, types구조를 만들게 되는것인지 궁금합니다

상황에 따라 다르겠지만 기본적으로는 url(domain)을 따라가는 주소로 보통 명명하고 있습니다 상세 페이지가 나뉜다면 이 역시 경우에 따라 다르겠지만 보통은 아래와 같은 형식을 많이 사용하고 있습니다!

```
.
└── src
    └── domain
        └── vendor
            └── warehouse-list
                ├── api
                │   └── warehouse-list.api.ts
                ├── components
                │   └── SearchPanel
                │       ├── SearchPanel.tsx
                │       ├── SearchPanle.styled.tsx
                │       └── index.ts
                ├── page
                │   └── WarehouseListPage
                │       ├── WarehouseListPage.tsx  // init 지점이 되는 페이지
                │       ├── WarehouseDetailPage.tsx  or [id].tsx// 상세페이지
                │       └── index.ts
                └── types
                    └── warehouse-list.type.ts
```

>추가로 배럴파일로 만드신 이유도 알고 싶습니다!

배럴파일을 만드는건 제가 개인적으로 선호하는 방법인데요. 이 부분은 import 문을 깔끔하게 유지하고 파일을 찾기 쉽게 하기 위해서 선택했던 방법입니다. 폴더 밑에 `index` 파일을 두는 것도 방법이지만(ex - `components/SearchPanel/index.tsx`) `index`라는 파일을 여러개 열게 되면 IDE에 같은 이름의 tab이 여러개 생기기도 하고 특정 경로를 검색하는 것보다 파일명을 검색하는게 탐색하기 좋다고 생각했습니다. 

<img width="1000" alt="image" src="https://github.com/next-step/react-payments/assets/61097373/8d81ee54-bf79-4706-9a48-5a5f1b32025c">

이 부분은 취향이 많이 나뉘는 부분으로 알고 있는데요.(팀 내에서 폴더 구조를 정할 때 가장 뜨거웠던 부분이기도 하구요) 최근에 [자바스크립트 에코시스템의 속도 향상 - 배럴(Barrel) 파일의 대실패](https://github.com/yeonjuan/dev-blog/blob/master/JavaScript/speeding-up-the-javascript-ecosystem-the-barrel-file-debacle.md#%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%97%90%EC%BD%94%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EC%86%8D%EB%8F%84-%ED%96%A5%EC%83%81---%EB%B0%B0%EB%9F%B4barrel-%ED%8C%8C%EC%9D%BC%EC%9D%98-%EB%8C%80%EC%8B%A4%ED%8C%A8)라는 글을 읽고 고민을 하긴 했으나 아직은 관성적으로 유지하고 있는 부분이기도 합니다 😅

이 부분에 대해서 재영님은 어떻게 생각하고 계신지도 궁금하네요 ㅎㅎ

---

xState 사용에 대한 부분은 저도 능숙치 않아서 재영님의 코드를 보면서 많이 배워가고 있는데요. 비쥬얼라이제이션이 안 되는 부분은 정말 당황할만하네요 ㅋㅋㅋㅋ

이번 step은 여기서 이만 머지하고 다음 step으로 넘어가시면 좋을거 같네요! 다음 리뷰 때는 저도 xState와 더 친해져서 관련해서 도움을 드릴 수 있도록 노력해보겠습니다! 🔥 🔥 🔥

고생 많으셨습니다 재영님! 👍 👍 👍

2024-03-24 17:47 UTC, yujo11 commented on src/service/payments/payments.machine.ts
> +      }
꼼꼼한 예외처리 좋네용 👍 👍 👍

2024-03-24 17:47 UTC, yujo11 commented on src/service/payments/payments.machine.ts
> +        window.localStorage.getItem(LOCAL_STORAGE_KEY_LIST.CARD_INFO) || '[]'
`getItem()`을 실행할 때 key에 해당하는 값이 없다면 null을 반환하기 때문에 여기는 OR 연산자 대신 널 병합 연산자를 사용하는게 더 적절할거 같다는 생각이 드네용

2024-03-24 17:47 UTC, yujo11 commented on src/service/payments/usePaymentCardList.ts
> +  }
이 로직을 useEffect에 담고 `cardList`를 상태로 관리한다면 이후 `cardList`를 사용하는 곳에서 타입이 올바르게 추론되어 사용하기 편할거 같다는 생각이 드네요

ex)
```ts
const [cardList, setCardList] = useState<Array<CardItem>>([])

useEffect(() => {
    const cardList = JSON.parse(window.localStorage.getItem(LOCAL_STORAGE_KEY_LIST.CARD_INFO) || '[]')

  if (!Array.isArray(cardList)) {
    throw new Error('cardList must be an array')
  }

  setCardList(cardList)
}, [])
```

2024-03-24 17:47 UTC, yujo11 commented on src/service/payments/payments.machine.ts
> +}
enum을 통해 상수값으로 관리되니 다른 곳에서도 쉽게 가져다 사용할 수 있어 좋네요 👍 👍 👍

2024-03-24 17:47 UTC, yujo11 commented on src/service/payments/usePaymentCardList.ts
>      }
커밋 단위로 변경 된 코드를 쫓아가고 있었는데 불변성에 대한 코멘트를 남길까말까 했던 부분에서 불변성에 신경 쓴 코드를 작성해주셨군요 ㅎㅎ 👍 👍 👍

2024-03-24 17:47 UTC, merged

2024-03-25 11:33 UTC, SaeWooKKang commented on src/features/payments/Card/Card.tsx
> +Card.CardCompany = (props: CardCompanyProps) => {
> ps. 저는 구조분해할당을 하면 lint를 통해 사용하지 않는 변수에 대한 힌트를 받을 수 있어서 구조분해할당을 선호하는 편입니다 ㅎㅎ

오 그런 장점도 있겠네요!

2024-03-25 12:38 UTC, SaeWooKKang commented
남겨주신 리뷰 꼼꼼하게 읽어보았습니다. 감사합니다! 😊

> 이 부분은 취향이 많이 나뉘는 부분으로 알고 있는데요.(팀 내에서 폴더 구조를 정할 때 가장 뜨거웠던 부분이기도 하구요) 최근에 [자바스크립트 에코시스템의 속도 향상 - 배럴(Barrel) 파일의 대실패](https://github.com/yeonjuan/dev-blog/blob/master/JavaScript/speeding-up-the-javascript-ecosystem-the-barrel-file-debacle.md#%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%97%90%EC%BD%94%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EC%86%8D%EB%8F%84-%ED%96%A5%EC%83%81---%EB%B0%B0%EB%9F%B4barrel-%ED%8C%8C%EC%9D%BC%EC%9D%98-%EB%8C%80%EC%8B%A4%ED%8C%A8)라는 글을 읽고 고민을 하긴 했으나 아직은 관성적으로 유지하고 있는 부분이기도 합니다 😅
이 부분에 대해서 재영님은 어떻게 생각하고 계신지도 궁금하네요 ㅎㅎ

저는 단순히 취향차이 일거라고 생각했는데 해당 글을 읽어보니 런타임에는 전혀 문제가 없지만, DX와 배포시 테스트를 진행한다면 배포가 오래걸릴 수 있는 문제가 있을 수 있겠네요! 저는 유저 경험도 중요하지만 DX 또한 정말 중요한 것 같아요. 개발할 때 컴퓨터가 느리면 답~답 하더라구요 🤯
입사 초반에 집에서 m1을 쓰다가 회사에서 인텔맥을 쓰면서 역체감이 너무 느껴졌었거든요 ㅎㅎ (물론 추후 변경해 주셨습니다.) 노트북 변경전 CRA 프로젝트를  Vite로 팀원분이 마이그레이션 작업을 해주셨는데 HMR 속도차이가 몸으로 느껴지더라구요. 소프트웨어로 하드웨어를 극복했었던.. 경험도 재밌고 툴을 잘 활용하는것도 굉장히 중요하구나를 느꼇었습니다. 😄