[클린코드 리액트 3기 김대현] 페이먼츠 미션 Step3
next-step/react-payments pull request #160
Opened 2024-03-21 19:10 UTC by pengooseDev

# 변경사항

### 유효성 검증

- [x] 유효성 검증 실패에 대한 UI/UX 추가
- [x] 유효한 값 입력시 다음 필드로 Input Focusing

### 카드

- [x] 카드사를 선택하지 않아도 모달을 닫을 수 있다.
- [x] 카드사가 선택되고 유효한 카드 번호 16자리를 모두 입력하면, 자동으로 만료일로 focus된다.
- [x] 별칭 수정 가능

가상 키보드를 구현했지만, 현재 commit에 추가하지 않았습니다.
useForm 적용할 것인지, 적용한다면 onChange 로직을 어떻게 동기화 할 것인지에 대한 고민이 끝나지 않았기 때문입니다.

고민을 진행하고 혹시 좋은 해결책이 생각난다면 commit을 추가하겠습니다! :)

2024-03-24 15:19 UTC, Tanney-102 requested changes
안녕하세요 대현님!! 리뷰가 많이 늦었네요🥲
끝까지 고생 많으셨습니다!
몇가지 궁금한 점들 남겨두었습니다!

2024-03-24 15:19 UTC, Tanney-102 commented on src/pages/Payments/funnel/AddCard.tsx
>    const values = formMethods.values as unknown as CardData;
지난 리뷰 때 이 부분을 놓친 것 같네요..! as를 사용하지 않고 values를 타입핑할 수는 없었을까요?

2024-03-24 15:19 UTC, Tanney-102 commented on src/components/modal/atom/Modalitem.tsx
> +      />
'dot'이라는 요소가 항상 들어가야 하나요~?
컴포넌트가 atom/ModalItem인 것에 비해 조금 덜 유연해보여요!
차라리 'leftContent' 같은 prop을 받아서 넣어주면 어떨까요?

```ts
interface ModalItemProps extends React.PropsWithChildren {
  name: string
  leftContent?: React.ReactNode
}

export const ModalItem = ({ name, leftContent }: ModalItemProps) => {
  return (
    <div>
      { leftContent }
      <span>{ name }</span>
    </div>
  )
}
```

2024-03-24 15:19 UTC, Tanney-102 commented on src/components/modal/ModalPortal.tsx
> +  const root = document.getElementById('modal-root');
root도 prop으로 받으면 더 유연할 듯 합니다.

2024-03-24 15:19 UTC, Tanney-102 commented on src/components/input/molecules/card/securityCode/SecurityCode.tsx
> +  fields,
오 이 컴포넌트는 'SecurityCode' 로 특정 필드에 대한 input을 다루고 있는데 field를 prop으로 받을 필요가 있었나요?

2024-03-24 15:19 UTC, Tanney-102 commented on src/components/input/molecules/card/password/Password.tsx
> +      </Input.Title>
input title, error 등 반복되는 레이아웃이 있는 듯 해요 이걸 다른 컴포넌트로 분리해볼 수도 있을 것 같습니다!

2024-03-24 15:19 UTC, Tanney-102 commented on src/components/input/molecules/card/company/Company.tsx
> +          <ModalItem key={key} color={value.color} name={value.name} />
결론적으로 모달 안에 렌더되긴 하지만 ModalItem이라기엔 그냥 카드사 선택을 위한 UI정도로 이해되어요..! 다른 이름을 고려해보셔도 좋을듯 합니다.

2024-03-30 13:29 UTC, pengooseDev commented on src/pages/Payments/funnel/AddCard.tsx
>    const values = formMethods.values as unknown as CardData;
useForm 사용처에서 제네릭타입을 주입한 뒤,
```ts
export const useForm = <T extends object>() => {
  // ...codes
```

아래와 같이 타입을 할당하였습니다. :)
```ts

  const getValues = useCallback(() => {
    return Object.keys(fieldsRef.current).reduce((valuesAcc, name) => {
      const field = fieldsRef.current[name];

      valuesAcc[name as keyof T] = field.value as T[keyof T];

      return valuesAcc;
    }, {} as Values<T>);
  }, []);
```

```ts
export type Values<T> = {
  [K in keyof T]: T[K];
};
```

2024-03-30 14:02 UTC, pengooseDev commented on src/components/modal/atom/Modalitem.tsx
> +      />
분리하였습니다! :)

```ts
          <ModalItem
            key={key}
            name={value.name}
            topContent={<Dot color={value.color} />}
          />
  ```

2024-03-30 14:11 UTC, pengooseDev commented on src/components/input/molecules/card/company/Company.tsx
> +          <ModalItem key={key} color={value.color} name={value.name} />
직접 이름을 바꾸기엔 modal molcule에 Company 도메인이 섞이는 것 같아, 사용처에서 atom 컴포넌트를 하나 만들어 추가하였습니다! :)

```tsx
import { Dot } from '@/components/common/Dot';
import { ModalItem } from '@/components/modal/atom/ModalItem';

interface CompanyOptionProps {
  name: string;
  color: string;
}

export const CompanyOption = ({ name, color }: CompanyOptionProps) => {
  return <ModalItem name={name} topContent={<Dot color={color} />} />;
};
```

```tsx
<CompanyOption name={value.name} color={value.color} />
```

2024-03-30 14:25 UTC, pengooseDev commented on src/components/modal/ModalPortal.tsx
> +  const root = document.getElementById('modal-root');
Layout 컴포넌트랑 합치니까 엄청 유연해졌습니다! 🥳👍 감사합니다!

```ts
export const ModalPortal = ({ children, rootId }: ModalPortalProps) => {
  const root = document.getElementById(rootId || 'modal-root'); // ⛳️

  if (!root) return null;

  return ReactDom.createPortal(children, root);
};
```

```ts
export const GlobalLayout = ({ type, children }: GlobalLayoutProps) => {
  // ...codes 

  return (
    <main className={rootStyle} id={rootId}> // ⛳️
      <div className={appStyle}>{children}</div>
    </main>
  );
};
```

```tsx
const ModalContainer = ({
// ... codes
  return (
    <ModalPortal rootId={LAYOUT.ROOT_ID.MOBILE}> // ⛳️
       // ...codes
    </ModalPortal>
  );
};
```

2024-03-30 14:54 UTC, pengooseDev commented on src/components/input/molecules/card/securityCode/SecurityCode.tsx
> +  fields,
생각해보니 그렇네요. 기억을 더듬어보니, 전에 모든 Input에 대해 autoFocus를 핸들링한다고 저렇게 propsDrilling이 발생했던걸로 기억하는데, 피드백주신 useAutoFocus 로직 분리로 의존성이 사라졌던걸 캐치하지 못했던 것 같습니다 :)

깔끔하게 걷어냈습니다 감사합니다! 😊

```ts
        <CardInput.Number
          formMethods={formMethods}
          autoFocusMethods={autoFocusMethods}
        />
        <CardInput.ExpireDate
          formMethods={formMethods}
          autoFocusMethods={autoFocusMethods}
        />
        // ... codes
```

```tsx

export const CardNumber = ({
  formMethods,
  autoFocusMethods,
}: CardInputProps) => {
  const { register, errors } = formMethods;
  const { autoFocusRefs, handleAutoFocus } = autoFocusMethods;

  const fieldKeys = Object.values(CARD_NUMBER.FIELDS).map(({ name }) => name);
  const fieldsFulfilled = Object.values(fieldKeys).map((key) => !errors[key]);
  // ...codes  

```

2024-03-30 15:36 UTC, pengooseDev commented on src/components/input/molecules/card/password/Password.tsx
> +      </Input.Title>
Input의 Atom 컴포넌트들 이용해 Header 컴포넌트를 추가하였습니다! :)

```tsx
import { Input } from '../Input';

interface InputHeaderProps {
  title?: string;
  errorMessage?: string;
  hasError?: boolean;
}

export const InputHeader = ({
  title,
  errorMessage,
  hasError,
}: InputHeaderProps) => {
  return (
    <Input.Title>
      <span>{title}</span>
      {errorMessage && (
        <Input.Error errorMessage={errorMessage} hasError={hasError || false} />
      )}
    </Input.Title>
  );
};
```

```tsx
      <Input.Header
        title={EXPIRE_DATE.TITLE}
        hasError={fieldErrors.length > 0}
        errorMessage={errorMessage}
      />
```

2024-04-01 15:15 UTC, Tanney-102 approved these changes
안녕하세요 대현님~! 
끝까지 리뷰 반영하시느라 고생하셨습니다!
더욱 유연한 컴포넌트들이 된 듯 하여 기분이 좋네요! ㅎㅎ
이번 미션 여기서 마무리 하면 될 듯 합니다! 고생 많으셨어요~!

2024-04-01 15:15 UTC, merged

2024-04-01 15:18 UTC, pengooseDev commented
1달 동안 감사했습니다! :) 행복한 봄 되시길 바랍니다! 😆