[클린코드 리액트 1기 이영범] 페이먼츠 미션 Step1
next-step/react-payments pull request #17
Opened 2022-01-23 15:17 UTC by youngbeomrhee

안녕하세요 리뷰어님 react-payment Step1 리뷰요청 드립니다
2번 이상 반복되는 영역은 모두 컴포넌트로 분리했습니다
Storybook이 처음이라 제대로 구현한건지 모르겠네요... 관련해서 특히나 많은 피드백 부탁 드립니다

[데모](https://youngbeomrhee.github.io/react-payments/)  

[코드](https://github.dev/youngbeomrhee/react-payments/tree/youngbeomrhee/)  

[스토리북](https://61ed6be799d45c004a58df91-bkarlzcztr.chromatic.com/?path=/story/card--default/)

2022-01-25 04:53 UTC, glassyi commented on src/App.js
> +  const [status, setStatus] = useState('list');
setStatus를 호출하는 쪽에서 setStatus라는 이름으로는 어떤 상태를 변경하는지 바로 알기가 힘들어서, setRoute 나 setRouteStatus 같이 좀 더 알기 쉽게 변경하는건 어떠신가요?

2022-01-25 05:02 UTC, glassyi commented on src/pages/CardList.js
> +          <Card key={uuid()} card={card} />
key 에 uuid를 쓰신게 인상적이네요! 👍

2022-01-25 05:11 UTC, glassyi commented on src/pages/Complete.js
> +        <div className="input-container flex-center w-100">
만들어두신 Input container 컴포넌트를 재사용할 수 있을 것 같은데 어떠신가요?
기존 Input container에 title 유무처리와 className Props 추가를 하면 가능할 것 같아 보입니다. 🙂

2022-01-25 05:20 UTC, glassyi commented on src/pages/Complete.js
> +        <Card />
올려주신 완료 페이지의 Card 컴포넌트는 small 사이즈 카드이네요. 디자인과 마크업 페이지에서는 big 사이즈 카드 디자인이더라구요. Card 컴포넌트의 big 사이즈 추가와 기존 만드신 card 컴포넌트에서 어떤식으로 분리 또는 추가하는게 좋을지 고민해보시면 좋을 것 같습니다!

2022-01-25 05:44 UTC, glassyi commented on src/components/CardInputForm.js
> +        setCardHolerInfo(`입력글자수 : ${value.length} / 30`);
```js
if (value === '') {
        setCardHolerInfo('');
      } else {
        setCardHolerInfo(`입력글자수 : ${value.length} / 30`);
```
현재 키와 맵핑되는 값을 없데이트 하는 역할과 입력글자수 내용을 업데이트하는 역할을 분리하는게 어떨까요?

입력글자수 메세지를 나타내는 위 코드를 92번째 라인으로 옮기면 setCardHolerInfo를 쓰지 않아도 분리 시킬 수 있을 것 같아요.

2022-01-25 05:48 UTC, glassyi commented on src/components/EmptyCard.js
> +export default EmptyCard;
EmptyCard가 storybook에만 보이고 전체 코드에선 쓰이진 않는것 같은데 맞나요?

2022-01-25 10:46 UTC, glassyi requested changes
영범님 안녕하세요! 
전체적으로 간결하게 코드 작성해 주셨네요👍  미리 context api로 작성하셔서 그 부분은 제외하고 
제가 코멘트 할 수 있는 부분들 위주로 확인했습니다!

Storybook에서는 구성하신 stories에 title에 `/`구분 기호를 사용해서 좀 더 그룹핑하시면 어떨까 첨언드려요.
실제 component와 page들이 스토리북 페이지 상에서 한 뎁스에 있어서 "compnents/*", "pages/*" 이런식으로 좀 더 그룹핑하면 더 명확해질 것 같습니다.

그리고 각 컴포넌트 요소들이 context api로 state를 참조하고 있다보니 스토리북에서 controls로 볼 수가 없더라구요. 스토리북의 controls로 직접 제어해서 컴포넌트가 변경되는걸 확인할 수 있는 이점을 살리면서 기존 작성하신 코드를 유지할 수 있는 방법이 무엇이 있을지 좀 찾아봐야 할 것 같아요.

또 덧붙이자면 components 폴더 하위에 있는 card 요소들과 page title 도 modal, nav 폴더처럼 일관성있게 폴더 구조를 가지는게 어떨까합니다 🙂  다른 의도가 있으셨다면 답변 부탁드려요!

고생 많으셨습니다 👍

2022-01-25 12:59 UTC, hyoungnam commented on src/pages/CardList.js
> +          <Card key={uuid()} card={card} />
<img width="1574" alt="스크린샷 2022-01-25 오후 9 55 46" src="https://user-images.githubusercontent.com/19677717/150980777-f90f64fa-3157-4c2b-a04c-594a17074c30.png">
uuid와 비슷한 nanoid 라이브러리 예시입니다. 
렌더링할때마다 key uuid() **함수 호출**을 하게되면 재조정(reconciliation) 할때 key 비교를 통한  장점을 잃어버립니다. card  데이터 를 최초 생성할때  uuid값을 넣어주고 활용하는게 좋을듯 합니다.
```suggestion
          <Card key={card.id} card={card} />
```

2022-01-25 13:04 UTC, hyoungnam commented on src/pages/CardList.js
> +          <Card key={uuid()} card={card} />
https://ko.reactjs.org/docs/reconciliation.html#recursing-on-children
<img width="1317" alt="스크린샷 2022-01-25 오후 10 04 14" src="https://user-images.githubusercontent.com/19677717/150982043-80a8731b-7762-43ee-ac76-b89c8883fba3.png">

2022-01-26 06:48 UTC, glassyi commented on src/pages/CardList.js
> +          <Card key={uuid()} card={card} />
아~ 내용 공유해주셔서 감사합니다! @hyoungnam

2022-01-27 15:07 UTC, youngbeomrhee commented on src/App.js
> +  const [status, setStatus] = useState('list');
예 헷갈릴 수 있겠네요 좋은 의견 감사합니다 반영하여 수정하겠습니다

2022-01-27 15:38 UTC, youngbeomrhee commented on src/pages/CardList.js
> +          <Card key={uuid()} card={card} />
@hyoungnam 좋은 지적 감사합니다 
key의 최적화와 관련해서 착각하고 있던 부분이 있었네요
의견주신 내용 토대로 일부 변경하도록 하겠습니다

2022-01-27 15:41 UTC, youngbeomrhee commented on src/pages/Complete.js
> +        <div className="input-container flex-center w-100">
해당 부분도 고민을 했었는데요
일면 유사해 보이지만 공통화 하기에는 예외 상황이 많아서 전혀 다른 컴포넌트로 판단했습니다
실무에서라면 이후에 유사한 컴포넌트가 계속 반복된다면 공통화하게 될 것 같아요

2022-01-27 15:42 UTC, youngbeomrhee commented on src/pages/Complete.js
> +        <Card />
예 말씀주신대로 아직 카드를 사이즈별, 상태별로 분리는 안했습니다 
이 부분은 2차 리뷰때 반영하도록 하겠습니다

2022-01-27 15:50 UTC, youngbeomrhee commented on src/components/CardInputForm.js
> +        setCardHolerInfo(`입력글자수 : ${value.length} / 30`);
이 부분은 input에 대한 입력값을 받아서 그 값의 변경에 따라 다른 dom의 정보를 업데이트하는 로직이라 그렇게 단순히 로직을 옮기는 정도로는 해소가 어려울 것 같아요

2022-01-27 15:50 UTC, youngbeomrhee commented on src/components/EmptyCard.js
> +export default EmptyCard;
예 맞습니다^^; 이 부분은 아직 빈 카드와 싸이즈별 카드 부분을 명확히 구현하지 않아서 그렇고요
위에서 카드 관련해서 피드백 주신 내용 포함해서 2차에서 구현하도록 하겠습니다

2022-01-27 16:32 UTC, youngbeomrhee commented
@glassyi 유리님 안녕하세요 꼼꼼한 피드백 감사 드립니다
피드백 주신 내용 반영하여 다시 리뷰요청 드립니다
확인 부탁 드립니다 :)

2022-01-27 18:12 UTC, glassyi commented on src/components/CardInputForm.js
> +        setCardHolerInfo(`입력글자수 : ${value.length} / 30`);
아~ 단순 코드를 옮긴다기 보다는, cardholder 입력값이 setInputCard로 업데이트 되고 dom에 렌더 되는 시점에 inputCard.cardholder의 value도 업데이트된 값으로 반영이 될 것이기 때문에 그러한 이유로 입력 글자수를 반영하는 `입력글자수 : ${value.length} / 30`를 jsx 영역에 옮겨도 무방하지 않나 하는 의미로 말씀드린거에요~ 🙂

2022-01-27 18:13 UTC, glassyi commented on src/pages/Complete.js
> +        <Card />
넵! 👍

2022-01-27 18:13 UTC, glassyi commented on src/pages/Complete.js
> +        <div className="input-container flex-center w-100">
🙆‍♀️

2022-01-27 18:16 UTC, glassyi approved these changes
고생하셨습니다. 🙇‍♀️ 스텝2에서 뵐게요!

2022-01-27 18:17 UTC, merged