[클린코드 리액트 1기 이상우] 페이먼츠 미션 Step 1
next-step/react-payments pull request #22
Opened 2022-01-26 17:04 UTC by lsw1164

오랜만이라 초기 환경설정이랑 CI/CD에서 시간을 많이 썼네요 ㅠ
리뷰 잘부탁드립니다 :)

## 데모

[바로가기](https://lsw1164.github.io/react-payments/)

## 웹 vscode 환경

[바로가기](https://github.dev/lsw1164/react-payments)

## 스토리북
[바로가기](https://61efd5311665cd0042886870-bxiddzqrbh.chromatic.com/)

## 📝 Requirements

### 필수 요구사항
- [x] Storybook 상호 작용 테스트
- [x] 재사용 가능한 Component 작성

### 카드 추가

- [x] <(뒤로가기) 버튼 클릭 시, 카드 목록 페이지로 이동한다.

- [x] 카드 번호를 입력 받을 수 있다.
  - [x] 카드 번호는 숫자만 입력가능하다.
  - [x] 카드 번호 4자리마다 -가 삽입된다.
  - [x] 카드 번호는 실시간으로 카드 UI에 반영된다.
  - [x] 카드 번호는 앞 8자리만 숫자로 보여지고, 나머지 숫자는 *로 보여진다.

- [x] 만료일을 입력 받을 수 있다.
  - [x] MM / YY 로 placeholder를 적용한다.
  - [x] 월, 년 사이에 자동으로 /가 삽입된다.
  - [x] 만료일은 실시간으로 카드 UI에 반영된다.
  - [x] 월은 1이상 12이하 숫자여야 한다.

- [x] 보안코드를 입력 받을 수 있다.
  - [x] 보안코드는 *으로 보여진다.
  - [x] 보안코드는 숫자만 입력가능하다.

- [x] 카드 비밀번호의 앞 2자리를 입력 받을 수 있다.
  - [x] 카드 비밀번호는 각 폼마다 한자리 숫자만 입력가능하다.
  - [x] 카드 번호 입력 시, *으로 보여진다.

- [x] 카드 소유자 이름을 입력 받을 수 있다.
  - [x] 이름은 30자리까지 입력할 수 있다.
  - [x] 이름 입력 폼 위에, 현재 입력 자릿수와 최대 입력 자릿수를 실시간으로 보여준다.

- [x] 카드 추가 완료 시, 카드 등록 완료 페이지로 이동한다.

### 심화 요구사항 (선택사항)
- [ ] Storybook 단위 테스트
- [ ] 유효성 검증 실패에 대한 UI/UX 추가
- [ ] 유효한 값 입력시 다음 필드로 Input Focusing
- [ ] 카드사 선택
  - [ ] 카드 번호 앞 8자리로 카드사를 추정하여 그 테마를 카드 UI에 반영한다.
  - [ ] 카드사를 선택하지 않아도 모달을 닫을 수 있다.
  - [ ] 카드사가 선택되고 유효한 카드 번호 16자리를 모두 입력하면, 자동으로 만료일로 focus된다.
- [ ] 보안코드 툴팁
  - [ ] 클릭 시, 보안코드 관련 안내 메시지를 보여준다.
  - [ ] focusout 시, 툴팁이 닫힌다.
- [ ] 가상 키보드
  - [ ] 마스킹 처리된 값 입력시 사용
  - [ ] 숫자를 랜덤으로 배열

2022-01-30 18:55 UTC, ppamppamman requested changes
상우님 안녕하세요! 이번에 리뷰를 진행한 유재욱입니다.
개인사정이 있었음에도 양해해주셔서 다시 한 번 감사드립니다.

리뷰를 하면서 저도 많이 배우는 것 같습니다.
CI/CD까지 깃헙 액션으로 설정해주셔서 스니펫 줍줍해갑니다 :)

상우님께서 구현하셨던 내용 중 놓치신 것 같은 부분에 초점을 맞춰 리뷰를 진행해보려고 노력했습니다.
부족한 리뷰입니다만, 잘부탁드립니다. 더불어 리뷰가 충분히 구체적이지 못하여 궁금하신 내용이 생기시거나 의견이 있으시다면 가감없이 코멘트 남겨주세요!

아래는 공통적으로 드릴 수 있는 간단한 코멘트입니다.
- CRA의 기본으로 함께 만들어지는 reportWebVitals와 같은 파일들은 만약 활용하지 않는다면 지워주셔도 괜찮을 것 같습니다.
- common/constants.ts 에서 일부는 잘 정리가 되었지만, 일부는 한 파일에서 그대로 타입선언을 하시고 활용하신 것 같습니다. 하나의 파일에서만 활용되어 common하지 않은데도 들어가있는 타입들이 있으니 참고해주시면 감사드리겠습니다.
- UI/UX적인 측면에서 디테일을 추가해드리자면, 카드 input의 경우 필드가 완성되면 다음필드로 자동으로 넘어가서 다음 필드값을 자연스럽게 추가할 수 있는 형태는 어떨까 싶습니다.

step1 구현 고생하셨습니다! step2 구현 때 뵙겠습니다 :D

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/AddCardForm.tsx
> +  );
- `<Card>`는 cardData에 따라 단지 디스플레이를 위한 컴포넌트인 것 같은데 폼으로 감싸져서 관리되어야하는 다른 이유가 있을까요?
- 렌더에 필요한 cardData가 해당 `<Form>` 컴포넌트에서 다뤄지고 있어서 `<Card>`라는 컴포넌트를 어쩔 수 없이 해당 컴포넌트의 자식요소로 구현한 것으로 보입니다. step2에서 cardData를 전역객체로 관리하게 된다면, 컴포넌트의 관심사 분리가 적절하게 이뤄질 수 있을 것 같습니다.

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/CardNumberInput.tsx
> +        ))}
- map 함수의 인자로 쓰고 계시는 carNumInputState 변수명에 오타가 있는 것으로 보여집니다.
- 이번 프로젝트에 대해서는 useInput을 여러번 호출하는 것을 통해 inputState의 어레이로써 각 input 데이터의 순서를 고정하여 활용하셨군요. key값으로 활용할만한 stable한 id값이 필요없도록 구현하신 것이 의도로 보여지는데 제 생각이 맞는지 궁금합니다.
  - 만약 그런것이 아니라면 해당 리뷰가 도움이 될 수 있을 것 같습니다. list로부터 렌더링을 시도할 때 key를 list의 인덱스로 지정하게 되면 cardNumInputStateList의 element의 고유한 식별값이 아닌 list의 순서에 의존성이 생기게 됩니다. 이에 따라 리렌더링을 하지 않아도 되는, 같은 값을 지닌 컴포넌트일지라도 인덱스에 변화가 주어진다면 리렌더링을 시도하게 될 것 입니다. 
  - 따라서 안정적으로 사용 가능한 유니크한 값이 있다면, 인덱스 대신 사용하시는 것이 좋을 것 같습니다. 리액트 공식 문서에 해당 부분이 잘 나와 있어서 링크전달드립니다 :)
https://ko.reactjs.org/docs/lists-and-keys.html#keys

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/CardOwnerNameInput.tsx
> +  });
카드 소유자 이름 부분에는 `이름 성`의 포맷으로 작성한다고 생각합니다. 
다만, AlphabetRegex에서 띄어쓰기를 허용하지 않고 있네요. `/^[a-zA-Z\s]+$/`정도로 정리해볼 수 있을 것 같습니다.

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/AddCardForm.tsx
> +  };
기본 form의 onSubmit을 오버라이딩해서 핸들링하시기 위해 작성한 함수라면 함수명을 handleSubmit 정도로 작성하는건 어떨까요?

2022-01-30 18:55 UTC, ppamppamman commented on src/hooks/useInput.ts
> +};
- 참 잘 구성된 커스텀훅이라 생각합니다! 재사용 가능하고, 각각의 변수가 지칭하는 내용도 뚜렷하다고 생각합니다. 다만, 이렇게 처리가되면 모든 input 컴포넌트의 값이 controlled하게 처리되어 step2의 uncontrolled component로 개선하실 때 약간 까다로울 수 있겠다는 생각이 듭니다.

- 지금은 useInput의 영향으로 한번 input의 업데이트에 의한 렌더링이 발생하고, 각 컴포넌트의 useEffect로부터 props.onChangeInputState의 영향을 받아 리렌더링이 또 전체적으로 되는 구조네요. 리렌더링이 필요 이상으로 발생하는 것 같습니다. step2때는 어떻게 구성될지 궁금합니다 :)

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/AddCardForm.tsx
> +    props?.onSubmit && props.onSubmit(e);
여기서 e를 넘기는 이유는 무엇인가요?

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/SecurityCodeInput.tsx
> +  }, [securityCodeInputState.value]);
- 이부분은 제가 배워야할 것 같아서 여쭙니다! 저는 .call이나 .apply의 첫번째 인자로 null을 넘길 때는 비단 this가 필요없는 경우 뿐만아니라 특정 class의 메소드 중 this 활용이 필요없는 경우에 null을 넘기고는 합니다. this 활용을 하지 않는 함수에서 null을 잡아주면서까지 .call이나 .apply를 사용하지는 않는데 이유가 무엇인가요?
- useInput 커스텀 훅쪽에서도 언급드리겠지만, 이렇게 되면 securityCodeInputState가 변하고 리렌더링이 한차례 일어난 후에야 useEffect를 통해 다시 렌더링을 발생시킵니다. input 컴포넌트 전반적으로 이러한 구조를 띄고 있는데 개선할 수 있는 방법은 없을까요?

2022-01-30 18:55 UTC, ppamppamman commented on src/components/button/AddCardBtn.tsx
> +const AddCardBtn = ({ onClick }: NewCardProps) => {
특정 부분에서는 props로 잡아주셨는데 여기를 포함해 일부 컴포넌트에서는 디스트럭쳐링으로 작업해주셨네요

2022-01-30 18:55 UTC, ppamppamman commented on src/hooks/useInput.ts
> +    }
- 각 input 함수에서 밸리데이터 함수를 구현하여 훅에서 넘겨받아 사용하는 방식은 로직에 대한 적절한 위임이 이뤄진 정말 좋은 방법이라 생각합니다! 덕분에 배웠습니다.
- 다만, 제 생각에 isValid부분은 함수를 받아 계산만해서 return 해줘도 문제는 없을 것 같은데 상태로서 값을 지정해 저장하는 이유가 있을까요?

2022-01-30 18:55 UTC, ppamppamman commented on src/components/card/NormalCard.tsx
> +      {alias ? <span className="card-nickname">{alias}</span> : null}
`alias && <span className="card-nickname">{alias}</span>` 으로도 달성가능할 것 같습니다.

2022-01-30 18:55 UTC, ppamppamman commented on src/components/addCardForm/AddCardForm.tsx
> +import { CardData, CardType } from "@common/constants";
필요한 상수를 모아주셔서 확인하기에 훨씬 수월했습니다 감사합니다!

2022-01-30 19:00 UTC, ppamppamman commented
앗 그리고 여담입니다만, 커밋 프리픽스에 붙은 이모지는 어떤 의미를 가지고 지정하신 건가요??

2022-01-31 05:48 UTC, lsw1164 commented
> 앗 그리고 여담입니다만, 커밋 프리픽스에 붙은 이모지는 어떤 의미를 가지고 지정하신 건가요??

gitmoji를 사용했습니다 :)

https://gitmoji.dev/

https://github.com/carloscuesta/gitmoji

2022-01-31 05:50 UTC, lsw1164 commented on src/components/addCardForm/AddCardForm.tsx
> +  );
말씀하신대로 Card 컴포넌트는 form에 포함되지 않는게 맞겠습니다 피드백 감사합니다 :)

2022-01-31 05:51 UTC, lsw1164 commented on src/components/addCardForm/CardNumberInput.tsx
> +        ))}
고유 id로 작성해야겠군요 링크 감사합니다 👍

2022-01-31 05:53 UTC, lsw1164 commented on src/components/addCardForm/AddCardForm.tsx
> +  };
적절한 네이밍이네요 👍

2022-01-31 06:01 UTC, lsw1164 commented on src/hooks/useInput.ts
> +};
리렌더링까지 고려하지 않았는데 필드가 늘어날수록 불필요한 렌더링이 점점 늘어나는 구조네요.
step2에서 개선해보겠습니다.

2022-01-31 06:04 UTC, lsw1164 commented on src/components/addCardForm/SecurityCodeInput.tsx
> +  }, [securityCodeInputState.value]);
call 메서드는 단순히 옵셔널체이닝과 함께 이벤트를 인보크하려고 사용했습니다만 이렇게 수정할 수 있겠네요.
 
 someInterface.customMethod?.();

2022-01-31 06:06 UTC, lsw1164 commented on src/components/button/AddCardBtn.tsx
> +const AddCardBtn = ({ onClick }: NewCardProps) => {
통일성을 고려하지 않았는데. 추후에 전반적으로 디스트럭쳐링으로 수정하는 것도 좋겠다는 생각이드네요 🤔

2022-01-31 06:07 UTC, lsw1164 commented on src/hooks/useInput.ts
> +    }
isValid 값이 원하는 타이밍에 갱신되지 않아서 useState hook을 사용했습니다.

2022-01-31 06:23 UTC, merged