[클린코드 리액트 1기 전환오] 페이먼츠 미션 Step2
next-step/react-payments pull request #30
Opened 2022-02-03 23:13 UTC by jho2301

안녕하세요 박실님
스텝2 재업합니다!

#23

2022-02-04 05:44 UTC, parksil0 requested changes
스텝2까지 마무리 하느라 수고하셨습니다!
리뷰이지만 오히려 깔끔하게 짜신 코드 보면서 되려 배웠다는 생각이 듭니다..!
리뷰 되어있는 부분 확인해보시면서 변경 할 부분은 변경하시면 될 것 같습니다.

2022-02-04 05:44 UTC, parksil0 commented on src/components/Registration/카드예시.tsx
> +export const 카드예시 = ({ cardForm }: { cardForm: CardForm }) => {
`카드예시.tsx`와 `CardItem.tsx`를 공통으로 하나의 파일을 만드는 방법도 있을텐데, 나누신 이유가 있을까요?

2022-02-04 05:44 UTC, parksil0 commented on src/pages/CardListPage/index.tsx
> +          <span style={{ cursor: 'alias' }} onClick={() => navigate(`/edit?id=${card.id}`)}>
별칭에 `onClick`이벤트를 설정하는 것보다, 카드에 `onClick`이벤트를 설정하는게 더 좋을듯 싶습니다!

2022-02-04 05:44 UTC, parksil0 commented on src/pages/CardRegistrationPage/index.tsx
>            <span className="input-title">카드 번호</span>
카드 번호 사이사이에 `-`구분자를 넣어주는 로직을 모듈화하는 방법도 좋을것 같습니다!

2022-02-04 05:44 UTC, parksil0 commented on src/store/CardContext.tsx
> +    <CardContext.Provider value={{ card, setCard, setNickname }}>{children}</CardContext.Provider>
저는 `setCard`를 각 컴포넌트 또는 페이지에 제공하는 것과, 해당 파일 내에서 `setCard`를 사용하여 함수를 만들어 제공하는 방법을 고민하다가 기존에 사용하던 리덕스를 생각해서 후자를 선택해서 구현했어요.
환오님은 전자의 방법을 선택하신 것 같은데, 이유에 대해서 알 수 있을까요??!

2022-02-04 05:44 UTC, parksil0 commented on src/store/CardContext.tsx
> +    throw Error('card context exception occurred');
예외 설정을 하신 이유에 대해 알수 있을까요?

2022-02-04 13:17 UTC, jho2301 commented on src/components/Registration/카드예시.tsx
> +export const 카드예시 = ({ cardForm }: { cardForm: CardForm }) => {
UI구조는 같지만 사용되는 데이터가 달라서 구분해봤어요!
존재 이유가 다른 컴포넌트이니 분리하는게 변경에 더 강하다고 생각했습니다
다만 컴포넌트 내부에서 사용되는 스타일 및 요소는 공유할 수 있다고 생각해요.
리팩토링을 해본다면 그런 방향으로 진행해볼 것 같습니다

2022-02-04 13:18 UTC, jho2301 commented on src/pages/CardListPage/index.tsx
> +          <span style={{ cursor: 'alias' }} onClick={() => navigate(`/edit?id=${card.id}`)}>
이거는 의도한 UX가 달라서 뭐가 맞고 틀리고는 없는 것 같아요.
제가 의도한 바는 이름을 터치했을때 수정이 되는게 보다 자연스러울 것 같다는 판단에서 였습니다!

2022-02-04 13:19 UTC, jho2301 commented on src/pages/CardRegistrationPage/index.tsx
>            <span className="input-title">카드 번호</span>
유틸화 해보도록 할게요 감사합니다 🙏

2022-02-04 13:27 UTC, jho2301 commented on src/store/CardContext.tsx
> +    <CardContext.Provider value={{ card, setCard, setNickname }}>{children}</CardContext.Provider>
저는 그냥 useState를 사용했기 때문에 setState를 내려준 의식의 흐름이었어요 
기존 상태관리라이브러리에서 찾아보면 recoil이랑 비슷한 사용방법이지 않을까요? 
박실님이 구현하신 방법도 궁금하네요 참고해보도록 하겠습니다!

2022-02-04 13:29 UTC, jho2301 commented on src/store/CardContext.tsx
> +    throw Error('card context exception occurred');
nullish타입 때문이에요 여기서 에러를 던지면 사용하는쪽에서는 null을 고려하지 않고 값을 사용할 수 있게 됩니다

2022-02-04 16:53 UTC, parksil0 commented on src/pages/CardListPage/index.tsx
> +          <span style={{ cursor: 'alias' }} onClick={() => navigate(`/edit?id=${card.id}`)}>
필수 요구사항 중에 '카드를 클릭하면, 카드 별칭 수정(카드 추가 완료 페이지)로 이동한다.' 라고 되어있어 크게 별 생각 없이 리뷰 남겼는데, 환오 님과 같은 접근도 충분히 일리 있네요. 좋은 의견 감사합니다!

2022-02-04 16:58 UTC, parksil0 commented on src/store/CardContext.tsx
> +    <CardContext.Provider value={{ card, setCard, setNickname }}>{children}</CardContext.Provider>
저는 관련 핸들러 함수를 컨텍스트 파일 내에 정의한 것 말고는 없어요 ㅋㅋ.
제가 리덕스 말고는 상태관리 라이브러리를 써본 적이 없어서 recoil이라는 라이브러리 [공식문서](https://recoiljs.org/ko/docs/introduction/core-concepts#selectors) 개요를 잠깐 보고왔습니다.
위에 링크에서처럼 구현하신 거군요. 좋은 인사이트 배워갑니다!ㅎㅎ

2022-02-05 08:28 UTC, jho2301 commented on src/pages/CardRegistrationPage/index.tsx
>            <span className="input-title">카드 번호</span>
[257f3fd](https://github.com/next-step/react-payments/pull/30/commits/257f3fd846db78da612fde196f082b622d23fb2c) 에서 반영해봤어요!

2022-02-05 09:50 UTC, merged

2022-02-05 09:50 UTC, parksil0 commented
수고하셨습니다~!!