[클린코드 리액트 2기 신형기] 페이먼츠 미션 Step 1
next-step/react-payments pull request #49
Opened 2023-02-19 10:30 UTC by hyungkishin

안녕하세요 :) 리뷰어님 

스토리북이 미숙하여 아직 작성에 미숙하여 작성중에 있습니다.
그전에 현재 방향이 맞는지 선 검토 부탁드릴 수 있을까요 :) 
🙇🏻‍♂️ 감사합니다

2023-02-20 16:08 UTC, Tanney-102 requested changes
안녕하세요 형기님~ 리뷰어 오태은입니다.
미션 진행하느라 고생 많으셨어요!
나름의 기준으로 컴포넌트를 재사용성 높게 잘 나눠주신 것 같아요!
몇가지 코멘트 남겨드렸으니 확인 부탁드려요!

그리고 스토리북은 예시 코드만 추가되고 따로 진행되고 있는 테스트는 없는 것 같습니다.
아직 추가하기 전이실까요?

2023-02-20 16:08 UTC, Tanney-102 commented on src/App.tsx
> +      <Route path="/3" element={<AddCardModal />} />
path에 3은 의도적으로 넣으신 걸까요?

2023-02-20 16:08 UTC, Tanney-102 commented on src/components/card/index.tsx
> +    cardExpiry[0] ? `${cardExpiry[0]} / ${cardExpiry[1] || "YY"}` : "MM / YY";
인덱스로 접근하기 보다 의미있는 키를 활용하면 어떨까요?
```js
interface CardExpiry {
  month: string
  year: string
}
const showCardExpiry = (cardExpiry: CardExpiry) => { ... }
```

2023-02-20 16:08 UTC, Tanney-102 commented on src/components/card/index.tsx
> +  };
더 좋은 이름이 있을 것 같습니다.
isHypen은 인자가 하이픈인지 아닌지를 반환하는 함수처럼 느껴져요

2023-02-20 16:08 UTC, Tanney-102 commented on src/components/card/index.tsx
> +    cardExpiry[0] ? `${cardExpiry[0]} / ${cardExpiry[1] || "YY"}` : "MM / YY";
여기 선언된 함수들은 꼭 컴포넌트 안에 있을 필요가 없어보이는데 밖으로 빼면 어떨까요?

2023-02-20 16:08 UTC, Tanney-102 commented on src/components/input/CardForm.tsx
> +  };
이 함수는 어떤 용도 일까요~?

2023-02-20 16:08 UTC, Tanney-102 commented on src/components/input/cardPassword/index.tsx
> +          value="*"
type이 password인데 value를 *로 넣어줄 필요가 있을까요?

2023-02-20 16:08 UTC, Tanney-102 commented on src/pages/RegistPage/AddCardPage.tsx
> +        <CardForm />
선언적으로 잘 작성해주신 것 같습니다~
컴포넌트가 잘 나뉘었네요!

2023-02-20 16:08 UTC, Tanney-102 commented on src/store/Provider.tsx
> +  const [cvc, setCvc] = useState<string>("");
이 Provider로 App 자체를 감싸고 계시던데 그렇게 큰 범위로 정하신 이유가 궁금합니다.
cardNumbers,... 등은 카드 등록 폼과 관련한 상태들인데 해당 페이지들에서만 사용하도록 해도 충분하지 않을까요?

2023-02-20 16:08 UTC, Tanney-102 commented on src/store/Provider.tsx
> +    };
전반적으로 Provider에서 모든 input의 핸들러를 관리하는 것으로 보입니다.
이 Provider가 가지고 있는 관심사를 각 컴포넌트에 잘 나눠주면 어떨까요?
provider에서는 폼 관련 상태와 이를 업데이트 하는 인터페이스만 제공하고 실제 이벤트를 핸들링하는 건 각 input을 가지고 있는 컴포넌트의 책임으로 넘기면 어떨까 제안드려봅니다.

ex)
```js
// Provider
type CardNumber = [string, string, string, string]

...

const [cardNumber, setCardNumber] = useState<CardNumber>([ ... ])

...

const handleChangeCardNumber = (cardNumber: CardNumber) => {
  // some validations
  setCardNumber(cardNumber)
}

// Input/CardNumbers
const CardNumbers = ({ cardNumber, onCardNumberChange }) => {
  const handleChange = (index) => (event) => {
    const newCardNumber = [...cardNumber]
    newCardNumber[index] = event.target.value
    onCardNumberChange(newCardNumber)
  }
}
```

2023-02-22 07:10 UTC, hyungkishin commented on src/components/input/CardForm.tsx
> +  };
step2 에서 작성하게 될것 같습니다 제거 하는게 낫겠네요

2023-02-22 07:11 UTC, hyungkishin commented on src/components/input/cardPassword/index.tsx
> +          value="*"
아 그렇군요 미쳐 생각하지 못한 부분이였습니다

2023-02-22 07:11 UTC, hyungkishin commented on src/pages/RegistPage/AddCardPage.tsx
> +        <CardForm />
감사합니다

2023-02-22 07:16 UTC, hyungkishin commented on src/store/Provider.tsx
> +  const [cvc, setCvc] = useState<string>("");
큰범위로 감싼부분은 제가 아직 미숙한 부분 +
store 로 관리 되어 카드 등록이 완료된 경우 해당 상태들을 가져오게 하기 위한 목적이였습니다. 

hooks 로 관리하려다 step2 에서 contextApi 를 사용해야 될것같아 한곳으로 모아놓았네요 . 

그리고 충분하다는 말씀이 컴포넌트 하나에 책임을 말씀하시는 것인지... 궁금합니다 :)

2023-02-22 07:17 UTC, hyungkishin commented on src/components/card/index.tsx
> +    cardExpiry[0] ? `${cardExpiry[0]} / ${cardExpiry[1] || "YY"}` : "MM / YY";
아 이부분 이해했습니다 감사드립니다 :)

2023-02-22 07:18 UTC, hyungkishin commented on src/components/card/index.tsx
> +  };
addHypen 으로 바꾸게 될것같습니다 !

2023-02-22 07:18 UTC, hyungkishin commented on src/components/card/index.tsx
> +    cardExpiry[0] ? `${cardExpiry[0]} / ${cardExpiry[1] || "YY"}` : "MM / YY";
음.... 이부분 고민을 좀더 해봐야겠습니다

2023-02-22 07:20 UTC, hyungkishin commented on src/store/Provider.tsx
> +    };
아 요기가 말씀하신 부분중에 "책임" 이군여 !!!! 
1. provider에서는 폼 관련 상태와 이를 업데이트 하는 인터페이스만 제공할것
2. 실제 이벤트를 핸들링하는 건 각 input을 가지고 있는 컴포넌트의 책임으로
이렇게 진행해보겠습니다 

감사합니다 :)

2023-02-27 15:42 UTC, Tanney-102 commented on src/store/Provider.tsx
> +  const [cvc, setCvc] = useState<string>("");
굳이 이 Context의 상태를 사용하지 않는 곳까지 포함하지 않아도 되겠다는 의미였습니다~!

2023-02-27 15:49 UTC, Tanney-102 approved these changes
안녕하세요 형기님! 
리뷰 반영하느라 고생많으셨습니다!
코멘트 하나 남기긴했는데 다음 스텝에서 고민하셔도 좋을 것 같아 바로 머지하도록 하겠습니다!

2023-02-27 15:49 UTC, Tanney-102 commented on src/components/input/cardNumbers/index.tsx
> +  }, [numbers, handleChangeCardNumber]);
전반적으로 컴포넌트 안에서 상태를 따로 관리하고 useEffect를 통해 상위 컴포넌트와 동기화 하는 방식인듯한데, 부모 컴포넌트로 부터 상태와 changeHandler 둘 다 prop으로 받는 방식이면 어떨까요?
지금 방식으로는 상태(여기서는 numbers)가 컴포넌트와 Context 두곳에 존재하게 됩니다. 상태의 출처(source)는 가능한 하나가 되도록 해주시면 좋겠습니다.

```ts
const CardNumbersInput({
  cardNumbers,
  handleChangeCardNumber
}) => {
  ...
}
```

2023-02-27 15:49 UTC, merged

2023-02-28 02:23 UTC, hyungkishin commented on src/components/input/cardNumbers/index.tsx
> +  }, [numbers, handleChangeCardNumber]);
아 그렇군요 ! :) 감사합니다 !