[클린코드 리액트 2기 최진희] 페이먼츠 미션 Step 1
next-step/react-payments pull request #58
Opened 2023-02-20 13:12 UTC by realhee

안녕하세요 환오님!
페이먼츠 미션을 리뷰받게 되서 영광입니다 잘 부탁드립니다 🥳

React 컴포넌트 활용이 익숙치 않아 헤매느라 PR 이 늦었네요..ㅎㅎ
제가 이해하고 설명할 수 있는 한도 내에서 최대한 구현해보려 노력했습니다
필수 요구사항 구현 피드백 진행하면서 storybook도 함께 추가 반영하겠습니다!

🚩 [데모링크](https://react-payments-ruby.vercel.app/)

## **필수 요구사항**

- [ ]  **`Storybook`** 상호 작용 테스트
- [x]  **`재사용 가능한 Component`** 작성

### **카드 추가**

- [x]  **`<`**(뒤로가기) 버튼 클릭 시, 카드 목록 페이지로 이동한다.
- [x]  카드 번호를 입력 받을 수 있다.
    - [x]  카드 번호는 숫자만 입력가능하다.
    - [x]  카드 번호 4자리마다 `-`가 삽입된다.
    - [x]  카드 번호는 실시간으로 카드 UI에 반영된다.
    - [x]  카드 번호는 앞 8자리만 숫자로 보여지고, 나머지 숫자는 `*`로 보여진다.
- [x]  만료일을 입력 받을 수 있다.
    - [x]  **`MM / YY`** 로 placeholder를 적용한다.
    - [x]  월, 년 사이에 자동으로 `/`가 삽입된다.
    - [x]  만료일은 실시간으로 카드 UI에 반영된다.
    - [x]  월은 1이상 12이하 숫자여야 한다.
- [x]  보안코드를 입력 받을 수 있다.
    - [x]  보안코드는 `*`으로 보여진다.
    - [x]  보안코드는 숫자만 입력가능하다.
- [x]  카드 비밀번호의 앞 2자리를 입력 받을 수 있다.
    - [x]  카드 비밀번호는 각 폼마다 한자리 숫자만 입력가능하다.
    - [x]  카드 번호 입력 시, `*`으로 보여진다.
- [x]  카드 소유자 이름을 입력 받을 수 있다.
    - [x]  이름은 30자리까지 입력할 수 있다.
    - [x]  이름 입력 폼 위에, 현재 입력 자릿수와 최대 입력 자릿수를 실시간으로 보여준다.
- [x]  카드 추가 완료시 카드 등록 완료 페이지로 이동한다.
### **TODO**
- [ ] 카드 소유자 이름 현재 입력 자릿수 위치 조정
- [ ] nextsibling auto focus
- [x] `CardInfo` 라는 공통 상태 값으로 제어하기

## **고민했던 점**
### CDD 관점으로 개발하기
CDD는 상향식 개발이라는 관점으로 시작해 처음 `input`부터 위로 올라가면서 용도에 따라 컴포넌트를 쪼갰습니다. 유효성 검사 로직을 적용하면서 중복 코드도 많아졌고, 불필요한 수정이 너무 많이 일어나서 시간을 많이 보낸 것 같습니다.. ( 앞으로는 개선점이 보일 때마다 리팩토링을 진행하면서 코드를 작성해보려 합니다! ) 최대한 책임을 확실히 구분하고, 응집성 있는 컴포넌트 구현을 하고 싶었는데.. 잘 된건지 모르겠습니다.

### State 끌어올리기
React 에서의 실시간으로 변경되어야하는 제어 컴포넌트 개념과 customHook 패턴을 제대로 이해하기 위해 노력했습니다. 부모 컴포넌트로부터 onchange event를 받고 자식 컴포넌트의 state를 끌어올리는 작업이 익숙치 않아 오래 헤맸습니다.
`AddCard` 페이지 레벨에서 상태를 실시간으로 view로 보여주는 `CardBox` 컴포넌트와 onchange 이벤트를 핸들링하는 컴포넌트들( `CardNumberInput` `CardExpirationInput` `CardOwnerNameInput` `CardSecurityCodeInput` `CardPasswordInput`)으로 나눴습니다. 하위 컴포넌트들은 실시간으로 data를 공유합니다. 상태는 불변성을 유지하기 위해 spread operator를 활용했습니다.

### 디렉토리 구조
정확한 목적 별로 묶고 싶었고 `src` 폴더 안에서 `componsnts` `constant` `hooks` `pages` `stories` `styles` 로 구성했습니다.
domain과 style 적 요소를 구분해야 하는지는 아직 필요성을 잘 모르겠습니다.

## **✔️질문**
1. 현재 `AddCard` (카드추가 페이지) 컴포넌트에서 state를 개별 컴포넌트 단위로 customHook으로 관리하고 있는데요. `AddCard` 컴포넌트에서 개별 customHook 인자값을 `CardInfo` 라는 공통 state로 묶어 제어 컴포넌트처럼 동작하게 하고 싶은데 방법이 있을까요?

2. `input`, `span`과 같은 DOM 요소를 `<Input>` `<Span>`으로 React 컴포넌트화 해야하나 고민스러웠는데요.  재활용의 의미가 크게 없어보여 현재는 `<Span>`만 컴포넌트화 한 상태입니다.  단일 DOM 요소를 컴포넌트화 하는 게 CDD 적 관점에서 어떤 의미가 있는지 궁금합니다! 
 ➕ [Component Driven User Interface](https://www.componentdriven.org/)
![image](https://user-images.githubusercontent.com/25587196/220111437-1ca41181-db28-45a0-b8c9-bd6cfd916761.png)

3. 처음 CardInfoForm를 컴포넌트화 했었는데 하나의 컴포넌트 안에서 너무 많은 상태 값을 넘겨줘야 하기 때문에 책임이 많아지는 것 같아 컴포넌트를 제거했습니다. 혹시 여러개의 상태 값을 넘길 때 간소화할 수 있는 방법이 있나요?

4. useEffect, useMemo, useRef 를 활용해보고 싶은데 구현 시 적용 포인트에 대한 감이 잘 오지 않습니다! 리뷰어님은 보통 어떤 시점, 그리고 어떤 필요성에 의해 적용하시는 편인지 궁금합니다.
 ➕ 질문 남기고 나서 아래 링크에서 useMemo, useEffect에 대한 해답을 얻은 것 같아요!
[유연한 컴포넌트 작성하기](https://overreacted.io/ko/writing-resilient-components/#유연한-컴포넌트-작성하기)

5. LMS에서 언급되어 있는 `useimperativehandle`에 대한 이해가 잘 되지 않았는데요. 실제 활용이 많이 되는 패턴인가요? 혹시 추천해주실만 한 레퍼런스가 있다면 추천도 부탁드립니다!

2023-02-21 02:10 UTC, jho2301 requested changes
안녕하세요 진희님!
리뷰를 하게된 전환오라고 합니다 🙌 
전반적으로 코드의 역할이 분리되어있고 깔끔하게 구성되어있어서 pr을 읽는데 큰 무리가 없었던 것 같아요
각 input을 훅으로 분리해주셨었는데 변경의 범위를 어떻게 바라보는지에 따라 input별로 hook을 분리한 것이 유지보수하는 것에 불편함으로 작용할 수도 있을 것이라고 생각해요. 모든 input이 controlled component로 작성되었는데 form을 제어함에 있어서 언제 렌더가 이뤄져야하는지 한 번 고민을 해보셨으면 좋겠다고 생각해봤습니다. 사실 타이핑을 할 때마다 매번 렌더가 될 필요는 없을 것 같아요. 기존 패키지로는 react hook form이라는 라이브러리가 있는데 여기 패키지의 동작을 한 번 알아보셔도 좋을 것 같습니다. 

### 고민했던 점
> 현재 AddCard (카드추가 페이지) 컴포넌트에서 state를 개별 컴포넌트 단위로 customHook으로 관리하고 있는데요. AddCard 컴포넌트에서 개별 customHook 인자값을 CardInfo 라는 공통 state로 묶어 제어 컴포넌트처럼 동작하게 하고 싶은데 방법이 있을까요?

useReducer라는 리액트의 api를 참고해보셔도 좋을 것 같아요!
좀 더 나아가보면 위 데이터들은 각자 연관이 깊은, 독립적으로는 그렇게 의미가 없을 수도 있는 데이터들이기 때문에 객체로 묶어서 관리하고, 위에서 말씀드린 것처럼 비제어컴포넌트로 관리할 수 있다면 가장 최적화된 form페이지가 나오지 않을까 싶네요!

> input, span과 같은 DOM 요소를 <Input> <Span>으로 React 컴포넌트화 해야하나 고민스러웠는데요. 재활용의 의미가 크게 없어보여 현재는 <Span>만 컴포넌트화 한 상태입니다. 단일 DOM 요소를 컴포넌트화 하는 게 CDD 적 관점에서 어떤 의미가 있는지 궁금합니다!

코멘트에 남긴대로 html요소를 그대로 return한다면 컴포넌트로 만드는 것에 크게 의미가 있다고 생각하진 않아요. 특정한 스타일과 속성을 공통적으로 사용하는 요소에 적용해야할 때 atom요소로 의미가 있다고 생각합니다.

> 처음 CardInfoForm를 컴포넌트화 했었는데 하나의 컴포넌트 안에서 너무 많은 상태 값을 넘겨줘야 하기 때문에 책임이 많아지는 것 같아 컴포넌트를 제거했습니다. 혹시 여러개의 상태 값을 넘길 때 간소화할 수 있는 방법이 있나요?

객체를 이용해보시면 좋을 것 같아요!
카드를 예로들어보면

```ts
<CardRepresenter ownerName={ownerName} cardNumber={cardNumber} color={cardColor} .... />
```ts

이렇게 각각 prop을 기입해주기 보다는

```ts
<CardRepresenter card={card}
```
요렇게 객체로 주고 받는게 보다 효율적이고, 관련한 데이터들을 객체로 모으는 효과를 가져올 수 있어요.

> useEffect, useMemo, useRef 를 활용해보고 싶은데 구현 시 적용 포인트에 대한 감이 잘 오지 않습니다! 리뷰어님은 보통 어떤 시점, 그리고 어떤 필요성에 의해 적용하시는 편인지 궁금합니다.

해답을 얻으셨다니 다행이네요 :) overreacted 블로그는 리액트 메인테이너 중 가장 유명한 개발자인 댄 아브라모프가 운영하는 블로그라 신뢰도도 높고, 인사이트도 많이 얻어갈 수 있으실거라고 생각해요. 저도 많이 읽지는 않았지만 추천합니다 👍 👍 
간단하게 축약해서 설명해볼 수 있을 것 같아요. 자세한 동작과 사용법은 리액트 공식문서에서 자세하게 파악해볼 수 있을거예요
- useEffect: 컴포넌트에서 상태가 변함에 따라 http통신과 같은 부수효과(side effect)를 일으켜야 할 때 사용하는 훅
- useMemo: 함수컴포넌트 내부의 값들은 함수컴포넌트가 호출될때마다 새롭게 계산되고, 레퍼런스 타입의 경우 레퍼런스가 변하게 되는데  계산을 반복해서 하지않고 레퍼런스를 유지하기 위해 사용하는 훅
- useRef: 함수컴포넌트는 반복해서 호출되기때문에 일정한 값을 유지하기 힘든데, 이 값을 유지하기 위한 훅

> LMS에서 언급되어 있는 useimperativehandle에 대한 이해가 잘 되지 않았는데요. 실제 활용이 많이 되는 패턴인가요? 혹시 추천해주실만 한 레퍼런스가 있다면 추천도 부탁드립니다!

비제어 컴포넌트를 만드실 때 사용하실 수 있어요. 기본적으로 컴포넌트의 ref 를 통해 사용되는 api들을 제공할 때 사용합니다. 보통 input에서는 focus나 blur와 같은 메서드가 제공되는데요. useImperativeHandle을 사용하시면 요런 메서드를 정의해서 ref를 통해 외부에 제공할 수 있어요

```ts
const inputRef = useRef(...)

useEffect(() => {
   inputRef.current?.customMethod();
})

<input ref={inputRef} />
```

이 api역시 리액트 공식문서에서 참조하는게 가장 정확합니다! 

코멘트 남긴 부분 자유롭게 의견 남겨주세요
화이팅입니다 🦾

2023-02-21 02:10 UTC, jho2301 commented on src/components/Span.js
> +}
특정한 스타일이나 속성을 주입할 것이 아니라면 컴포넌트로 래핑해서 사용할 이유가 없는 것 같아요!

2023-02-21 02:10 UTC, jho2301 commented on src/components/PageTitle.js
> +}
요기도 그냥 h2로 사용하면 어떨까요?

2023-02-21 02:10 UTC, jho2301 commented on src/App.js
> +  },
기본적으로 url이 case sensitive하지만 url의 컨벤션은 일반적으로 케밥케이스를 따라요. 참고해보시면 좋을 것 같습니다.

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddCard.js
> +export default function AddCard() {
페이지이름은 명사로 명명하면 보다 의미가 명확해지는 것 같습니다. + 페이지컴포넌트라는 것을 드러내기 위해서
CardRegistrationPage 정도면 어떨까요?

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddCard.js
> +const [cardPassword, handleCardPassword] = useCardPassword();
한 개 인풋에 대한 상태와 검증로직을 훅으로 묶어주신 것으로 보여요. form의 경우에는 위에서 만들어주신 상태들이 무조건 같이 사용되기 때문에 이 값들 역시 한 묶음으로 생각해보면 어떨까요? 개별적으로 사용되는 케이스를 생각해보긴 어려울 것 같아요.

2023-02-21 02:10 UTC, jho2301 commented on src/hooks/useCardExpiration.js
> +  }
요런 유틸성 함수들은 util 이라는 디렉토리를 마련해두고 재사용해보면 좋을 것 같아요

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddCard.js
> +      </PageTitle>
요렇게 페이지에서 공통적으로 사용될 법한 컴포넌트들을 Layout 과 같은 컴포넌트로 선언하고 재사용하면 편하고, 페이지컴포넌트에서는 페이지가 다루는 도메인에 집중할 수 있어요

2023-02-21 02:10 UTC, jho2301 commented on src/components/CardOwnerNameInput.js
> +        {CARD_OWNER_NAME.MAX_LENGTH}
상수화를 적절하게 진행해주신 것 같아요 👍

2023-02-21 02:10 UTC, jho2301 commented on src/components/CardOwnerNameInput.js
> +}
일정한 스타일을 가진 Label 컴포넌트와 input컴포넌트를 atom컴포넌트로 갖고있었다면
별도로 컴포넌트를 분리하지 않아도 페이지 컴포넌트에서 크게 복잡도가 증가하지 않고 사용해볼 수 있을 것 같아요. 물론 지금 형태도 좋다고 생각합니다 👍

2023-02-21 02:10 UTC, jho2301 commented on src/components/CardPasswordInput.js
> +      {["num0","num1","num2","num3"].map((name, index) => {
함수컴포넌트는 함수를 호출함으로써 렌더가 이뤄지게 되는데, 요런 배열과같은 레퍼런스타입의 값들은 매번 새로운 주소값을 가지게 되어요. 내부에서 사용되는 값은 같기 때문에 주소값을 유지하는게 불필요한 렌더를 막는데 주효한 방법입니다. 컴포넌트 밖에 배치해 함수컴포넌트가 호출될때 새롭게 배열을 만드는 것을 막거나 컴포넌트 내부에서 useMemo를 사용해 memoization을 진행하면 레퍼런스를 유지할 수 있어요

2023-02-21 02:10 UTC, jho2301 commented on src/hooks/useCardPassword.js
> +    }
검증 조건이 두 개 이상이 되면 이런 if문 블록이 여러개 생길텐데, 하나의 함수에서 검증을 해보도록 처리해보면 어떨까요? 상위로는 error객체나 {success: boolean, errorMessage?: string} 과 같은 결과 객체를 반환하면 사용하는 쪽에서 어떤 단계에서 검증이 실패했는지 파악하기 쉬울 것 같아요

2023-02-21 02:10 UTC, jho2301 commented on src/hooks/useCardPassword.js
> +    }
false를 반환하는 의도가 아마도 핸들링이 중간에 실패했다는 것을 의도해주신 것으로 보여요, 다만 성공했을 때 true를 반환하고 있지 않아서  일관성은 떨어지는 것 같습니다. 역시 { success: boolean } 객체를 반환하면 의도를 보다 명확히 해볼 수 있어요

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddCard.js
> +      <Link className="button-text" to={`/AddedCard`}>
route path는 상수로 관리해보시면 어떨까요? 재사용이나 변경, 쿼리파람의 일관성있는 적용등에서 이점이 있어요

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddCard.js
> +      </Link>
유저의 입력 값들로 카드를 등록하는 동작이기 때문에(제출) form형태로 변경해보시면 좋을 것 같아요. submit이벤트에서 전달받은 데이터들을 검증하고, 에러메시지를 도출해내거나, 유효한 데이터로 검증이 되었다면 이 검증된 데이터로 카드를 만들어볼 수 있을 것 같아요.

2023-02-21 02:10 UTC, jho2301 commented on src/pages/AddedCard.js
> +}
요기 페이지도 적절하게 컴포넌트로 분리해 구성해보시면 어떨까요?

2023-02-21 02:10 UTC, jho2301 commented on src/stories/Button.jsx
> +};
요즘은 요런 프로퍼티를 이용하기보다는 자바스크립트단에서 처리하는 것 같아요.
```js
export const Button = ({ primary = false, backgroundColor, size = 'mdeium', label, ...props }) => {
```

2023-02-21 02:10 UTC, jho2301 commented on src/stories/Button.jsx
> +};
propTypes를 이용해주셨네요.
prop에 한해서 타입스크립트를 적용해보셔도 좋겠다는 생각이 들었어요

2023-02-21 02:10 UTC, jho2301 commented on src/constants/card.js
> +  PLACEHOLDER: "카드에 표시된 이름과 동일하게 입력하세요.",
적절하게 상수화가 필요한 매직값들을 분리해주신 것 같아요 👍

2023-02-21 02:10 UTC, jho2301 commented on package.json
> +    "build": "react-scripts build",
요즘 vite가 핫한데 vite에 대해서 알아보시고 적용해보셔도 좋을 것 같아요~

최근에 리액트쪽 레포에서 요런 논의가 있었어요
https://github.com/reactjs/reactjs.org/pull/5487

2023-02-22 11:05 UTC, realhee commented on src/components/CardOwnerNameInput.js
> +}
Label컴포넌트를 쪼갠다면 length를 실시간으로 나타내는 제어 컴포넌트처럼 동작해야 하겠군요 😶
다른 Input 계열 컴포넌트의 length를 나타내는 Label을 재사용 한다면 유용할 것 같아요! 
우선 지금 프로젝트에서는 재사용 포인트가 보이지 않아 필요 시 적용해보겠습니다 :)

2023-02-25 16:04 UTC, realhee commented on src/hooks/useCardPassword.js
> +    }
의도는 알겠으나 객체로 에러 객체를 넘긴다는 말이 이해가 가지 않았습니다 😭
react-hook-form의 코드를 확인해봤는데, reducer 에서 이런 식으로 객체를 넘기는 걸 말씀하신 걸까요?
```
<form onSubmit={handleSubmit(onSubmit)}>
      <input
        type="text"
        placeholder="First name"
        {...register("First name", { required: true, maxLength: 80 })}
      />
```

>  {success: boolean, errorMessage?: string} 

errorMessage key는 어떻게 관리하는건가요? 가능하시다면 suggestion 부탁드립니다!

2023-02-25 16:06 UTC, realhee commented on src/pages/AddCard.js
> +const [cardPassword, handleCardPassword] = useCardPassword();
useReducer를 적용해봤습니다!

[ee6a2e5](https://github.com/next-step/react-payments/pull/58/commits/ee6a2e5b5434e0d5bef28b4fab8f5c9c6bc8a693)

2023-02-25 16:25 UTC, realhee commented on src/pages/AddCard.js
> +      </Link>
제어/비제어 컴포넌트의 구분에 대해 몇 가지 고민을 해봤습니다.

처음 설계 당시, 모든 Input을 제어 컴포넌트로 작성했던 이유는 모든 input의 유효 값이 CardBox에 실시간으로 UI 반영되려면 제어 컴포넌트로 동작해야겠다고 생각했기 때문이었는데요. 

코멘트 주신 내용을 토대로 다시 생각해봤습니다.

1. 에러 핸들링을 실시간으로 제어해야 할까?
- 제어 : 실시간으로 input의 border를 빨간색으로 띄운다면 편할 것 같다는 생각
- 비제어 : 모바일 환경에서는 실시간으로 에러 메시지를 나타내는 alert창을 띄우는 것이 UX 면에서 불편 하겠다는 생각.
- (+) CardBox UI에는 에러 핸들링을 하지 않은 그대로의 값을 반영해야 하는데 괜찮나?

2. 일부 Input에서는 실시간으로 에러 핸들링을 하고, 일부 Input에서는 form submit 시 에러 핸들링을 한다면?
- [react-hook-form](https://react-hook-form.com/)을 확인해보니 watch(제어), errors(제어), touched(비제어-killfocus 시점) 로 관리 - 링크
- 사용자 입장에서 혼란을 가지진 않을까?

3. 일괄적으로 비제어 컴포넌트 사용으로 제출 시에만 리렌더링
- 불필요한 재렌더링을 줄이고 성능 최적화에 가장 적합한 방법이라 판단

결론적으로 cardInfo의 모든 컴포넌트가 비제어 컴포넌트로 관리되어야 한다고 생각했습니다.
(useRef를 통해 비제어 컴포넌트화 시키려는데 어떻게 적용해야 할지 공부해보고 추가 반영하겠습니다 🙂)


위 내용이 리뷰어님 생각과 비교해 개선 포인트가 있는지 궁금합니다!

2023-02-26 13:46 UTC, jho2301 approved these changes
안녕하세요 진희님 
꼼꼼하게 반영해주셔서 감사합니다~!
고민을 하고 계신 부분에 의견남겨보았으니 스텝2 진행하실때 참고 해보셔도 좋을 것 같습니다.
크게 이견 없어서 스텝 2에서 뵙도록 하겠습니다 
고생하셨습니다 🙇

2023-02-26 13:46 UTC, jho2301 commented on src/pages/CardRegistrationPage.js
> +  console.log(action, state);
pr올릴때 console.log 한 번 검색해보고 제거하는 단계를 의식적으로 가져봐도 좋을 것 같아요

2023-02-26 13:46 UTC, jho2301 commented on src/pages/CardRegistrationPage.js
> +      }
에러UI를 리듀서함수에서 보여주고있는데 다른방식으로 표현해야한다면 변경하기 까다로울 것 같아요
dipatch를 보내기 전에 검증을 하고 검증된 값만 dispatch를 타도록 하면 좋을 것 같습니다

2023-02-26 13:46 UTC, jho2301 commented on src/hooks/useCardPassword.js
> +    }
```js

  if (!isValidPassword(value)) {
      return { success: false, errorMessage: "숫자만 입력 가능합니다" }
    }
```
이렇게 변경해보시면 어떨까요? 그러면 사용하는 컨텍스트에서 에러여부와 에러메시지 역시 파악할 수 있어요

2023-02-26 13:46 UTC, jho2301 commented on src/pages/AddCard.js
> +      </Link>
useRef로 변경을 할 때 검증을 계속 진행하고, 검증을 통과하지못하면 검증함수에서 받아온 메시지를 setState를 통해 리렌더링을 트리거해주면 비제어와 제어 두 가지방식을 필요한 상황에 적절하게 사용하는 형태가 되지 않을까 싶어요

2023-02-27 15:31 UTC, realhee commented on src/pages/CardRegistrationPage.js
> +      }
오 reducer 로직을 작성할 때는 유지보수를 염두해 작성해야겠군요 🧐 
아래 커밋에서 반영했습니다~

[02a6494](https://github.com/next-step/react-payments/pull/58/commits/02a649449562d358e31e636304d0837ece43549d)

2023-02-28 12:57 UTC, merged