[클린코드 리액트 1기 박실] 페이먼츠 미션 Step 1
next-step/react-payments pull request #7
Opened 2022-01-17 14:26 UTC by parksil0

## 작업내용

- 스토리북이 설정
   - 처음이라 예제와 공식문서를 봐도 헷갈리네요. 가장 기본적인 스토리만 넣어놨고, 예제들 보면서 추가할 예정입니다.
- step 1 의 필수 요구사항들을 주로 코드 작성 
   - 그 뒤에 이어지는 것들은 step 2에서 시작할게요!

제가 카드 추가 했을 때에는 별 문제 없었던걸로 확인 되는데, 혹시라도 발견하면 코멘트 부탁드립니다! 
감사합니다 😄 
---
## 📝 Requirements
### 필수 요구사항
- [X] Storybook 상호 작용 테스트
- [X] 재사용 가능한 Component 작성
### 카드 추가
- [x] `<`(뒤로가기) 버튼 클릭 시, 카드 목록 페이지로 이동한다.
- [x] 카드 번호를 입력 받을 수 있다.
   - [x] 카드 번호는 숫자만 입력가능하다.
   - [x] 카드 번호 4자리마다 -가 삽입된다.
   - [x] 카드 번호는 실시간으로 카드 UI에 반영된다.
   - [x] 카드 번호는 앞 8자리만 숫자로 보여지고, 나머지 숫자는 *로 보여진다.
- [x] 만료일을 입력 받을 수 있다.
   - [x] MM / YY 로 placeholder를 적용한다.
   - [x] 월, 년 사이에 자동으로 /가 삽입된다.
   - [x] 만료일은 실시간으로 카드 UI에 반영된다.
   - [x] 월은 1이상 12이하 숫자여야 한다.
- [x] 보안코드를 입력 받을 수 있다.
   - [x] 보안코드는 *으로 보여진다.
   - [x] 보안코드는 숫자만 입력가능하다.
- [x] 카드 비밀번호의 앞 2자리를 입력 받을 수 있다.
   - [x] 카드 비밀번호는 각 폼마다 한자리 숫자만 입력가능하다.
   - [x] 카드 번호 입력 시, *으로 보여진다.
- [x] 카드 소유자 이름을 입력 받을 수 있다.
   - [x] 이름은 30자리까지 입력할 수 있다.
   - [x] 이름 입력 폼 위에, 현재 입력 자릿수와 최대 입력 자릿수를 실시간으로 보여준다.
- [x] 카드 추가 완료시 카드 등록 완료 페이지로 이동한다.
### 심화 요구사항 (선택사항)
- [ ] Storybook 단위 테스트
- [x] 유효성 검증 실패에 대한 UI/UX 추가
- [ ] 유효한 값 입력시 다음 필드로 Input Focusing
- [ ] 카드사 선택
   - [ ] 카드 번호 앞 8자리로 카드사를 추정하여 그 테마를 카드 UI에 반영한다.
   - [x] 카드사를 선택하지 않아도 모달을 닫을 수 있다.
   - [ ] 카드사가 선택되고 유효한 카드 번호 16자리를 모두 입력하면, 자동으로 만료일로 focus된다.
- [ ] 보안코드 툴팁
   - [ ] 클릭 시, 보안코드 관련 안내 메시지를 보여준다.
   - [ ] focusout 시, 툴팁이 닫힌다.
- [ ] 가상 키보드
   - [ ] 마스킹 처리된 값 입력시 사용
   - [ ] 숫자를 랜덤으로 배열

2022-01-18 12:39 UTC, amorfati0310 requested changes
수고하셨습니다. 리뷰 살펴보시고 수정할만한 부분 수정해보시면 좋을 것 같습니다.

2022-01-18 12:39 UTC, amorfati0310 commented on examples/index.html
> +			<div class="modal-dimmed">
인덴트 맞춰주시면 좋을 것 같습니다.

2022-01-18 12:39 UTC, amorfati0310 commented on src/common/styles.tsx
> +export const PageTitle = styled.h2`
```suggestion
export const PageTitle = styled.h2<{mb10}: {PageTitleProps}>`
```
아래 사용하고 있는 방법으로 일관성 맞춰주시는게 더 좋을 것 같네요

2022-01-18 12:39 UTC, amorfati0310 commented on src/common/styles.tsx
> +  ${({ mb10 }: PageTitleProps) => mb10 && `margin-bottom: 2.5rem;`}
10이 의미하는 부분이랑 2.5rem이랑 다른 데도 사용하는 부분 비율이 맞으면 좋을 것 같습니다. 
50 /4   12.5rem

2022-01-18 12:39 UTC, amorfati0310 commented on src/components/Card/index.tsx
> +      {type === 'list' && <span>법인카드</span>}
여기도 empty가 아니면 렌더링 하도록 해도 되지 않을까요?

2022-01-18 12:39 UTC, amorfati0310 commented on src/components/Modal/index.tsx
> +            <ModalItemButton onClick={onClose}>
반복되는 마크업 구조를 list rendering으로 고치셔도 좋을 것 같습니다.

2022-01-18 12:39 UTC, amorfati0310 commented on src/components/Card/styles.tsx
> +export const CardBasic = styled.div<{ size: string; color?: string }>`
Card에서 정의한 union type으로 지정해주시면 더 좋을 것 같습니다. `size: 'small' | 'big';`

2022-01-18 12:39 UTC, amorfati0310 commented on src/pages/Add.tsx
> +    const copyCardNumberPasswordError = [...cardNumberPasswordError];
주석으로 
// 카드번호 유효성검사 
// 만료일 유효성 검사 
// cvc 유효성 검사 
나눈 것 처럼 함수들로 나눠놓으면 흐름 파악하기 더 용이할 것 같습니다.

2022-01-18 12:39 UTC, amorfati0310 commented on src/pages/Add.tsx
> +            {cardNumber[0].length === 4 ? '-' : ''}
여기 로직이 반복되는데 함수를 만들어서 사용하는 것이 어떨까요?

2022-01-18 14:35 UTC, parksil0 commented on src/components/Card/index.tsx
> +      {type === 'list' && <span>법인카드</span>}
아래의 첨부 사진과 같이 카드 목록에만 보이는 별칭을 설정해 놓은 코드입니다~!

![image](https://user-images.githubusercontent.com/41149744/149957141-12e257a9-d942-4b38-8564-9ee966fd2e50.png)

2022-01-18 14:41 UTC, parksil0 commented on src/common/styles.tsx
> +  ${({ mb10 }: PageTitleProps) => mb10 && `margin-bottom: 2.5rem;`}
10마다 2.5rem씩 증가하는 것으로 확인됩니다. 그래서 50이 12.5rem인것 같아요!
충분히 헷갈릴 수 있는 것같은데, 굳이 사용하지 않아도 아래의 링크처럼 일단 생성해 놓는게 좋을까요??
링크 : https://github.com/parksil0/react-payments/blob/step1/examples/styles/utils.css

2022-01-18 15:13 UTC, parksil0 commented
> 수고하셨습니다. 리뷰 살펴보시고 수정할만한 부분 수정해보시면 좋을 것 같습니다.

안녕하세요 희찬님! 반갑습니다. 저는 박 실이라고 합니다. 😄 
리뷰 주신내용 읽어보고 다시 커밋 했습니다. 혹시 의도하신대로 변경이 안 된 부분이 있다면 코멘트 남겨주신다면 감사하겠습니다!

2022-01-19 15:31 UTC, amorfati0310 commented
> > 수고하셨습니다. 리뷰 살펴보시고 수정할만한 부분 수정해보시면 좋을 것 같습니다.
> 
> 안녕하세요 희찬님! 반갑습니다. 저는 박 실이라고 합니다. 😄 리뷰 주신내용 읽어보고 다시 커밋 했습니다. 혹시 의도하신대로 변경이 안 된 부분이 있다면 코멘트 남겨주신다면 감사하겠습니다!

확인 했습니다 수고많으셨습니다

2022-01-19 15:32 UTC, merged