[클린코드 리액트 2기 김민혁] 페이먼츠 미션 Step 2
next-step/react-payments pull request #77
Opened 2023-03-02 05:09 UTC by minhyeok0328

안녕하세요 리뷰어님!
step2 제출이 조금 늦어진 감이 있어서.. 피드백을 전부 반영하지는 못했지만 더 늦기전에 풀리퀘스트 남깁니다!

[페이먼츠 링크](https://react-payments-plum.vercel.app/)
[스토리북 링크](https://63f1bd39e23868234828c4f0-lzjyblfwxi.chromatic.com/)

## 필수 요구사항
- [x] Storybook 상호 작용 테스트
- [x] Controlled & Uncontrolled Components에 입각하여 Form 핸들링
- [x] Context API를 활용해 전역 상태 관리 및 계층 재구성

## 카드 추가 확인
- [x] 이전 폼에서 입력된 카드를 보여준다.
- [x] 카드 별칭을 입력할 수 있다.
  - [x] placeholder는 카드 별칭 (선택)이다.
  - [x] 빈 입력값인 경우, 카드사 이름이 별칭으로 저장된다.
  - [x] 최대 길이는 10자리이다.
- [x] 확인 버튼을 누르면, 카드 목록 페이지로 이동한다.

## 카드 목록
- [x] 카드 목록을 조회할 수 있다.
- [x] 카드 목록은 최신순(내림차순)으로 정렬된다.
- [x] 목록 최상단에 +을 누르면 카드 추가 페이지로 이동한다.
- [x] 카드를 클릭하면, 카드 별칭 수정(카드 추가 완료 페이지)로 이동한다.
- [x] 카드를 삭제할 수 있다.

# 고민해본 점

우선 기존에 useInput 이라는 input 제어컴포넌트 훅을 사용하고 있었는데, 피드백을 보고 다시 생각해보니 폼에서 그렇게 까지 제어컴포넌트를 사용할 이유가 없는 것 같아 ref로 값을 받아와서 사용하게 해보았습니다.

Card 관련 상태나 함수를 provider로 제공하도록 해두었고, 값이 변경되면 provider로 감싼 모든 자식 컴포넌트에서 리렌더링이 일어나는 것으로 알고 있어서 사용하는 컴포넌트를 memo로 감싸고 provider에서 value를 주입 해 줄 때도 useMemo로 메모이제이션을 해줬습니다.

2023-03-04 11:28 UTC, InSeong-So requested changes
안녕하세요, 민혁님! 리뷰어 소인성입니다😁
1단계 피드백을 많이 적용해주려고 노력해주셨네요. 고생 많으셨어요!
그럼에도 아직 몇 가지가 보여서... 코드로 코멘트 남겼으니 확인 바랍니다🙇‍♂️

또 배포된 서비스에서 문제가 조금 있어서 말씀드립니다.
1. 유효성 검사에 실패해도 등록이 됨

![image](https://user-images.githubusercontent.com/18283006/222897286-7c81bd66-4669-4dba-abb4-65d23691a55b.png)

2. 카드 등록 후 추가하기를 누르면 기존 카드 정보가 유효하게 남아있음

고민해본 점에 기록해두신 제어/비제어 컴포넌트에 대한 고찰이 너무 좋네요.
이제 이를 토대로, 어느 시점에 어떤 컴포넌트로 활용하는 것이 좋을지에 대한 결정을 해보는 것이 좋을 것 같아요😎

고생 많으셨습니다! 내용 수정 후 다시 요청 부탁드려요👍

2023-03-04 11:28 UTC, InSeong-So commented on src/components/CardBox.tsx
>          </div>
네이밍이 brand보다는 company나 카드 발행사의 성격을 띄는 단어가 좋을 것 같은데, 바꾸신 의도가 있을까요?!

2023-03-04 11:28 UTC, InSeong-So commented on src/components/CardBox.stories.tsx
>  };
EOL 😨

2023-03-04 11:28 UTC, InSeong-So commented on src/components/CardBox.tsx
> +function CardBox({ cardNumber, cardHolder, expiredDate, type = 'small', color, brand }: PropsWithChildren<ICardBox>) {
`PropsWithChildren` 을 쓰신 이유가...? 있을까용? `children`이 안보이네요!

2023-03-04 11:28 UTC, InSeong-So commented on src/components/CardSelection.tsx
> +        <div className="flex-center" key={key}>
key가 뭐지?하고 봤는데 index를...! 지금처럼 변경사항이 없어서 index로 넣어두신 것 같네요. 그래도 지양해보는 것이 어떨까요? crypto의 randomUUID를 쓴다거나...🙄

2023-03-04 11:28 UTC, InSeong-So commented on src/components/CardSelection.tsx
> +            <div className="modal-item-container" key={cardCompany.color} onClick={() => onChange(cardCompany)}>
인라인 함수보다 useCallback 등으로 함수를 분리하는 작업은 어떨까요?

2023-03-04 11:28 UTC, InSeong-So commented on src/components/Modal.tsx
> +  }, []);
오... 이런 이벤트는 css로도 제어할 수 있습니다. user-select를 none으로 해두거나 말이죠!

2023-03-04 11:28 UTC, InSeong-So commented on src/components/form/Button.tsx
>    children?: ReactNode;
`children`은 없어도 될 것 같아요!

2023-03-04 11:28 UTC, InSeong-So commented on src/utils/filter.ts
> +  }).join('-');
정규식도 상수화해서 관리하는게 좋겠네요!💪

2023-03-04 11:28 UTC, InSeong-So commented on src/router/index.tsx
> +  {
👍

2023-03-04 11:28 UTC, InSeong-So commented on src/provider/card-box/useCardBoxContext.ts
> +}
context API는 최상위에서 사용하면 하위 컴포넌트가 모두 리렌더링되는 이슈가 있기 때문에... 이를 해결하는 방법을 찾아보길 바랍니다!

[참고](https://itchallenger.tistory.com/285)를 확인해주세요🤗

2023-03-04 11:28 UTC, InSeong-So commented on src/hooks/useRefs.ts
> +  }
[여기](https://stackoverflow.com/questions/65350114/useref-for-element-in-loop-in-react)를 참고해서 고쳐보면 좋을 것 같습니다😊

2023-03-04 11:28 UTC, InSeong-So commented on src/provider/card-box/CardBoxProvider.tsx
> +  }, []);
이 함수의 논리대로라면 cardNumber, expiredDate 둘 다 변경 되었을 때가 제일 효율이 좋지만, 하나만 변경되면 불필요하게 연산을 수행해야 하네요. 그렇다면 setCardState 함수를 분리하여 cardNumber용, expiredDate용 setter를 두면 어떨까요?

2023-03-04 11:28 UTC, InSeong-So commented on src/repositories/CardRepository.ts
> +
클래스로 extends 된 인스턴스를 관리하는 팁입니다.

생성자 함수에 인자를 명시하여 어떤 역할을 하는 파라미터인지 타인에게 인지시키고, 해당 값을 super로 올려주게 하면 직관성이 높아지며 외부에서 무엇을 할 지 선택사항이 많아집니다.

```suggestion
class CardRepository extends Repository {
  constructor(storeKey:string) {
    super(storeKey);
  }
}

export default new CardRepository('card-list');

```

2023-03-04 11:28 UTC, InSeong-So commented on src/pages/RegisterComplete.tsx
> +    const nickName = value.length ? value : cardData.brand;
공백문자('     ')도 허용될 것 같은데... 어떤가요?! minLength, required 등의 어트리뷰트를 활용해도 괜찮아보입니다🫠

2023-03-04 11:28 UTC, InSeong-So commented on src/pages/RegisterComplete.tsx
> +  const cardData = useMemo(() => cardList.find((item) => item.index === cardIndex), []);
이 코드는 훅으로 분리되면 좀 더 깔끔하게 관심사를 분리할 수 있을 것 같아요.
필요한 것은 카드의 index, list, data 등이기 때문에 searchParams를 파싱하는 내용을 알지 않아도 괜찮겠죠!

2023-03-04 11:28 UTC, InSeong-So commented on src/pages/RegisterCard.tsx
> +    const cardList = cardRepository.getItem();
Date 객체말고 Node.crypto 패키지를 활용해보면 어떨까요?

2023-03-04 11:28 UTC, InSeong-So commented on src/pages/CardList.tsx
> +          <div className="flex-column-center" onClick={() => goRegisterComplete(item.index)}>
어느 컴포넌트는 인라인으로 핸들러가 존재하고, 어디는 상단에 변수로 분리해서 관리하시네요! 일관성을 지키는 것이 좋을 것 같아요.

JSX는 매번 함수 오브젝트를 생성하니까 상단에 변수로 선언하는 컨벤션을 가져가보면 어떨까요?

2023-03-04 11:28 UTC, InSeong-So commented on src/pages/CardList.tsx
> +        >
card의 index가 고유식별 번호처럼 쓰일줄 알았는데... 그렇다면 key는 고유식별번호가 좋지 않을까요? 현재 카드에서는 cardNumber에 대한 중복 유효성이 없거든요!

2023-03-05 08:32 UTC, minhyeok0328 commented on src/components/CardBox.tsx
>          </div>
네이밍을 바꾸던 중에 카드 브랜드가 좀 더 적합하지 않을까? 하는 생각에 바꾸었는데 다시 찾아보니
`카드 브랜드`는 신용카드의 결제망을 제공하는 글로벌 기업을 의미하는 것이네요😮 단어를 혼동해서 사용한 것 같으니 이 부분은 다시 변경해 두겠습니다!

2023-03-05 08:35 UTC, minhyeok0328 commented on src/components/CardBox.stories.tsx
>  };
```
    "eol-last": [
      "error",
      "always"
    ]
```

앗.. eslint 규칙에 넣어둔 줄 알았는데 누락된 것 같아서 다시 추가했습니다!

2023-03-05 08:39 UTC, minhyeok0328 commented on src/components/CardBox.tsx
> +function CardBox({ cardNumber, cardHolder, expiredDate, type = 'small', color, brand }: PropsWithChildren<ICardBox>) {
children를 사용하는 컴포넌트 들을 전체적으로 변경하다 보니 실수로 들어간 것 같습니다😱

커밋 하고나서 file change를 좀 더 꼼꼼하게 보는 습관을 들여야 겠네요

2023-03-08 10:09 UTC, minhyeok0328 commented on src/pages/RegisterComplete.tsx
> +    const nickName = value.length ? value : cardData.brand;
지금 구조상 공백도 그냥 입력이 되어 버리네요ㅠㅠ 다만

카드 별칭을 입력할 수 있다.
 - placeholder는 카드 별칭 (선택)이다.
 - 빈 입력값인 경우, 카드사 이름이 별칭으로 저장된다.
 - 최대 길이는 10자리이다.

요런 내용이 있어 minLength나 required를 사용하기 애매하다고 판단이 들어서
```
    const value = nicknameRef.current.value.trim();
    const nickName = value.length ? value : cardData.cardCompany;
```

trim으로 공백을 제거한 후에 length를 체크하는 식으로 개선했습니다!

2023-03-09 11:33 UTC, minhyeok0328 commented
리뷰어님 안녕하세요!
피드백 주신 내용 반영했습니다. 확인 부탁드립니다~

## 피드백 반영 된 내용
- [x] 유효성 검사에 실패해도 등록이 됨
- [x] 카드 등록 후 추가하기를 누르면 기존 카드 정보가 유효하게 남아있음
- [x] 카드 네이밍 brand > company로 변경
- [x] EOL eslint 설정 추가
- [x] 전체적으로 인라인 함수가 사용된 부분들을 상단에 함수로 선언하여 분리
- [x] 컴포넌트 key에 Date객체, map에 index값 등으로 사용하던 부분 제거, 사용할 경우 `crypto.randomUUID()`를 사용하도록 변경
- [x] 불필요하게 PropsWithChildren 사용하거나 interface에 children  있는 부분 제거
- [x] 정규식 상수화 하여 관리
- [x] context api 리렌더링 최적화
  -  state를 사용하지 않고 dispatch만 사용하는 부분에서는 useCardDispatch로 사용하여 리렌더링 최적화
- [x] useRefs 커스텀 훅 로직 수정
- [x] url 파싱하는 부분 등에 로직들을 커스텀 훅으로 따로 분리

## 추가로 작업한 내용
- 컴포넌트를 atomic 패턴으로 분리

2023-03-11 06:41 UTC, InSeong-So approved these changes
민혁님, 안녕하세요!
피드백 확인했고, 코드가 많이 바뀌었는데 좋은 구조로 개선되었다고 생각이 드네요! 타입 쪽을 신경 많이 쓰신게 느껴져요. 몇 가지 간단한 코멘트만 남겨두었습니다.

기능은 잘 동작하네요!
해당 미션은 여기서 머지해도 괜찮을 것 같아요.
너무 고생 많으셨습니다.

다음 장바구니 미션도 파이팅이에요!

2023-03-11 06:41 UTC, InSeong-So commented on src/App.tsx
> +      </CardProvider>
👍

2023-03-11 06:41 UTC, InSeong-So commented on src/components/molecules/card-item/index.tsx
> +  }, []);
onClickButton이 undefined 일 수 있는데 그 대응책이 없어보여요!

2023-03-11 06:41 UTC, InSeong-So commented on src/components/molecules/input-container/index.tsx
> +      <div className={`${notInputBox ? '' : 'input-box'} ${className}`}>
`notInputBox`의 기본값을 `''`로 해두면 3항식을 제거할 수 있을 것 같아요👍

2023-03-11 06:41 UTC, InSeong-So commented on src/components/molecules/modal/index.tsx
> +  }, []);
이벤트 캡처링을 위해서만 존재하기에는 조금 과한 느낌이 있는데... 어떤 것을 의도하셨을까요?

2023-03-11 06:41 UTC, InSeong-So commented on src/components/organisms/register-card/ExpiredDate.tsx
> +    });
`cardDispatch`를 타입과 payload를 다 넘겨주는 것보다, useCardDispatch 내부에서 커스텀하게 이벤트를 셋해두면 어떨까요?

`setCardDispatch({ expiredDate: expiredDate.join('') });`

이런 식으로 type을 알 필요가 없어지게 만드는 거에요.

2023-03-11 06:41 UTC, InSeong-So commented on src/domain/typeGuard.ts
> +}
정규식으로 다 처리할 수 있지 않을까요?

2023-03-11 06:41 UTC, InSeong-So commented on src/domain/types.ts
> +export type TFourDigit = `${TSingleDigit}${TSingleDigit}${TSingleDigit}${TSingleDigit}`;
신선한 방식이네요! 타입 챌린지 같은 느낌입니다👍 이렇게 해서 typeGuard와 연결시키셨군요. 그럼으로써 좀 더 좋은 로직이 되었을까요?

2023-03-11 06:41 UTC, InSeong-So commented on src/domain/types.ts
>  }
모두가 undefined일 수 있다면, Partial 타입을 쓰는 것이 어떨까요?

2023-03-11 06:41 UTC, merged

2023-03-12 08:19 UTC, minhyeok0328 commented on src/components/molecules/modal/index.tsx
> +  }, []);
사실 이벤트 캡쳐링을 위해 해뒀습니다ㅎㅎ.. 저번에 피드백 주신 css로 user-select: none 속성을 줘서 간단하게 해결하도록 바꿔봐야 겠네요!

2023-03-12 08:26 UTC, minhyeok0328 commented on src/domain/types.ts
> +export type TFourDigit = `${TSingleDigit}${TSingleDigit}${TSingleDigit}${TSingleDigit}`;
타입스크립트를 공부하는 입장이라 잘은 모르겠지만.. 정규식 + 타입으로 한 번 더 검증해주니 좀 더 안정성이 좋아진 것 같습니다! 혹여나 정규식이 덜 꼼꼼하게 작성되어 예기치 못한 값이 들어가도 여기서 추가로 타입검증을 같이 해주니 이 후 값을 연산하거나 할 때도 더 맘이 놓이는 느낌입니다!