[클린코드 리액트 2기 김재원] 페이먼츠 미션 Step 1
next-step/react-payments pull request #91
Opened 2023-03-06 13:01 UTC by gptplayer

안녕하세요 우병님! 
리액트와 스토리북 모두 익숙하지 않아, 첫번쨰 스텝 일정부터 엄청나게 밀려버렸습니다.ㅠㅜ
하지만 이제 더 속도내서 스텝2와 스텝3를 이번주 안에 모두 완료하는걸 목표로 달려보려고 합니다.

CDD로 구현하고 싶었는데, CDD의 장점을 꼽히는 개발 생산성 향상, 유지 보수성 향상 등의 유용함을 느껴보지는 못한것 같아요. 현재는 스토리북으로 컴포넌트를 미리 보고, 테스트하는 정도로 활용한것 같습니다. 보다 작은 단위로 컴포넌트를 쪼개고 확장해 나가는 방향으로 써봐야 더 유용함을 느낄것 같은데, 이 부분은 스텝2~3에서 느끼기를 기대하고 있습니다.

## 📝 Requirements

### 필수 요구사항

- [x] Storybook 상호 작용 테스트
- [x] 재사용 가능한 Component 작성

### 카드 추가

- [x] `<` (뒤로가기) 버튼 클릭 시, 카드 목록 페이지로 이동한다.
- [x] 카드 번호를 입력 받을 수 있다.
  - [x] 카드 번호는 숫자만 입력가능하다.
  - [x] 카드 번호 4자리마다 `-`가 삽입된다.
  - [ ] 카드 번호는 실시간으로 카드 UI에 반영된다.
  - [x] 카드 번호는 앞 8자리만 숫자로 보여지고, 나머지 숫자는 `*`로 보여진다.
- [x] 만료일을 입력 받을 수 있다.
  - [x] MM / YY 로 placeholder를 적용한다.
  - [x] 월, 년 사이에 자동으로 /가 삽입된다.
  - [ ] 만료일은 실시간으로 카드 UI에 반영된다.
  - [x] 월은 1이상 12이하 숫자여야 한다.
- [x] 보안코드를 입력 받을 수 있다.
  - [x] 보안코드는 `*`으로 보여진다.
  - [x] 보안코드는 숫자만 입력가능하다.
- [x] 카드 비밀번호의 앞 2자리를 입력 받을 수 있다.
  - [x] 카드 비밀번호는 각 폼마다 한자리 숫자만 입력가능하다.
  - [x] 카드 번호 입력 시, `*`으로 보여진다.
- [x] 카드 소유자 이름을 입력 받을 수 있다.
  - [x] 이름은 30자리까지 입력할 수 있다.
  - [x] 이름 입력 폼 위에, 현재 입력 자릿수와 최대 입력 자릿수를 실시간으로 보여준다.
- [ ] (추가) 카드 값을 localStorage에 저장한다
- [ ] (추가) 카드 색상 + 카드 이름을 변경할 수 있다
- [ ] 카드 추가 완료시 카드 등록 완료 페이지로 이동한다.
  - [ ] localStorage 값으로 카드 등록 완료 페이지에서 입력한 값을 확인한다.

2023-03-06 16:59 UTC, woobottle requested changes
안녕하세요 재원님 
미션 수행하시느라 정말 고생 많으셨어요!!!
스토리 북 세팅은 정말 이쁘게 해주셨네요!! 

스토리북에서 일부 input은 입력이 되지 않는데 의도된 것인지 궁금해요!

더 수월한 리뷰를 위해 스토리북 배포와 프로젝트 배포 후 링크 첨부를 요청할 수 있을지 궁금해요!

몇 가지 코멘트 남겼으니 확인 부탁드릴게요~~!! 👍🏻

아래는 제가 기능 QA하면서 발견한 사항들인데 확인 한번 부탁드릴게요!

1. 카드 번호를 제거할때와 입력할때 조금 어색한 부분이 있어서 확인 요청 드려요~!!
2. 카드번호가 입력될때 4자리 마다 ‘-‘가  입력 되
는 것이 아니라 16자가 다 입력되어야 -가 삽입되는 것 같아요
3. 카드 번호에서 뒤의 8자리를 *로 변환 할때 16자리가 다 입력되고 나어야 바뀌는 것 같아요
4. 이름을 30글자를 입력받게 되면 글자가 카드 ui를 넘어 가는 것 같아요
5. 월을 입력할때 숫자를 하나만 입력하면 이후에는 문자가 입력 가능해요
6. 년을 입력할때 문자도 입력이 되요
7. 툴팁을 클릭했을때 보이는 ui에 수정이 필요할 것 같아요!


<img width="216" alt="Screenshot 2023-03-06 at 11 37 43 PM" src="https://user-images.githubusercontent.com/50283326/223178682-abf1b7a7-4491-4384-81d6-2da278313140.png">

https://user-images.githubusercontent.com/50283326/223178709-d08af291-d867-4678-b0ee-e94c4076946d.mov

2023-03-06 16:59 UTC, woobottle commented on src/pages/CardListPage.tsx
> +  cursor: pointer;
이런 디테일한 부분들 너무 좋은것 같아요

2023-03-06 16:59 UTC, woobottle commented on src/App.tsx
> +          <Route path="/card-add" element={<CardAddPage />} />
다른 path로 유저가 진입하게 되면 어떻게 될까요??!!

2023-03-06 16:59 UTC, woobottle commented on src/App.tsx
> +import CardListPage from "./pages/CardListPage";
페이지가 많아지면 Import 구문의 관리가 어려워 질것 같은데 혹시 방법이 있을까요??

2023-03-06 16:59 UTC, woobottle commented on src/contexts/PaymentsCardContext.tsx
> +
contextApi를 사용하셔서 구현하신 이유가 궁금해요
step1의 요구사항 중 어떤것 때문에 접목하셨는지 여쭤보고 싶어요

2023-03-06 16:59 UTC, woobottle commented on src/contexts/PaymentsCardContext.tsx
> +type CardContextType = {
number, Digits 등의 타입이 string으로 설정해주신 이유가 궁금해요 
변수명을 접하게 되면 숫자로 입력되길 예상이 되어서요

2023-03-06 16:59 UTC, woobottle commented on src/components/common/PaymentsCard.tsx
> +    color: "#575757",
color에 대한 정보들은 한곳에서 변수로 관리되면 어떨지 재원님의 생각이 궁금해요!!

2023-03-06 16:59 UTC, woobottle commented on src/components/common/PaymentsCard.tsx
> +  type?: "empty" | "small" | "big";
(궁금) small과 big을 나누는 기준은 무엇일까요??

카드 정보 입력 화면과 별칭 등록 화면일까요??

2023-03-06 16:59 UTC, woobottle commented on src/components/common/PaymentsCard.tsx
> +  background: ${({ type }) => cardSizes[type || "empty"].background};
${({ type = 'empty' }) => cardSizes[type].background};

(궁금) 혹시 destruct의 기본값 할당을 이용하면 가독성이 좀 더 확보되지 않을까 싶은데 의견이 궁금해요!

2023-03-06 16:59 UTC, woobottle commented on src/components/common/BackButton.tsx
> +
(궁금) 스타일 컴포넌트를 보통 컴포넌트의 상단에 작성하시는 것을 선호하시는 편인가요?? 

저는 스타일 컴포넌트는 return문 하단에 위치하는 것을 선호하는 데요
그 이유는 다음과 같아요 

style에 대한 정의는 보통 길어지기 유지기수 인것 같아요(린트, 프리티어 이슈)
현재의 구조에서는 컴포넌트가 거대해졌을때 가독성이 떨어지지 않을까 하는 생각이 들어요
우선순위가 높은 정보를 먼저 인식시켜주는 것이 좋지 않을까 생각해요

```
const Component = () => {. 
<BackButtonText>. 
   ~~~.  
</BackButtonText>.   
}

export default Component;    
    
const BackButtonText = styled.span``;    
   
```

2023-03-06 16:59 UTC, woobottle commented on src/components/common/BackButton.tsx
> +const BackButtonText = styled.span`
tag를 알맞게 잘 사용해 주시는 것 같아요!!

2023-03-06 16:59 UTC, woobottle commented on src/components/common/DefaultLayout.tsx
> +const DefaultLayout: React.FC<DefaultLayoutProps> = ({
DefaultLayout의 도입의도가 좋은것 같아요!

아래 사항들에 대한 의견이 궁금해요
1. 컴포넌트 이름을 변경하는게 어떨까요?? DefaultLayout에 Root, App등이 존재하니 리액트 전체 구조에 영향을 끼질것으로 기대가 되어요
2. Root, App등의 스타일드 컴포넌트 이름도 변경되는건 어떻게 생각하실지 궁굼해요

2023-03-06 16:59 UTC, woobottle commented on src/pages/CardAddPage.tsx
> +    if (handleGoBack) {
handleGoBack은 어떤 요구사항의 내용으로 추가하시게 되신것인지 궁금해요

2023-03-06 16:59 UTC, woobottle commented on src/pages/CardAddPage.tsx
> +  const [isAllInfoEntered, setIsAllInfoEntered] = useState(false);
isAllInfoEntered라는 새로운 상태의 정의보다는 
카드들의 상태를 정의하는 곳에서 계산해서 내려주는 형태는 어떻게 생각하실지 궁금해요

카드들의 상태를 이용하는 새로운 상태가 다른 위치에 정의되어 있어 관리 포인트가 늘어나는 것 같아요
새로운 상태로 추가하지 않아도 의도하신 바를 충족할 수 있지 않을까 해요

상태가 추가된다는 것은 아래의 의미를 가지고 있다고 생각해서 지양할 수 있는 상황에서는 지양하는게 좋다고 생각해요
1. 컴포넌트의 리렌더링 불필요한 유발 요소
2. 유지보수를 위한 관리포인트가 지대하게 늘어남


이에 대한 재원님의 의견도 궁금해요!!

2023-03-06 16:59 UTC, woobottle commented on src/pages/CardAddPage.tsx
> +      <CardSubmitButton disabled={!isAllInfoEntered} />
추상화 레벨이 잘 지켜진 것 같아요!

2023-03-06 16:59 UTC, woobottle commented on src/hooks/useCardPreview.tsx
> +  const ownerNameRegExp = useMemo(() => /[^\w\s]/gi, []);
useMemo를 사용하신 이유가 궁금해요

2023-03-06 16:59 UTC, woobottle commented on src/hooks/useCardPreview.tsx
> +      ownerName.replace(ownerNameRegExp, "").slice(0, 15) || "NAME"
15와 같은 것들은 상수로 관리되면 좋을지 재원님의 의견이 궁금해요

2023-03-06 16:59 UTC, woobottle commented on src/hooks/usePasswordFirstTwoDigits.tsx
> +  );
현재 구조에서는  passwordFirstTwoDigits대신 passwordFirstDigits / passwordSecondDigits로 변경하면 더 구조가 쉬워지지 않을가 생각이 들어요 

firstDigit, secondDigit라는 파생되어 진 상태의 추가가 없어도 되고
```
setFirstDigit(newValue);
    setPasswordFirstTwoDigits(
      newValue +
        (passwordFirstTwoDigits.length > 1 ? passwordFirstTwoDigits[1] : "")
    );
```

위의 로직이 더 간결해지지 않을까 싶어요

2023-03-06 16:59 UTC, woobottle commented on src/hooks/useCardNumberInput.tsx
> +  const { cardNumber, setCardNumber } = useContext(CardContext);
cardNumber도 firstCardNumber, secondCardNumber, thirdCardNumber, fourthCardNumber로 관리되면 현재 구조에서 코드가 간결해 질것 같은데 어떻게 생각하실지 궁금해요!

각각에 대한 validation, regex, 상태 추적도 수행할 수 있구요
요구사항에 대해 더 유연하게 대응할 수 있지 않을까 싶어요

이에 대한 재원님의 의견이 궁금해요!

2023-03-06 16:59 UTC, woobottle commented on src/pages/CardAddPage.tsx
> +      cardNumber.length === 16 &&
지금 validation을 따로 가져가는 구조로 이해가 되어요 

1. 값의 입력에 대한 validation은 훅 내부
2. 값의 길이에 대한 validation 여부는 이곳 
3. 폼 제출에 대한 validation 여부는 useCardSubmit에서 1,2 번의 결과값을 가지고 제어

관리 포인트가 많다는 것이 많다는 제 의견에 동의하시는 지 궁금하고 
이 구조를 변경할 수 있을지 궁금해요

2023-03-06 16:59 UTC, woobottle commented on src/contexts/PaymentsCardContext.tsx
> +});
폼에 입력 종류가 추가될 때마다 state, setState, hook이 매번 추가되어야 하고 
변경사항 발생시 여러 파일들에 변경작업을 해야 하는데요 

각각의 state, setState, hook으로 구성하시면서 어떤 고민을 하셨고 
현재 구조에서 가져갈 수 있는 장점과 단점은 어떠한 게 있으시다고 생각하실지 재원님의 의견이 궁금해요!!!

2023-03-06 16:59 UTC, woobottle commented on src/components/CardSubmitButton.tsx
> +    props.disabled ? "not-allowed" : "pointer"};
disabled를 사용하는 property가 계속 추가되면 type 정의에 대한 코드가 계속 중복될것 같아요
혹시 방지할 수 있는 방법이 있을까요??

ex)
```
 color: ${(props: { disabled: boolean }) =>
    props.disabled ? "#ccc" : "#000"};
  cursor: ${(props: { disabled: boolean }) =>
    props.disabled ? "not-allowed" : "pointer"};
  background-color: ${(props: { disabled: boolean }) =>
    props.disabled ? "#ccc" : "#000"};
border-radius: ${(props: { disabled: boolean }) =>
    props.disabled ? 5 : 10}px;
```

2023-03-07 02:53 UTC, gptplayer commented on src/pages/CardListPage.tsx
> +  cursor: pointer;
감사합니다 😄

2023-05-01 16:21 UTC, merged