[클린코드 리액트 2기 양아름] 페이먼츠 미션 Step 2
next-step/react-payments pull request #92
Opened 2023-03-07 16:39 UTC by areumsheep

안녕하세요 우병님 :)
Step3 함께 제출하려다가 너무 늦을 것 같아 미리 제출합니다..

> 커밋 내역을 분리하는 방법을 잘 모르겠네요.... Files changed로 확인 부탁드립니다...!

## 링크
- [배포 링크](https://react-payments-git-step-2-areumsheep.vercel.app/card-list)
   - 아래 popup은 스크린샷 참고하시어 사라지게 할 수 있습니다.
    <img width="305" alt="image" src="https://user-images.githubusercontent.com/48716298/223526022-5667f18a-1cd6-40a4-9ba4-a377411624b4.png">

- [스토리북 링크](https://step-2--63f3d360072418df2bea01bd.chromatic.com/)
    - 모달이 추가되었습니다.
- [Figma 링크 (실제 구현과 약간의 차이가 있습니다!)](https://www.figma.com/file/Al9b1617ZK29sgqu6m9WwZ/React-Payment?node-id=0%3A1&t=epiaqOP9F7SGmpsA-1)

## 궁금한 점

### Context API 사용 방법
`src/contexts/CardListProvider.tsx` 에서 Provider에 대한 함수들까지 `CardListContext` 안에 담고 있는데 함수들을 분리하기 위해 어떻게 하는 게 좋을지 의문입니다... 우병님께선 어떻게 하시는 지 궁금해요! 👀 

### Modal.Trigger
모달의 로직을 재활용하기 위하여 `Modal.Trigger`라는 부분으로 event가 일어나는 컴포넌트를 받도록 구현하였어요. 요런 방법은 우병님께서 생각하시기에 어떠신 지 궁금합니다 :)
참고한 라이브러리 입니다...! https://www.radix-ui.com/docs/primitives/components/select

2023-03-08 16:29 UTC, woobottle requested changes
아래 머지 커멘트에 추가해두었어요!!!

2023-03-08 16:29 UTC, woobottle commented on src/components/@common/Modal/ModalProvider.tsx
> +  const { isOpened, open, close } = useToggle();
useToggle에서 내려주는 변수들 open, close의 변수명이 바뀌는 건 어떨까요??

ex. setToggleOpen, setToggleclose

2023-03-08 16:29 UTC, woobottle commented on src/components/@common/Tooltip/Tooltip.tsx
> +      {isOpened && (
좋은것 같아요!

2023-03-08 16:29 UTC, woobottle commented on src/components/CreditCard/CreditCard.tsx
> +        {nickname || findCardDefaultName(color!)}
예외처값 설정은 항상 좋은것 같아요!!

color에 대한 타입 강제는 type guard문이나 기본값 설정등으로 제외할 수 잇을까요??
프로덕트를 확장할때 장애물이 되거나 런타임에 에러가 날때 추적이 너무 어려워지는 경우가 대게 있을 수 있다고 생각해요

이에 대한 아름님의 의견도 궁금해요!

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/CardDetail.tsx
> +        <FormFieldControl>
👍🏻

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/CardDetail.tsx
> +            type="text"
이곳에서 ref를 접목하시게된 의도가 궁금해요!

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/CardDetail.tsx
> +    updateCardNickname(card.id!, value);
card.id! 타입 확정에 대한 아름님의 의견이 궁금해요!!

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/CardDetail.tsx
> +          <Button type="submit" onClick={handleCardNickname} className="w-47">
ux 관점에서 삭제 혹은 수정 액션 후에 모달이 내려가면 어떨까 하는데 

이에 대한 아름님의 의견이 궁금해요!!

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/CardDetail.tsx
> +            type="submit"
예전에 button의 default Type이 무엇이냐고 질문을 받아본적이 있어요!

2023-03-08 16:29 UTC, woobottle commented on src/components/ModalContent/SelectCompany.tsx
> +  grid-template-columns: repeat(4, 1fr);
👍🏻

2023-03-08 16:29 UTC, woobottle commented on src/hooks/useCardData.ts
> +const initalData: CreditCardType = {
나중에 getInitialCardData와 같이 리턴 함수를 생성하시면 테스트 코드 짤때 유용하게 이용하실 수 있으실거에요!!

2023-03-08 16:29 UTC, woobottle commented on src/hooks/useToggle.ts
> +    close,
위에서 언급드렸는데 아름님의 의견이 궁금합니다!

//  는 삭제 부탁드려요~~

2023-03-08 16:29 UTC, woobottle commented on src/pages/CardListPage.tsx
> +          onClick={() => push('/card-registration')}
이건 요즘 많이 느끼고 있는건데 프로덕트가 커지면 네비게이션 같은 경우들은 
한곳에 모아두고 추상화된 메서드를 내려주는게 정말 꼭 필요한것 같아요 ㅜㅜ

ex. onClick={navigateToCardRegistration}

2023-03-08 16:29 UTC, woobottle commented on src/pages/CardListPage.tsx
> +                  key={index}
[키 값에 인덱스는 최후에!!](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318)

2023-03-08 16:29 UTC, woobottle commented on src/contexts/CardListProvider.tsx
> +    data['id'] = id.current;
전달받은 데이터의 값에도 영향이 가게 될것 같은데 {...data, id: id.current} 와 같은 형태로 새로운 값을 생성한 후 배열에 추가해주는 것은 어떻게 생각하실지 궁금해요

2023-03-09 14:42 UTC, woobottle approved these changes
바쁘신 와중에 열심히 수행해 주셔서 정말 감사합니다!!!
이번에 ux적으로 고려하신 부분 피그마 작업해주신 부분이 인상깊었어요(저도 배우고 싶네요)
코멘트 남겨두었고 아래는 질문 해주신 내용들에 대한 제 답변입니다!

> Context API 사용 방법
src/contexts/CardListProvider.tsx 에서 Provider에 대한 함수들까지 CardListContext 안에 담고 있는데 함수들을 분리하기 위해 어떻게 하는 게 좋을지 의문입니다... 우병님께선 어떻게 하시는 지 궁금해요! 👀

지금의 형태라면 아름님과 같이 작성했을것 같아요
더 커진다면 커스텀 훅으로의 분리나 비즈니스 로직들을 전부 분리해 버릴 것 같아요
이건 저만의 철칙인데 분리를 절대 먼저 하거나 고려하지 않아요
우선 사용되는 곳에서 제일 가까운곳에 작성을 하고
다른 곳에서 공통사용이 필요하게 될때 하나씩 분리해 나가는 것 같아요

역으로 아름님이 함수들을 분리하시려고 하셨던 이유가 궁금해요

> Modal.Trigger
모달의 로직을 재활용하기 위하여 Modal.Trigger라는 부분으로 event가 일어나는 컴포넌트를 받도록 구현하였어요. 요런 방법은 우병님께서 생각하시기에 어떠신 지 궁금합니다 :)

제 사견은요 결국 핵심은 모달을 열어주는것 하나인 것 같아요
Modal.Trigger가 쉽게 와닿지 않는것 같아요
Modal을 open하는 액션 메서드를 전달하고
현재 Modal.Trigger 하위에 있는 컴포넌트 들에 모달 오픈 액션 메서드를 전달하는게 어떨까 하는데
이에 대한 아름님의 의견이 궁금해요
해당 부분 개발하면서 어떤 고민을 하셨는지도 궁금하구요!!

2023-03-09 14:43 UTC, merged

2023-06-25 07:27 UTC, areumsheep commented on src/components/@common/Modal/ModalProvider.tsx
> +  const { isOpened, open, close } = useToggle();
이 코멘트를 봤을 땐 '충분히 명시적인데 왜 수정해야 할까?' 라는 생각이 들었는데 회사를 다니며 간단한 함수명을 사용하지 않게 되었어요.
우병님의 코멘트 또한, 함수명 (= 변수명)이 단순하면 겹칠 수 있기에 수정하라는 의미로 보이는데 맞을까요?

2023-06-25 07:53 UTC, woobottle commented on src/components/@common/Modal/ModalProvider.tsx
> +  const { isOpened, open, close } = useToggle();
저는 추상화가 너무 많이 되어 있다고 생각했었던 것 같아요
open, close가 같은 provider 내부에서 사용될 것 같고 (정의된 곳과 사용되는 곳의 거리가 멀어짐)
단어만 보았을때 모달에 관한 정보인지 알기 어렵지 않을까 싶었던것 같아요

2023-06-26 14:11 UTC, areumsheep reviewed
저의 모든 컴포넌트들은 Radix-ui를 가장 많이 참고하여 만들어졌어요!
`Modal.Trigger`도 [Radix를 참고](https://www.radix-ui.com/docs/primitives/components/alert-dialog)해서 만들어졌는데, 이벤트가 발생할 곳이라는 뜻을 담고 있었어요.

> Modal.Trigger 하위에 있는 컴포넌트 들에 모달 오픈 액션 메서드를 전달하는게 어떨까 하는데 이에 대한 아름님의 의견이 궁금해요

저도 요게 가장 이해하기가 쉬울 것 같은데 어떤 방법이 가장 아름다울지 모르겠어서 일단 Context에서 함수를 받아서 사용하는 걸로 수정하였습니다!
점차 더 진행해보면서 떠오르는 아이디어 있으면 바로 적용해보겠습니다.

**너무 늦게 코멘트를 확인했는데도 답변 남겨주셔서 감사해요! ㅋㅋㅋ**

2023-06-26 14:11 UTC, areumsheep commented on src/components/CreditCard/CreditCard.tsx
> +        {nickname || findCardDefaultName(color!)}
동의합니다! 벌써 몇 달 전이라 잘 기억은 안 나지만... 빨리 개발하려고 단언을 사용했던 것 같아요.
그에 대해 좋은 의견 감사드립니다 bb

2023-06-26 14:11 UTC, areumsheep commented on src/components/ModalContent/CardDetail.tsx
> +    updateCardNickname(card.id!, value);
위의 우병님 말씀에 동의합니다! 13번째 줄의 if 문에서 함께 확인을 하는 것이 좋을 것 같아 수정했습니다.

2023-06-26 14:11 UTC, areumsheep commented on src/components/ModalContent/CardDetail.tsx
> +            type="text"
카드 별칭은 제어 컴포넌트로 설정할 필요가 없기에 비제어 컴포넌트를 위하여 사용하였습니다... 
요건 이미 아실만한 답변같은데 혹시 어떤 것을 위한 질문일까요?

2023-06-26 14:11 UTC, areumsheep commented on src/components/ModalContent/CardDetail.tsx
> +            type="submit"
오! button의 default type이 submit 이군요! 좋은 정보네요👍 
다만 최근에는 가독성을 위해 적는 건 나쁘지 않다고 생각하기에 삭제하진 않겠습니당당

2023-06-26 14:11 UTC, areumsheep commented on src/contexts/CardListProvider.tsx
> +    data['id'] = id.current;
오오!!!! 요번에 타입 다시 설정하면서 수정해보았습니다!
캬 예리한 리뷰 감사해요!

2023-06-26 14:11 UTC, areumsheep commented on src/components/ModalContent/CardDetail.tsx
> +          <Button type="submit" onClick={handleCardNickname} className="w-47">
동의합니다! 짚어주셔서 감사해요!

2023-06-26 14:11 UTC, areumsheep commented on src/hooks/useToggle.ts
> +    close,
말씀해주셨던 의견엔 동의하여 수정하였습니다!

https://github.com/radix-ui/primitives/blob/main/packages/react/alert-dialog/src/AlertDialog.tsx#L286
`//`는 변수와 함수를 구분하는 구분자로 사용하기 위해 작성하였습니다.
다만 지금은 값이 많지 않기에 없는 것이 더 좋겠다는 생각이 들지만, 있어도 보기에 불편하지 않기에 유지하겠습니당~

2023-06-26 14:11 UTC, areumsheep commented on src/pages/CardListPage.tsx
> +          onClick={() => push('/card-registration')}
![image](https://github.com/next-step/react-payments/assets/48716298/f471ca06-fcbd-4b03-9e43-c2b03a3679b3)
엄엄... 요렇게 추론이 되는데도 각 페이지마다 함수를 만들어서 사용하는 것이 맞다고 생각하시는 걸까유?!
제가 이해하기로는 `navigateToCardRegistration`는 아래와 같이 만들어질 것 같은데, 요건 중복된 코드를 무한정 만드는 건 아닐까 생각이 드네용...

```typescript
/** Card 등록 페이지 */
export const navigateToCardRegistration = () => {
  push('card-registration');
}
/** Card 목록 페이지 */
export const navigateToCardList = () => {
  push('card-list');
}
```

2023-06-26 14:11 UTC, areumsheep commented on src/pages/CardListPage.tsx
> +                  key={index}
헛 [예제](https://jsbin.com/wohima/edit?output)를 보니까 확 오네요... 감사합니다...