[클린코드 리액트 2기 우경준] 페이먼츠 미션 Step 3
next-step/react-payments pull request #98
Opened 2023-03-19 01:53 UTC by Jay-WKJun

안녕하세요 준일님!

페이먼츠 마지막 step 잘 부탁드리겠습니다!

PR 후에도 피드백 주시거나 필요한 부분이 있다면 계속해서 추가해나갈 예정입니다.

### 실행 방법

```
# install
npm i

# run
npm start
```

[스토리북 배포 URL](https://www.chromatic.com/library?appId=64153ae64ded91dc4965aab5)

# 주요 변경 사항

- 카드 생성 페이지의 storybook을 완성했습니다.
- 새로운 기능이 다른 로직과 섞이지 않도록 노력했습니다.

## requirements

- 유효성 검증
- [x] 유효성 검증 실패에 대한 UI/UX 추가
- [x] 유효한 값 입력시 다음 필드로 Input Focusing

- 카드
- [x] 카드 번호 앞 8자리로 카드사를 추정하여 그 테마를 카드 UI에 반영한다.
- [x] 카드사를 선택하지 않아도 모달을 닫을 수 있다.
- [x] 카드사가 선택되고 유효한 카드 번호 16자리를 모두 입력하면, 자동으로 만료일로 focus된다.
- [x] 별칭 수정 가능

- 보안코드 툴팁
- [x] 클릭 시, 보안코드 관련 안내 메시지를 보여준다.
- [x] focusout시, 툴팁이 닫힌다.

- 가상 키보드
- [] 마스킹 처리된 값 입력시 사용
- [] 숫자를 랜덤으로 배열

# 질문

- Bottom-up 컴포넌트 개발 방식을 통한 재사용 가능한 추상화된 컴포넌트를 만드는 것이 이번 TDD 과정의 목표였습니다. 노력했지만, 잘 적용됐는지 궁금합니다.

- 함수와 hook의 역할이 적절하게 나뉘었을까요?
  
  책임이 명확하고 추상화된 함수부터 조금씩 구체화하면서 비즈니스 로직을 구체화하도록 노력했습니다.

- Application의 전체적인 설계는 어떻게 생각하시는지 궁금합니다.

  각 input마다 객체를 두고 자신의 상태를 스스로 판단해서 결과를 내도록 했습니다.

2023-03-22 15:47 UTC, JunilHwang requested changes
안녕하세요 경준님! 리뷰가 너무 늦어졌네요 ㅠㅠ 죄송합니다 🙏 (요즘 현생에 너무 치여 살아서.. ㅎ)
작업량이 무척 많네요. 150개의 파일이 변경되었다니!

음... 일단 전체적으로 너무 추상화 레이어가 깊어요.

- 값 하나에 타입 하나를 매칭하고
- 해당 값을 쓰는 state가 있고
- state의 context가 있고
- state의 dispatch api가 있고
- state를 사용하는 storage가 있고
- storage를 저장해서 사용하는 localStorage가 있고
- localStorage를 저장하는 externalStorage가 있고
- 각각의 state에 대한 각각의 로직을 정의해서 context로 관리하고
- state에 대한 pojo가 있고, pojo에 대한 type이 있고, ...

경준님이 아닌 다른 사람이 이 코드를 보고 적응하는게 무척 어렵겠구나... 라는 생각이 들었답니다 ㅎㅎ
어느정도 설계 다이어트를 해야하지 않을까요?

이럴 때 필요한건, 경준님이 설계하신 것들에 대해 그림을 한 번 쭉 그려보시면 좋답니다!

그리고 type 이름에 대한 일관성이 필요할 것 같아요!
어딘가에는 prefix로 `T`를 붙이고 어딘가에는 안 붙이고 있고, interface의 suffix로 type을 쓰는 등 네이밍 컨벤션이 뒤죽박죽이라서요!

그리고 사용성에 대한 피드백을 남기자면

https://user-images.githubusercontent.com/18749057/226959256-f475c036-b532-49d1-b055-48a70c86d69e.mov

현재 작성중인 input에 대해 validation을 해야하지 헷갈리지 않을 것 같아요..! 혹은 그냥 전체 input에 대해 다 표시를 해준다거나?

<img width="208" alt="image" src="https://user-images.githubusercontent.com/18749057/226959640-b3eb484c-9012-463f-a6d0-c1f64037db52.png">

만료일 같은 경우, `12년 12월`이 현재 날짜 이전이기 때문에  validation message를 표기해야 할 것 같습니다.

---

일단 지금 필요한건 코드의 복잡도를 낮춰야할 것 같아요..!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/Card.tsx
> +export const Card = memo(function Card({
원래 익명함수였는데, Card라는 이름을 지정한 이유가 있을까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/Card.tsx
> +  cardNickname?: TCardNicknameProp;
하나로 합쳐서 표현할 수 있지 않을까요?
```tsx
card?: Record<CardDTO>
```
이런 느낌으로여!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/types.ts
> +export type TCardNicknameProp = string | undefined;
```tsx
type TOptionalString = string | undefined;
```
이걸로 퉁쳐도 되지 않을까 싶어요!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/Card.tsx
> +            <CardExpireDate expireDates={cardExpireDate} />
```tsx
          <CardNumbers value={cardNumbers} />
          <div className="card-bottom__info">
            <CardOwnerName value={cardOwnerName} />
            <CardExpireDate value={cardExpireDate} />
```
각각의 컴포넌트 입장에서는 단순하게 value로 볼 수 있지 않을까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/Card.tsx
> +      {disableNickname || <CardNickname nickname={cardNickname} />}
여기도 동일합니다!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/CardNumbers.tsx
> +  const isHide = type === 'password';
`isHide`라는 네이밍은 함수에 어울릴 것 같아요~
지금은 `hided` 혹은 `masked` 처럼 표현하면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/CardNumbers.tsx
>  }
앞선 내용과 동일합니다!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/CardNumbers.tsx
>    return value.split('').map((cardNum) => (isHide ? '*' : cardNum));
```tsx
return isHide ? "*".repeat(value.length) : value;
```
이렇게 표현하면 더 간단하겠네요!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Card/CardOwnerName.tsx
> +}
```tsx
const DEFAULT_OWNER_NAME = 'NAME';

export function CardOwnerName({ ownerName = DEFAULT_OWNER_NAME }: CardOwnerNameProps) {
  return <StyledCardOwnerName className="card-text card-name-spacing">{ownerName}</StyledCardOwnerName>;
}
```
아예 props에서 default 값을 지정하는 방법도 있답니다!

2023-03-22 15:47 UTC, JunilHwang commented on src/components/ConditionalComponentWrapper/ConditionalComponentWrapper.tsx
>    if (!isRender || !children) return null;
여기서 쓰이는 `isRender`도 함수에 어울리는 이름 같아요~

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Portal/Portal.tsx
> +type ElementOrNull = Element | null;
`OptionalElement` 처럼 표현하면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/components/Portal/Portal.tsx
>  }
getContainer인데 인자가 container 여서 함수의 동작을 예측하기가 어려울 것 같아요!

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useCardListWithLocalStorage/useCardListWithLocalStorage.ts
> +import { useCardContextApiSelector } from '@/stores/CardContext';
```tsx
import { CardStore, useCardContextApiSelector } from '@/stores';
```
이렇게 불러올 수 있도록 해주면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/routes.ts
> +  createCardNickname: (cardId?: number | string) => (cardId ? `${routes.nickname}/${cardId}` : routes.nickname),
이 메소드는 안쓰이는 것 같아요~

2023-03-22 15:47 UTC, JunilHwang commented on src/router.tsx
>  function Router() {
6 ~ 8 번째 줄을에서 Import 해오는게 무척 어색한데요,
```tsx
import { CardList, CardCreator, CardNicknameSetter } from '@/pages';
```
이렇게 가져올 수 있도록 해보면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/App.tsx
>  import Router from './router';
router가 App.tsx와 같은 폴더에 있기보단, router라는 폴더를 만들어서 관리해주면 더 좋을 것 같아요!

2023-03-22 15:47 UTC, JunilHwang commented on src/App.tsx
>  import { ErrorContextProvider } from './stores/ErrorContext';
이쪽 import도 합칠 수 있겠네요~

2023-03-22 15:47 UTC, JunilHwang commented on src/utils/utils.ts
> +}
`convertStringToNumber(numberString: string)`
처럼 표현해주면 더 좋을 것 같아요!

2023-03-22 15:47 UTC, JunilHwang commented on src/utils/object.ts
> +type ObjectType<T> = { [key: string]: Array<T> };
`TObjectArrayMap` 처럼 표현하면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/utils/object.ts
> +export function mapObjectValues<T, K extends { [key: string | symbol]: unknown }>(
`mapObject` 처럼 표현해도 좋을 것 같네요..!

2023-03-22 15:47 UTC, JunilHwang commented on src/types/types.ts
> +export interface InputStateType<T = string> extends CommonInputStateType {
interface에도 `I` 라는 prefix를 붙여주면 어떨까요?
`ICommentInputState` `IInputState` 처럼요!

2023-03-22 15:47 UTC, JunilHwang commented on src/types/types.ts
> +}
여기에 선언된 type을 보면서 느낀게,

브라우저에 종속적이지 않은 domain type이 있을 것이고
브라우저(reacrt)에 종속적인 type이 있을 것 같아요.

이런 것들을 구분해서 type을 관리해주면 더 좋지 않을까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/types/types.ts
> +  ref?: HTMLInputElement | null;
어차피 CommonInputState에 선언되었기 때문에 다시 선언할 필요는 없지 않을까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/types/types.ts
> +}
이 type을 보면서 느낀건, 이 type을 사용하는 대상은 굉장히 많은 역할을 수행하겠구나... 라는 느낌입니다.
InputState인데 함수를 갖는건 왜일까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/cardStore.ts
> +    }
type을 case로 구분하기보단... 더 명확한 행위(action)을 정의하면 좋을 것 같아요!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/cardStore.ts
> +  return { ...store };
여기서 return할 때도 clone을 해주면 어떨까 싶네요!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/cardStore.ts
> +export const ApiContext = createContext<ApiContextType>(null);
store와 context는 다른 개념이라고 생각되는데요,
파일 이름을 `cardContexts` 처럼 표현하면 어떨까 싶어요..!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/cardStore.ts
> +type ApiContextType = DispatchContext<Dispatch>;
reducer에 대한 내용을 아예 다른 파일로 분리하면 어떨까 싶기도 하네요.

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/cardStore.ts
> +export const ApiContext = createContext<ApiContextType>(null);
`api context` 라는건 너무 추상적인 이름 같아요..!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/useSelectors.ts
> +}
selector는 redux에서 쓰이는 용어 같은데, 지금은 context에서 가져오고 있기 때문에
- useCardContext
- useCardContextApi
처럼 표현하면 어떨까 싶어요!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/useSelectors.ts
> +import { ApiContext, CardContext } from './cardStore';
ApiContext도 `CardApiContext` 처럼 표현하면 더 좋을 것 같네요!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/CardContext/CardStates/utils.ts
> +}
`asdf`보다 명확한 이름이 필요할 것 같아요!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/ErrorContext/errorStore.ts
>  export const initialErrorStore: ErrorStore = {
이미 type을 정의했기 때문에 const로 단언하지 않아도 될 것 같아요. 반대로, 단언을 했기 때문에 type을 지정하지 않아도 될 것 같습니다!

2023-03-22 15:47 UTC, JunilHwang commented on src/stores/ErrorContext/useErrorContextSelectors.ts
> +}
파일 이름을 `errorContextHooks` 로 표현해보면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useLocalStorage/useLocalStorage.ts
>  }
지금 localStorage를 사용하기위해서

ExternalStore + useExternalStore > LocalStorage + useLocalStorage

이런 단계로 추상화가 되어있는데요,
너무 오버엔지니어링이 아닌가..? 싶은 생각이 드네요 ㅠㅠ

그리고 storage를 쓰는 부분도 hook으로 추상화를 굳이 해야할까 싶어요.

 hook > service > storage
 
차라리 이런 추상화를 해보면 어떨까요?

service에는 localStorage, sessionStorage, rest api 등 다양한 것들이 올 수 있는거죠.
그리고 hook에서는 service를 가져다 쓰면 되지 않을까 싶습니다.

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useLocalStorage/LocalStorage.ts
> +  }
인자 이름이 string인건 어색하네요!

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useExternalStore/useExternalStore.ts
> +}
hook 이름은 external인데 return은 localStore라서 어색해보여요!

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useExternalStore/ExternalStore.ts
> +    });
store를 넣고 빼는게 비동기 작업일필요가 있을까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useLocalStorage/LocalStorage.ts
> +  }
set으로 remove까지 하는건 불필요한 과정 같아요..!

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useExternalStore/ExternalStore.ts
> +  }
storage에 store를 저장하는 개념인 것 같은데..
store도 storage처럼 어떤 "저장소"의 역할을 하는건데
"저장소"를 "저장소"에 저장하는 느낌이라서 뭔가 싶어요..! 이해하기가 어렵다고 해야하나..?
차라리 store가 아니라 data나 state로 표현하면 어떨까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useGetInvalidInputState/useGetInvalidInputState.ts
> +  );
이게 category와 어떤 관련이 있는 데이터일까요?

2023-03-22 15:47 UTC, JunilHwang commented on src/hooks/useGetErrorMessage/useGetErrorMessage.ts
> +export function useGetErrorMessage(inputState?: ObjectWithKey | ObjectWithKey[]) {
`useErrorMessage` 처럼 표현하는게 좋을 것 같아요.
getter를 반환하는게 아니라 value를 반환하는거라서요!

2023-03-23 05:45 UTC, Jay-WKJun commented on src/components/Card/Card.tsx
> +export const Card = memo(function Card({
컴포넌트의 이름을 특정하기 위해 적었습니다.

React dev tool로 렌더링 screenshot을 할 때, 익명함수를 넣으면 어떤 컴포넌트인지 이름이 없어 특정되지 않기 때문입니다.

2023-03-25 10:46 UTC, Jay-WKJun commented on src/components/Card/Card.tsx
> +            <CardExpireDate expireDates={cardExpireDate} />
그러네요! interface도 통일되고 훨씬 좋은거같네요!

2023-03-25 10:48 UTC, Jay-WKJun commented on src/components/Card/CardOwnerName.tsx
> +}
아 ㅋㅋㅋ 깜빡했네요! 감사합니다.

2023-03-25 10:50 UTC, Jay-WKJun commented on src/components/Portal/Portal.tsx
> +type ElementOrNull = Element | null;
오 너무 좋은 네이밍이네요! 감사합니다!

2023-03-25 10:51 UTC, Jay-WKJun commented on src/components/Portal/Portal.tsx
>  }
넵 한번 고쳐보겠습니다! 이 부분은 가장 추상화된 컴포넌트인 만큼 신경써보겠습니다.

2023-03-25 10:55 UTC, Jay-WKJun commented on src/hooks/useCardListWithLocalStorage/useCardListWithLocalStorage.ts
> +import { useCardContextApiSelector } from '@/stores/CardContext';
이 부분은 일부러 CardContext가 드러나도록 했습니다.
CardContext에 해당하는 요소임을 나타내기 위함입니다.

각 Context마다 export해주는 요소들이 비슷하기 때문에, 해당 요소가 어떤 Context에서 import했다는 것을 명확하게 하고 싶었습니다.

2023-03-25 10:57 UTC, Jay-WKJun commented on src/routes.ts
> +  createCardNickname: (cardId?: number | string) => (cardId ? `${routes.nickname}/${cardId}` : routes.nickname),
넵 ㅠㅠ 감사합니다.

Dead code가 조금씩 보이네요.

일정에 쫒기기도 했고, 설계도 너무 복잡해서 놓친 부분이 많은 것 같습니다,,,

다시 한번 신경쓰도록하겠습니다 ㅠㅠ

2023-03-25 10:59 UTC, Jay-WKJun commented on src/utils/utils.ts
> +}
change보단 convert가 좀 더 명확하네요 👍

2023-03-25 11:01 UTC, Jay-WKJun commented on src/types/types.ts
> +}
오,,, 이건 한번 리팩토링하면서 구분되는 타입이 있다면 한번 적용해보겠습니다.

2023-03-25 11:03 UTC, Jay-WKJun commented on src/types/types.ts
> +}
다시 되돌아보니 준일님 말씀처럼 객체가 너무나도 큰 것 같습니다 ㅎㅎ

그리고 대부분의 메소드들이 컴포넌트에서 사용되기 위해 정의되는데, 정의하는 곳과 사용하는 곳이 멀어지니 코드를 이해하는데도 꽤나 방해될 것 같다는 생각이 들었습니다,,,,ㅎㅎ

2023-03-25 11:04 UTC, Jay-WKJun commented on src/types/types.ts
> +}
함수를 갖는건 일종의 객체 메소드로서 기능하기 위함입니다.

value를 객체가 가지고 있으니 그것을 메소드에 의해 스스로 조작하고 판단해 되돌려 주는 것을 생각했습니다.

정말 하나의 Input Element에서 작동하는 객체를 만든 것입니다.

2023-03-25 11:10 UTC, Jay-WKJun commented on src/types/types.ts
> +}
하지만, value를 조작하거나 판단하는 로직들이 결국 각자의 컴포넌트 말단에서 사용되는 것이기 때문에, 컴포넌트에 value 조작과 판단 로직을 두어도 좋을 것 같다는 생각을 했습니다.

로직의 사용처와 선언부가 가까우면 좀 더 코드를 읽고 이해하기 쉬울 것 같습니다.

컴포넌트가 완성된 비즈니스 로직을 가지니 CDD에도 더 적합한 방법이라고 생각됩니다.

2023-03-25 11:13 UTC, Jay-WKJun commented on src/stores/CardContext/cardStore.ts
> +export const ApiContext = createContext<ApiContextType>(null);
오... 용어를 좀 더 명확히 해야겠군요.

좀 더 알아보겠습니다.

2023-03-25 11:14 UTC, Jay-WKJun commented on src/stores/CardContext/CardStates/utils.ts
> +}
앗,,, 죄송합니다 🥲

2023-03-25 11:15 UTC, Jay-WKJun commented on src/stores/ErrorContext/useErrorContextSelectors.ts
> +}
오! 준일님은 문학작가시군요 감사합니다. 👍

2023-03-25 11:17 UTC, Jay-WKJun commented on src/hooks/useLocalStorage/useLocalStorage.ts
>  }
백엔드에서 많이 봤던 개념 같네요! 너무 좋은 방법인 것 같습니다 👍

감사합니다!

2023-03-25 11:18 UTC, Jay-WKJun commented on src/hooks/useExternalStore/ExternalStore.ts
> +    });
fetch로 바뀔것을 예상하고 만들었는데 말씀대로 굳이 그럴 필요는 없어보이네요!

2023-03-25 11:19 UTC, Jay-WKJun commented on src/hooks/useGetInvalidInputState/useGetInvalidInputState.ts
> +  );
card 정보들의 종류들을 한번에 묶으려고 했습니다.

그래서 card 정보의 category(종류)라는 네이밍이 탄생했습니다 ㅎㅎ

네이밍이 직관적이지 않은 것 같으니 좀 더 고민해보겠습니다!

2023-03-25 11:36 UTC, Jay-WKJun commented on src/hooks/useExternalStore/ExternalStore.ts
> +  }
오,,, 그러네요 ㅠㅠ

네이밍 정말 어렵네요!

감사합니다!

2023-03-29 06:25 UTC, Jay-WKJun commented
안녕하세요. 준일님!
리뷰 반영 및 수정되어서 리뷰 재 요청드립니다.

다시 살펴보니 정말 보기 어려운 코드였는데, 😭 성심성의껏 리뷰해주셔서 진심으로 감사합니다. 🙏

(시연 영상)

# 변경점

객체의 책임을 적절하게 분산하고 추상화 레이어를 줄여 설계를 최대한 알기 쉽도록 변경했습니다.

(말씀 주신 의존관계 다이어그램이 개선에 큰 도움이 되었습니다! 👍) [피그잼 링크](https://www.figma.com/file/Ir106JaRR3ULw5TH3hXMOB/TDD%2C-%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C-with-React---%ED%8E%98%EC%9D%B4%EB%A8%BC%EC%B8%A0-%EB%AF%B8%EC%85%98-%EC%84%A4%EA%B3%84%EB%8F%84-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8?node-id=0%3A1&t=qBMfbHt3mvnWPS5u-1)

**개선된 설계에 대한 준일님의 의견이 궁금합니다!**

이외 UX면에서 리뷰주신 AutoFocus 또한 변경했습니다.

## card store 설계 변경

객체 생성에 필요한 추상화 레이어를 줄였습니다.

전 | 후
--- | ---
<img src="https://user-images.githubusercontent.com/40374023/228439955-e6a942f7-dc1a-41fc-8cb7-70cd6aae1204.png" /> | <img src="https://user-images.githubusercontent.com/40374023/228439965-233b24e5-10a2-40bb-8cbf-428018364ca7.png" />

### input model의 객체 역할을 컴포넌트에 분담

"입력되어야 하는지 말아야하는지"에 대한 판단을 객체 메소드를 통해 하고 있었습니다.

이 메소드는 컴포넌트의 움직임에 대한 정보로 객체가 가지기엔 부적절하다고 판단했습니다.

### 데이터 구조 통일

store의 property 모두 Array로 통일하고 불필요한 Type 검사를 줄였습니다.

이전에 Array와 Array가 아닌 것이 혼재되어 있어, store를 다룰 땐, 항상 Array Type인지 아닌지에 대한 검사를 행했었습니다.

## 외부 storage와의 통신 설계 변경

불필요한 추상화를 줄이고 **hook -> service -> storage** 구조로 다시 설계해보았습니다.

전 | 후
--- | ---
<img src="https://user-images.githubusercontent.com/40374023/228440387-fd047184-2a1b-4795-beb7-6133874c671d.png" /> | <img src="https://user-images.githubusercontent.com/40374023/228440394-06c3b969-c533-4703-bd39-971a86294ef2.png" />

### service 객체

useFetch 재사용을 위해 service 객체를 주입해 사용할 수 있도록 설계했습니다.

## Error 표현 픽스

### 전체 Input 중에 단 하나 밖에 표현안되던 Error 표현을 해결했습니다.

이제 invalid한 Input 모두에 에러가 표시됩니다.

Active

# 추가 된 점

말씀주신 UX 향상을 위한 몇가지 feature가 적용되면 좋겠다고 생각해서 적용해보았습니다.

## 만기년도가 현재 년도 이후이어야 함.

Expire Year는 이제 현재 년도 이후 년도만 입력할 수 있습니다.

### (의견) 년월 입력은 Date select 혹은 select box로 바꾸는 것이 좋을 것 같습니다.

직접 Number를 입력하는 것에는 valid 체크에 한계가 있고 사용자 입력면에서도 불편하다고 생각되어 Date select 혹은 select box로 입력이 가능한 숫자만 제공하는 것이 UX에서도 유지보수 면에서도 좋은 것 같습니다.

## cardCreate페이지 진입시 AutoFocus

cardCreate 페이지 진입했을 때, AutoFocus 및 invalid 체크가 되도록하여 사용자가 바로 입력할 수 있도록 했습니다. (UX 향상)

# 패키지 배포를 위한 수정 계획

다른 개발자들이 사용할 수 있도록 적절한 interface를 제공하기 위한 계획을 생각해보았습니다.

## 외부 storage 통신을 위한 service 객체 받기

useFetch에 들어갈 service 객체를 받아서 설정합니다.

**받은 service객체는 ServiceContext에 담아 App 전체에서 사용할 수 있도록 할 예정입니다.**

객체가 없다면 localStorage와 이어져있는 default service를 설정합니다.

### 비동기 함수를 직접 받는 이유

- 후에 Suspense 적용에 도움이 될 것으로 생각됐습니다.

- state를 노출시키거나 연결시키기 위한 로직이 굉장히 복잡해질 것으로 생각됐습니다.

감사합니다.

2023-04-02 03:40 UTC, JunilHwang approved these changes
안녕하세요 경준님!
리뷰가 많이 늦었네요 ㅠㅠ 죄송합니다 🙏

일단 복잡한 구조를 개선하려고 애쓰신게 보이네요 ㅎㅎ 고생하셨습니다 👍👍
전체적인 설계에 대한 리뷰를 드리자면,

CardModelClass (이지만 DOM 종속적인..) -> state -> store -> context -> hooks -> components

이런 모습인데요, model이 dom에 종속적인 모습이 적절한가 고민해본다면 그건 아닌 것 같아요.
최소한 context 에서 부터 DOM에 종속적이여야 하지 않을까요?
가령 ssr에 대해 고민해본다면 store는 server에서 정의해서 건내줄 수도 있거든요.
그런데 server가 dom에 종속적이면 당연히 오류가 발생하게 되겠죠?

그리고 `ApplicationContext`의 경우 service를 주입받아서 쓰고 있네요..! 리뷰할때는 몰랐는데 지금 생각해보니 외부에서(아예 다른 패키지에서) 이걸 주입해서 쓰고싶어서 그렇게 하신 것 같다는 생각이 들었어요 ㅎㅎ
그런데 package로 받아서 사용할 때는 service를 주입하는게 아니라 그냥 함수(addCard, deleteCard, updateCard 같은)를 주입해서 써야하지 않을까요? 

service를 정의해서 사용하는 과정도 굉장히 복잡하다고 느껴졌어요.

localStorageService -> ApplicationContext -> useFetch -> useFetchCardList

이런 단계인데, 여기서 useFetchCardList는 결국에 함수를 반환하고 있기 때문에, useFetchCardList가 진짜 서비스의 역할을 하는게 아닌가 싶었습니다.
결국 위에서 정의한건, storage -> cardService 이렇게 두 단계로 요약할 수 있는게 아닌가 싶고, cardService의 모습이 `fetchCard` `postCard` `deleteCard` 같은 메소드를 가지고 있으면 되지 않을까 싶습니다.

이 외에도 꽤 많은 코멘트를 남겼는데 차근차근 확인해보시면 될 것 같습니다!
Step3가 무척 길어진 상태라서, 이번 단계는 여기서 마무리하도록 하겠습니다 ㅎㅎ
이미 장바구니 미션 진행중이신 것 같아서, 마지막 미션 진행하실 때 참고하시면 될 것 같아요!

생각보다 더 긴 호흡을 함께했네요! 같이할 수 있어서 즐거웠습니다 경준님 😁
끝까지 잘 마무리하기를 기대하겠습니다! 화이팅 💪💪

2023-04-02 03:40 UTC, JunilHwang commented on .storybook/preview.js
> +window.jest = jest;
오잉..? window에서 jest를 쓰일 일이 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +  );
음... some을 이렇게 사용해도 괜찮을걸까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/array.ts
> +  return new Array(arrayLength).fill(1).map(callback);
new는 여기서 생략해도 무방하답니다 ㅋㅋ

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/object.ts
> +  return Object.entries(obj) as [keyof T, T[keyof T]][];
타입 단언을 해주고 있기 때문에, 이렇게 return type은 정의하지 않아도 무방할 것 같아요!
```ts
export function entryObject<T extends { [key: string | number | symbol]: unknown }>(obj: T) {
  return Object.entries(obj) as [keyof T, T[keyof T]][];
```

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +      const isActiveElement = cardState.ref === document.activeElement;
activeElement는 처음 보네요 ㅎㅎ 덕분에 알아갑니다 👍

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +      const isActiveElement = cardState.ref === document.activeElement;
`isActiveElement` 라는 이름은 함수에 어울리는 이름 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +  return activeState;
```tsx
  return cardStore
    .flatMap(cardStates => [cardStates])
    .find(cardState => cardState.ref === document.activeElement);
```
이렇게 표현할 수 있을 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +}
앞선 리뷰와 비슷한데요,
```tsx
export function findInvalidStoreAndFocus(cardStore: TCardState[][]) {
  
  const invalidState =  cardStore.flatMap(cardStates => !cardState.value || !!cardState.errorMessage);
  invalidState?.ref?.focus();

  return invalidState;
}
```
이렇게 표현할 수 있겠네요 ㅎㅎ
그런데 focus를 여기서 하는건 좋지 않은 방법 같아요.
기본적으로 함수는 한 가지 일만 하는게 좋다고 생각하는데, 지금은 두 가지 일을 하는 것 같아서요!

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +export function findInvalidStoreAndFocus(cardStore: TCardState[][]): TCardState | null {
앞선 리뷰를 토대로 작성해본다면, return type은 정의하지 않아도 자동으로 추론되지 않을까 싶네요!

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
> +export function findActiveState(cardStore: TCardState[][]): TCardState | null {
앞선 리뷰와 동일합니다!

2023-04-02 03:40 UTC, JunilHwang commented on src/utils/card/card.ts
지금 이 파일에 정의된 함수들의 경우 전부다 TCardStore에 종속적인 모습을 확인할 수 있는데, 파일 위치를 아예 `CardContext` 파일 근처 (`contexts/CardContext/utils`)로 옮기면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/types/cards.ts
> +export type TSecurityCode = string;
이렇게 type을 표현했을 때 어떤 장점이 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/types/cards.ts
> +  theme: Themes;
`theme`라는 단수 프로퍼티에 `Themes`라는 복수 타입이 할당되는게 뭔가 부자연스러워보여요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/index.ts
> +export * from './types';
ApplicationContext와 CardContext도 index.ts에서 같이 내보내주면 어떨까요?
그리고 폴더 내부에 context만 있는게 아니라 provider까지 같이 있기 때문에

- ApplicationContext -> application
- CardContext -> card

이렇게 표현하면 어떨까 싶네요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/types.ts
> +}
InputElement라는 type이 context 폴더에 위치해있는것도 부자연스러운 것 같아요..!
이 타입을 보고 이걸 context와 연관지어서 생각할 수 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/cardContext.ts
> +export const CardApiContext = createContext<TApiContext>(null);
파일 이름도 변수 이름에 맞춰서 PascalCase로 표현해주면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/CardProvider.tsx
> +  const cardContextApis = useMemo(() => ({ dispatch }), [dispatch]);
api라는 이름과는 어울리지 않게 dispatch 하나만 내보내주고 있어요!
어차피 사용하는 방식도 dispatch에 종속적이기 때문에
아예 `cardContextDispatch` 라고 표현하면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/CardProvider.tsx
> +  const [store, dispatch] = useReducer(cardStoreReducer, value || getInitialCardStore());
보통 reducer를 사용할 때 store라는 이름 대신 state라는 이름을 사용하는데요,
store는 state에 대한 action(dispatch)까지 포함해서 store라고 짓는 것 같아요!

그래서 여기서도 store 보다 state로 표현하면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/initialCardStore.ts
> +  cardCompanies: createArray(1, () => new CardCompanyInputElement({})),
length가 1인 배열을 만드는거면, createArray로 만들 필요가 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/initialCardStore.ts
> +  cardCompanies: createArray(1, () => new CardCompanyInputElement({})),
card prefix를 전체적으로 넣어주거나 혹은 빼거나, 일관성있게 관리해주면 더 좋을 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/models/index.ts
> +export * from './SecurityCode';
models라고 부르기엔 다 dom에 종속적이네요 ㅠㅠ
그래서 아예 models를 contexts 밖으로 빼고,
dom에 종속적인 코드도 분리하고,
이를 결합하는 방식으로 써야 하는게 아닌가 싶어요.

지금 구조를 보면

class(DOM 정보를 포함) => state -> context -> component

이른 흐름으로 쓰이고 있는데,

프론트엔드 개발에서 state라는건 결국 "데이터를 기반으로 UI를 표현"하는 수단인데,
DOM은 결국 UI Level에서 관리되어야 하는게 아닐까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/models/CardCompany.ts
> +  }
생성자, 멤버변수 정의, setRef 메소드 등은 전체적으로 똑같은 코드로 쓰이고 있네요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/CardContext/models/CardCompany.ts
> +  }
생성자는 멤버변수 선언부 하위에 선언해주는게 코드를 이해하기 더 수월할 것 같아요.
다른 사람이 이 코드를 봤을 때 이게 클래스 중간에 선언되어있으면, 생성자가 없다고 판단할 수도 있지 않을까요? 흐름이 끊긴달까... 그렇네요

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/service/localStorageService.ts
> +};
`localStorageService` 라는 이름과는 어울리지 않게 key가 `cardList`에 종속적이네요.

`Storage` -> `CardService`

이렇게 두 단계로 나눠서 관리해도 무방할 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/service/cardListServiceChecker.ts
> +  }
post랑 get이 적절한 async 함수인지 검사하고 있지 않은데, async 함수를 할당하라는 메세지는 적절하지 않은 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/type.ts
> +export type TCardList = { [cardId: string]: TCard };
이게 무척 혼란스러운데요,
전체적인 구조를 처음 보는 사람 입장에서 보면 CardContext가 이 Type을 가져야 하는게 더 자연스럽게 느껴질 것 같아요!
이게 어째서 `ApplicationContext`에 속해야 하는지,
그리고 Application이 아닌 `Domain` 혹은 `Model`이라는 것에 묶여야 하는게 아닌지 고민이 필요할 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/ApplicationProvider.tsx
> +}
service라는 이름 자체가, service에 무언가를 주입해서 쓰는 모습을 상상할 수 있어서, service를 provider로 관리할 필요가 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/ApplicationProvider.tsx
> +  const AppContextValue = useMemo(() => {
여기서 변수 이름은 camelCase로 표현해야 할 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/ApplicationContext/applicationContext.ts
> +export const ApplicationContext = createContext<TApplicationContextValue | null>(null);
마찬가지로 파일 명과 변수 명을 일치시키켜주면 좋겠네요!

2023-04-02 03:40 UTC, JunilHwang commented on src/components/Card/CardNumbers.tsx
> +        <CardNumber key={`card-number-${i}-${cardNumber.value}`} {...cardNumber} />
key에 value는 넣지 않아도 될 것 같네요 ㅎㅎ

2023-04-02 03:40 UTC, JunilHwang commented on src/components/Card/CardNumbers.tsx
>  }
지금 마스킹 처리하는게 제대로 작동하지 않는 것 같아요~

2023-04-02 03:40 UTC, JunilHwang commented on src/components/Portal/Portal.tsx
>  const MODAL_ROOT = 'modal-root';
이에 대한 element가 index.html에 정의되어있는데,
아예 App에서 정의해주면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetch/useFetch.ts
> +}
서비스의 모습을 이렇게 한정지어도 괜찮을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetch/useFetch.ts
> +}
react-query의 모습을 상상해보면 좋을 것 같은데, service를 한정된 모습으로 관리하는게 확장성에 용의하진 않은 것 같아요..!

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetchCardList/useFetchCardList.ts
> +  const { fetch, fetchedData } = useFetch<TCardList | null>(appContext?.service);
여기서 생각해볼 부분은, service가 사실은 그냥 localStorage라는거고, 이 localStorage는 한 개의 key만 사용할 수 있으며, 이에 대한 service도 한 개만 존재합니다.

그리고 

localStorage -> service -> useApplicationContext -> useFetch -> useFetchCardList

지금 이와 같은 모습으로 쓰이고 있는데요,

여전히 너무 복잡한 모습이 아닌가 싶어요..!

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetchCardList/useFetchCardList.ts
> +      fetch('post', fetchedData);
저는 fetch의 결과로 fetchedData가 만들어지는줄 알았는데, 반대로 fetchedData를 fetch에게 넘겨주는 방식이네요..?

2023-04-02 03:40 UTC, JunilHwang commented on src/contexts/types.ts
> +  isAllowToFocusNext: () => boolean;
어디서는 `is`라는 prefix가 붙으면 boolean 타입으로 쓰이고, 여기서는 함수로 쓰이고 있네요!?

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetchCardList/useFetchCardList.ts
> +export function useFetchCardList() {
이 hook이 `useFetch`를 내부적으로 쓰고 있다는게 이 hook을 가져다 쓰는 입장에서는 사실 큰 관심사가 아닐 것 같아요.
그래서 `useCardData` 처럼 표현하면 어떨가 싶네요!

2023-04-02 03:40 UTC, JunilHwang commented on src/hooks/useFetchCardList/useFetchCardList.ts
> +  return { cardList: fetchedData, postCard, deleteCard };
callbakc 함수만 반환할거라면, 이게 hook으로 쓰일 필요가 있을까요? 그냥 함수로 만들어도 되지 않을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +}
여기서 전부다 null을 반환하면, 이 함수를 가져다 쓸 때 무엇 때문에 check를 통과하지 못했는지 알기가 어려울 것 같아요. 요구사항에 더 디테일한 오류메세지를 보여줘야 한다는게 생긴다면, 이 코드를 어떤식으로 개선해야 좋을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +  return cardCompanyList[changeNumberIntoLimit(index, cardCompanyList.length)];
```tsx
  return cardCompanyList[Math.min(index, cardCompanyList.length - 1)];
```
이렇게 표현하는게 이 코드를 보는사람 입장에서 이해하기 더 쉽지 않을까요?

이게 범용성의 차이라고 생각하는데, `changeNumberIntoLimit`과 `Math.min`의 차이가 사실 거의 없고, `Math.min`은 누구나(아마도?) 알고 있는 메소드라서 이럴 때는 "누구나 알고 있는" Math.min을 쓰는게 좋을 것 같아요 ㅎㅎ

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +function changeNumberIntoLimit(number: number, limit: number) {
이 함수의 경우 `limitNumber` 처럼 이름을 지어줘도 괜찮을 것 같아요!

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +export function autoCompanyChecker(cardNumber?: string | null) {
`getCompanyByCardNumber` 처럼 표현하면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +export function autoCompanyChecker(cardNumber?: string | null) {
이 코드의 경우 `CompanyList`에 종속적인 모습을 보이는데요,
이런게 바로 도메인 로직이 아닐까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/constants/cardCompanyList.ts
> +export const cardCompanyList: TCardCompany[] = [
상수로 쓰이고 있기 때문에, 대문자로 표현하면 어떨까 싶어요!

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useCardCompanySelectModal/CardCompanySelector/components/CardCompany/CardCompany.tsx
>        }}
```tsx
      onClick={() => onClick?.(cardCompany)}
```
이렇게 표현해도 된답니다!

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useCardCompanySelectModal/CardCompanySelector/CardCompanySelector.tsx
> +export const CardCompanySelector = memo(function CardCompanySelector({ onCardCompanyClick }: CardCompanySelectorProps) {
hooks 내부에 이런 component 파일이 위치해있는게 어색하네요..! 아예 밖으로 빼면 어떨까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useCardCompanySelectModal/CardCompanySelector/components/CardCompany/CardCompany.tsx
> +export function CardCompany({ cardCompany, onClick }: CardCompanyProps) {
앞선 내용과 동일합니다.

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/hooks/useInvalidFinderOnMount.ts
> +    findInvalidStoreAndFocus(cardStore);
이 함수는 사이드 이펙트가 존재하는 함수인데,
이게 utils라고 볼 수 있을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/CardCreator.tsx
>        <SubmitButton />
Submit에 대한 동작을 Creator에서 정의해줘야 하지 않을까요?

2023-04-02 03:40 UTC, JunilHwang commented on src/pages/CardCreator/SubmitButton/hooks/useCardSubmitEvent.ts
> +}
현재 구조에서는 이 hook이 button에 종속적인데, 그래도 괜찮을까요?

2023-04-02 03:40 UTC, JunilHwang approved these changes
안녕하세요 경준님!
리뷰가 많이 늦었네요 ㅠㅠ 죄송합니다 🙏

일단 복잡한 구조를 개선하려고 애쓰신게 보이네요 ㅎㅎ 고생하셨습니다 👍👍
전체적인 설계에 대한 리뷰를 드리자면,

CardModelClass (이지만 DOM 종속적인..) -> state -> store -> context -> hooks -> components

이런 모습인데요, model이 dom에 종속적인 모습이 적절한가 고민해본다면 그건 아닌 것 같아요.
최소한 context 에서 부터 DOM에 종속적이여야 하지 않을까요?
가령 ssr에 대해 고민해본다면 store는 server에서 정의해서 건내줄 수도 있거든요.
그런데 server가 dom에 종속적이면 당연히 오류가 발생하게 되겠죠?

그리고 `ApplicationContext`의 경우 service를 주입받아서 쓰고 있네요..! 리뷰할때는 몰랐는데 지금 생각해보니 외부에서(아예 다른 패키지에서) 이걸 주입해서 쓰고싶어서 그렇게 하신 것 같다는 생각이 들었어요 ㅎㅎ
그런데 package로 받아서 사용할 때는 service를 주입하는게 아니라 그냥 함수(addCard, deleteCard, updateCard 같은)를 주입해서 써야하지 않을까요? 

service를 정의해서 사용하는 과정도 굉장히 복잡하다고 느껴졌어요.

localStorageService -> ApplicationContext -> useFetch -> useFetchCardList

이런 단계인데, 여기서 useFetchCardList는 결국에 함수를 반환하고 있기 때문에, useFetchCardList가 진짜 서비스의 역할을 하는게 아닌가 싶었습니다.
결국 위에서 정의한건, storage -> cardService 이렇게 두 단계로 요약할 수 있는게 아닌가 싶고, cardService의 모습이 `fetchCard` `postCard` `deleteCard` 같은 메소드를 가지고 있으면 되지 않을까 싶습니다.

이 외에도 꽤 많은 코멘트를 남겼는데 차근차근 확인해보시면 될 것 같습니다!
Step3가 무척 길어진 상태라서, 이번 단계는 여기서 마무리하도록 하겠습니다 ㅎㅎ
이미 장바구니 미션 진행중이신 것 같아서, 마지막 미션 진행하실 때 참고하시면 될 것 같아요!

생각보다 더 긴 호흡을 함께했네요! 같이할 수 있어서 즐거웠습니다 경준님 😁
끝까지 잘 마무리하기를 기대하겠습니다! 화이팅 💪💪

2023-04-02 03:41 UTC, merged

2023-04-03 14:11 UTC, Jay-WKJun commented on src/utils/card/card.ts
> +}
이미 이름에서도 2가지의 일을 한다고 되어있네요!

역할 분리를 좀 더 신경써야겠습니다 ㅎㅎ

2023-04-03 14:12 UTC, Jay-WKJun commented on src/utils/card/card.ts
오 그쪽이 더 적합하겠네요! 감사합니다 👍

2023-04-03 14:14 UTC, Jay-WKJun commented on src/types/cards.ts
> +export type TSecurityCode = string;
현재 App에서 다루는 비즈니스 타입들에 이름을 부여해 명확히 활용할 수 있다고 생각합니다.

2023-04-03 14:16 UTC, Jay-WKJun commented on src/contexts/index.ts
> +export * from './types';
이건 일부러 Application과 Card의 Directory를 노출시켜서 제공했습니다.

Context가 export하는 내용들이 비슷하기 때문에, import {} 를 펼쳤을 때, 굉장히 헷갈릴 수 있기 때문입니다.

2023-04-03 14:17 UTC, Jay-WKJun commented on src/contexts/index.ts
> +export * from './types';
네이밍은 훨씬 적절한 네이밍 같네요! 감사합니다! 😁

2023-04-03 14:18 UTC, Jay-WKJun commented on src/contexts/types.ts
> +}
음... 그러네요,,,, App 전체에서 다루는 비즈니스 타입인 만큼 최상위에 두는게 맞을것 같네요,,,

2023-04-03 14:20 UTC, Jay-WKJun commented on src/contexts/CardContext/CardProvider.tsx
> +  const cardContextApis = useMemo(() => ({ dispatch }), [dispatch]);
혹시나 하는 다른 Api의 확장을 생각해서 네이밍을 Apis라고 추상적으로 두었는데, useReducer인 이상 다른 Api가 낄 틈은 없어보이네요! 감사합니다! 😁

2023-04-03 14:21 UTC, Jay-WKJun commented on src/contexts/CardContext/CardProvider.tsx
> +  const [store, dispatch] = useReducer(cardStoreReducer, value || getInitialCardStore());
아! 그렇군요,,, 말씀대로 state가 더 적절해보이네요! 감사합니다 🙌

2023-04-03 14:23 UTC, Jay-WKJun commented on src/contexts/CardContext/initialCardStore.ts
> +  cardCompanies: createArray(1, () => new CardCompanyInputElement({})),
음,,, 제 의도는 가독성을 위해 코드의 일관성을 유지하려 했었습니다,,

말씀대로 createArray일 필요는 없는 것 같습니다.

2023-04-03 14:25 UTC, Jay-WKJun commented on src/contexts/CardContext/initialCardStore.ts
> +  cardCompanies: createArray(1, () => new CardCompanyInputElement({})),
변수명이 길어지는걸 경계했었는데, 역시 가독성에 좋지 않은 것 같군요. 일관성있게 바꾸도록 하겠습니다!

2023-04-03 14:40 UTC, Jay-WKJun commented on src/contexts/CardContext/models/index.ts
> +export * from './SecurityCode';
사용자에 의해 InputElement에 입력된 data의 validation과 focus를 연관짓기 위해 하나의 객체로 묶어 관리하려는 의도였습니다.

제가 준일님의 개선사항을 이해한 바로는 DOM은 React 안에서만 다뤄져야한다. 라고 이해했는데 혹시 맞을까요?

확실히 독립적이어야하는 model들이 DOM이라는 side-Effect를 일으키는 것으로 생각되네요.
코드 수정에도 DOM 종속성으로 인한 문제가 발생할 수 있을 것 같습니다.

2023-04-03 14:46 UTC, Jay-WKJun commented on src/contexts/CardContext/models/index.ts
> +export * from './SecurityCode';
invalid에 의한 DOM focus 유발 방식을 바꾸고 전체 input을 관리하는 state를 두어 관리할 수 있을 것 같습니다.

다시 리팩토링 해보겠습니다. 🙂

2023-04-03 14:56 UTC, Jay-WKJun commented on src/contexts/ApplicationContext/type.ts
> +export type TCardList = { [cardId: string]: TCard };
밖에서 카드 정보를 줄 때, value만 줘도 받아들일 수 있게 객체를 재정의한 것입니다.

훨씬 더 단순화할 필요가 있을 것 같습니다,,,,

감사합니다. 🙂

2023-04-03 14:58 UTC, Jay-WKJun commented on src/contexts/ApplicationContext/ApplicationProvider.tsx
> +}
Application 어디서도 사용할 수 있도록 하고 싶었습니다.

2023-04-03 15:01 UTC, Jay-WKJun commented on src/hooks/useFetch/useFetch.ts
> +}
그래서 generic K를 통해 service를 자유롭게 확장해서 사용할 수 있도록 function을 override할 수 있도록 해두었습니다.

2023-04-03 15:09 UTC, Jay-WKJun commented on src/hooks/useFetchCardList/useFetchCardList.ts
> +  const { fetch, fetchedData } = useFetch<TCardList | null>(appContext?.service);
그럼 react-query처럼 get과 post를 수행하는 함수를 callback으로 넣어주는 게 훨씬 확장성 있고 좋을 수 있겠네요.

함수를 주입해주면 service에 하나의 key만 묶여있는 부분도 해결할 수 있을 것 같습니다.

감사합니다. 👍

2023-04-03 15:09 UTC, Jay-WKJun commented on src/contexts/types.ts
> +  isAllowToFocusNext: () => boolean;
ㅎㅎㅎㅎㅎ 그러네욥;;;

2023-04-03 15:13 UTC, Jay-WKJun commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +}
오,,, 그러네요,,, invalid라고 판단되는 부분에 구체적인 메세지를 전달해주면 좋겠네요.

2023-04-03 15:15 UTC, Jay-WKJun commented on src/pages/CardCreator/hooks/useAutoCompanyChecker/autoCompanyChecker.ts
> +export function autoCompanyChecker(cardNumber?: string | null) {
네 맞습니다.

그래서, 테스트하기 좋게 로직 격리에 신경을 썻습니다. ㅎㅎ

2023-04-03 15:27 UTC, Jay-WKJun commented on src/pages/CardCreator/SubmitButton/hooks/useCardSubmitEvent.ts
> +}
MouseEvent에는 종석적이지만, button에 종속적이진 않다고 생각됩니다 ㅎㅎ

혹시 어떤 부분때문에 button에 종속적이라고 판단하셨는지 여쭤봐도될까요?

2023-04-04 09:19 UTC, JunilHwang commented on src/contexts/index.ts
> +export * from './types';
@Jay-WKJun 

> export하는 내용들이 비슷하기 때문에

반대로 생각하면 export 하는 내용이 비슷해서 헷갈린다는 것 자체가 무언가 잘못된게 아닐까요? 🤔

2023-04-04 09:26 UTC, JunilHwang commented on src/pages/CardCreator/SubmitButton/hooks/useCardSubmitEvent.ts
> +}
이름이 `submit`을 처리하는건데, 실제로는 `mouse event`를 받아서 처리하는 구조라서요!
그리고 hook이 SubmitButton 내부에 있기 때문에 이건 SubmitButton 내부에서만 쓰이는건가? 라는 생각이 든답니다 ㅎㅎ
이런 로직은 Button이 아니라 Form에 종속적이여야 하지 않을까요?

2023-04-06 12:28 UTC, Jay-WKJun commented on src/pages/CardCreator/SubmitButton/hooks/useCardSubmitEvent.ts
> +}
아! 그렇군요! 순수하게 `submit`을 위한 로직 뿐만아니라 eventListener가 통째로 구현되어 있어서 그렇군요!

말씀처럼 Element가 아닌 Form에 종속적으로 하는 것이 맞는 것 같습니다!
감사합니다. 😁

2023-04-06 12:36 UTC, Jay-WKJun commented on src/contexts/index.ts
> +export * from './types';
export하는 내용이 비슷해서 import시에 헷갈리는 경우는 각 Context 디렉토리에 속한 module안의 변수와 함수들의 네이밍이 unique하지 않고 동일하거나 구별이 잘 안되게 네이밍 된 경우라고 생각됩니다.

module안의 변수나 함수들이 프로젝트에서 unique한 이름을 갖지 않는건 문제가 될 수 있을 것 같네요!

unique한 이름이 아니라면 IDE의 검색면에서도 import면에서도 불편해져 코드관리에도 불편해질 것 같네요.